import { IVariables } from '@tamm/app-composer';
import { AMENDMENT_TYPES } from 'client/config/amendments/constants/amendmentObjects';
import { UAE } from 'client/config/amendments/constants';

const partnersStructure = {
  type: '',
  nameEn: '',
  nameAr: '',
  firstNameEn: '',
  firstNameAr: '',
  lastNameEn: '',
  lastNameAr: '',
  licenceNo: '',
  companyNameEn: '',
  companyNameAr: '',
  profileType: '',
  typeArb: '',
  referenceContactId: '',
  emiratesId: '',
  sharePercentage: 1,
  sharePercentageLog: '',
  representativeTypeEng: '',
  representativeTypeArb: '',
  pEmail: '',
  bDate: '',
  phoneNumber: '',
  passportNumber: '',
  nationalityAr: '',
  nationality: '',
  nationalityLog: '',
  domicile: '',
  contactId: '',
};
const managerStructure = {
  type: '',
  nameEn: '',
  nameAr: '',
  firstNameEn: '',
  firstNameAr: '',
  lastNameEn: '',
  lastNameAr: '',
  profileType: '',
  typeArb: '',
  referenceContactId: '',
  emiratesId: '',
  sharePercentage: '',
  sharePercentageLog: '',
  representativeTypeEng: '',
  representativeTypeArb: '',
  pEmail: '',
  bDate: '',
  phoneNumber: '',
  passportNumber: '',
  nationalityAr: '',
  nationality: '',
  nationalityLog: '',
  contactId: '',
};
const localAgentStructure = {
  type: '',
  nameEn: '',
  nameAr: '',
  firstNameEn: '',
  firstNameAr: '',
  lastNameEn: '',
  lastNameAr: '',
  profileType: '',
  typeArb: '',
  referenceContactId: '',
  emiratesId: '',
  sharePercentage: '',
  sharePercentageLog: '',
  representativeTypeEng: '',
  representativeTypeArb: '',
  pEmail: '',
  bDate: '',
  phoneNumber: '',
  passportNumber: '',
  nationalityAr: '',
  nationality: UAE,
  nationalityLog: '',
  contactId: '',
};
const heirsStructure = {
  type: '',
  nameEn: '',
  nameAr: '',
  firstNameEn: '',
  firstNameAr: '',
  lastNameEn: '',
  lastNameAr: '',
  profileType: '',
  typeArb: '',
  referenceContactId: '',
  emiratesId: '',
  sharePercentage: '',
  sharePercentageLog: '',
  representativeTypeEng: '',
  representativeTypeArb: '',
  pEmail: '',
  bDate: '',
  phoneNumber: '',
  passportNumber: '',
  nationalityAr: '',
  nationality: '',
  nationalityLog: '',
  contactId: '',
};
const repStructure = {
  type: '',
  nameEn: '',
  nameAr: '',
  firstNameEn: '',
  firstNameAr: '',
  lastNameEn: '',
  lastNameAr: '',
  profileType: '',
  typeArb: '',
  referenceContactId: '',
  emiratesId: '',
  sharePercentage: '',
  sharePercentageLog: '',
  representativeTypeEng: '',
  representativeTypeArb: '',
  pEmail: '',
  bDate: '',
  phoneNumber: '',
  passportNumber: '',
  nationalityAr: '',
  nationality: '',
  nationalityLog: '',
  contactId: '',
};

const representativeStructure: IVariables = {
  [AMENDMENT_TYPES.PARTNERS]: partnersStructure,
  [AMENDMENT_TYPES.LOCAL_AGENT]: localAgentStructure,
  [AMENDMENT_TYPES.MANAGERS]: managerStructure,
  [AMENDMENT_TYPES.HEIRS]: heirsStructure,
  [AMENDMENT_TYPES.REPRESENTATIVES]: repStructure,
};

export default representativeStructure;
