import { IVariables } from '@tamm/app-composer';
import { upperFirst, startCase, camelCase } from 'lodash';

const CATEGORIES = [
  { 'Nature En': 'ADVOCATE OFFICES', 'Nature Ar': 'مكاتب المحاماة' },
  { 'Nature En': 'AGENCIES', 'Nature Ar': 'الوكالات' },
  { 'Nature En': 'AGRICULTURE', 'Nature Ar': 'الزراعة' },
  { 'Nature En': 'ANIMAL HUSBANDRY', 'Nature Ar': 'تربية الحيوانات' },
  {
    'Nature En': 'ANIMAL SHELTERING SERVICES',
    'Nature Ar': 'خدمات إيواء الحيوانات',
  },
  { 'Nature En': 'ART GALLERY', 'Nature Ar': 'صالات عرض الاعمال الفنية' },
  { 'Nature En': 'AUDITING OFFICES', 'Nature Ar': 'مكاتب تدقيق الحسابات' },
  { 'Nature En': 'BAKERIES AND SWEETS', 'Nature Ar': 'المخابز والحلويات' },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
  },
  { 'Nature En': 'BEAUTY', 'Nature Ar': 'التجميل' },
  { 'Nature En': 'BROKERAGE SERVICES', 'Nature Ar': 'خدمات الوساطة' },
  {
    'Nature En': 'BUILDING CLEANING AND OTHER CLEANING SERVICES',
    'Nature Ar': 'خدمات تنظيف المباني والتنظيفات الاخرى',
  },
  { 'Nature En': 'CARGO SERVICES', 'Nature Ar': 'خدمات الشحن' },
  {
    'Nature En': 'CEREMONY AND PARTY AND HALLS',
    'Nature Ar': 'صالات الافراح والمناسبات',
  },
  {
    'Nature En': 'CINEMAS AND THEATERS',
    'Nature Ar': 'صالات العرض السينمائية والمسارح',
  },
  { 'Nature En': 'CREATIVE ACTIVITIES', 'Nature Ar': 'أنشطة مبدعة' },
  { 'Nature En': 'DECORATION WORKS', 'Nature Ar': 'أعمال تنفيذ الديكور' },
  { 'Nature En': 'EDUCATION', 'Nature Ar': 'التعليم' },
  {
    'Nature En': 'EDUCATIONAL TRAVEL SERVICES',
    'Nature Ar': 'خدمات تنظيم الرحلات التربوية',
  },
  {
    'Nature En': 'EXTRACTION ACTIVITIES (EXPLORATION)',
    'Nature Ar': 'الأنشطة الاستخراجية (البحث والتنقيب)',
  },
  { 'Nature En': 'FISHING', 'Nature Ar': 'الصيد' },
  {
    'Nature En': 'FLOORING AND FURNITURE INSTALLATION',
    'Nature Ar': 'تركيب الأثاث والارضيات',
  },
  {
    'Nature En': 'FORUMS AND BUSINESSMEN COUNCILS',
    'Nature Ar': 'المنتديات ومجالس رجال الاعمال',
  },
  {
    'Nature En': 'FUNERALS AND RELATED SERVICES',
    'Nature Ar': 'الجنازات ومايتصل بها',
  },
  {
    'Nature En': 'GOVERNMENT LIAISON OFFICES AND INTERNATIONAL ORGANIZATIONS',
    'Nature Ar': 'مكاتب الارتباط الحكومي والمنظمات الدولية',
  },
  {
    'Nature En': 'HAJJ AND UMRAH SERVICES',
    'Nature Ar': 'خدمات تنظيم رحلات الحج والعمرة',
  },
  { 'Nature En': 'HANDICRAFTS', 'Nature Ar': 'الأعمال الحرفية الفنية' },
  { 'Nature En': 'INDUSTRY', 'Nature Ar': 'الصناعة' },
  { 'Nature En': 'INSURANCE SERVICES', 'Nature Ar': 'خدمات التأمين' },
  { 'Nature En': 'KEY DUPLICATION SERVICES', 'Nature Ar': 'نسخ المفاتيح' },
  { 'Nature En': 'LABOR SUPPLY OFFICES', 'Nature Ar': 'مكاتب تزويد العمالة' },
  { 'Nature En': 'LABORATORIES', 'Nature Ar': 'المختبرات' },
  {
    'Nature En': 'LANDSCAPING SERVICES',
    'Nature Ar': 'خدمات التجميل والتنسيق للمواقع',
  },
  {
    'Nature En': 'LEATHER PRODUCTS REPAIRING AND CLEANING',
    'Nature Ar': 'اصلاح وتنظيف المنتجات الجلدية',
  },
  { 'Nature En': 'LIBRARIES', 'Nature Ar': 'مكتبات خاصة للقراءة' },
  {
    'Nature En': 'MAINTENANCE, INSTALLATION AND CONTRACTING WORKS',
    'Nature Ar': 'أعمال المقاولات والصيانه والتركيبات',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
  },
  { 'Nature En': 'MARKETING SERVICES', 'Nature Ar': 'الخدمات التسويقية' },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
  },
  {
    'Nature En': 'MINING AND METAL PROCESSING',
    'Nature Ar': 'تعدين  ومعالجة المعادن',
  },
  {
    'Nature En': 'MONEY TRANSPORT AND BANK SECURITY SERVICES',
    'Nature Ar': 'خدمات أمن البنوك ونقل الاموال',
  },
  { 'Nature En': 'MUSEUMS', 'Nature Ar': 'المتاحف' },
  { 'Nature En': 'NATURAL RESERVES', 'Nature Ar': 'المحميات' },
  {
    'Nature En': 'OIL AND GAS EXTRACTION AND THE RELEVANT SERVICES',
    'Nature Ar': 'استخراج النفط والغاز والخدمات ذات العلاقة',
  },
  {
    'Nature En':
      'ORGANIZATIONAL SERVICES (EVENTS - CONFERENCES - EXHIBITIONS - CEREMONIES)',
    'Nature Ar': 'خدمات تنظيم (الفعاليات - المؤتمرات - المعارض والمناسبات)',
  },
  { 'Nature En': 'OTHER OCCUPATIONS', 'Nature Ar': 'الأعمال الحرفية الأخرى' },
  { 'Nature En': 'OTHER SERVICES', 'Nature Ar': 'الخدمات الاخرى' },
  {
    'Nature En': 'PARKS AND RECREATIONAL ACTIVITIES',
    'Nature Ar': 'الحدائق والخدمات الترفيهية',
  },
  {
    'Nature En': 'PEOPLE OF DETERMINATION ACTIVITIES',
    'Nature Ar': 'أنشطة اصحاب الهمم',
  },
  { 'Nature En': 'PHOTOGRAPHY', 'Nature Ar': 'التصوير' },
  {
    'Nature En': 'PRINTING, PUBLISHING AND RELATED SERVICE',
    'Nature Ar': 'الطباعة والنشر  والخدمات المتعلقه بها',
  },
  { 'Nature En': 'PROFESSIONAL ACTIVITIES', 'Nature Ar': 'الانشطة المهنية' },
  {
    'Nature En': 'PROJECT INVESTMENTS',
    'Nature Ar': 'الاستثمارات في المشاريع',
  },
  { 'Nature En': 'PUBLIC AUCTION HALLS', 'Nature Ar': 'صالات المزاد العلني' },
  { 'Nature En': 'REAL ESTATE SERVICES', 'Nature Ar': 'الخدمات العقارية' },
  { 'Nature En': 'RENT SERVICES', 'Nature Ar': 'خدمات التأجير' },
  { 'Nature En': 'REPAIRING AND MAINTENANCE', 'Nature Ar': 'الاصلاح والصيانة' },
  { 'Nature En': 'REPRESENTATION OFFICES', 'Nature Ar': 'مكاتب التمثيل' },
  {
    'Nature En':
      'RESTAURANTS, CAFETERIAS, CATERING AND MEAL PREPARATION SERVICES.',
    'Nature Ar': 'المطاعم  والكافتيريات وخدمات التموين اعداد الوجبات',
  },
  { 'Nature En': 'RETAIL', 'Nature Ar': 'البيع بالتجزئة' },
  {
    'Nature En': 'SECURITY AND GUARDING SERVICES',
    'Nature Ar': 'خدمات الامن والحراسة',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
  },
  { 'Nature En': 'SERVICES ACTIVITIES', 'Nature Ar': 'انشطة الخدمات' },
  {
    'Nature En': 'SMALL PRODUCER ACTIVITIES',
    'Nature Ar': 'أنشطة صغار المنتجين',
  },
  {
    'Nature En': 'SOCIAL AND CULTURAL SERVICES',
    'Nature Ar': 'الخدمات الاجتماعية والثقافية',
  },
  {
    'Nature En': 'SPORTS CLUBS AND RELEVANT SERVICES',
    'Nature Ar': 'الاندية الرياضية والخدمات المتعلقه بها',
  },
  { 'Nature En': 'STORAGE', 'Nature Ar': 'التخزين' },
  { 'Nature En': 'TAILORING', 'Nature Ar': 'تفصيل وخياطة المنسوجات' },
  {
    'Nature En': 'TAJER ABUDHABI ACTIVITIES',
    'Nature Ar': 'أنشطة تاجر أبوظبي',
  },
  { 'Nature En': 'TAXATION SERVICES', 'Nature Ar': 'الخدمات الضريبية' },
  {
    'Nature En': 'TECHNICAL AND OCCUPATIONAL INSPECTION SERVICES',
    'Nature Ar': 'خدمات الفحص الفني والمهني',
  },
  { 'Nature En': 'TECHNOLOGY', 'Nature Ar': 'تكنولوجيا' },
  { 'Nature En': 'TECHNOLOGY ACTIVITIES', 'Nature Ar': 'انشطة التكنولوجيا' },
  { 'Nature En': 'TELECOMMUNICATIONS', 'Nature Ar': 'الاتصالات' },
  {
    'Nature En': 'TEXTILE AND CARPET CLEANING SERVICES',
    'Nature Ar': 'خدمات غسيل المنسوجات والسجاد',
  },
  { 'Nature En': 'TOURISM', 'Nature Ar': 'السياحة' },
  { 'Nature En': 'TRADE CENTERS', 'Nature Ar': 'المراكز التجارية' },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
  },
  { 'Nature En': 'TRANSPORTATION SERVICES', 'Nature Ar': 'خدمات النقل' },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
  },
  {
    'Nature En': 'WASTE COLLECTION WORKS',
    'Nature Ar': 'أعمال تجميع النفايات',
  },
  { 'Nature En': 'WASTE TREATMENT', 'Nature Ar': 'معالجة النفايات' },
  { 'Nature En': 'WHOLESALE', 'Nature Ar': 'التجارة بالجملة' },
  {
    'Nature En': 'WORKSHOP AND PAINTING WORKS',
    'Nature Ar': 'أعمال الورش والطلاء',
  },
];
const SUBCATEGORIES = [
  {
    'Nature En': 'ADVOCATE OFFICES',
    'Nature Ar': 'مكاتب المحاماة',
    'Subnature En': 'Advocate Offices',
    'Subnature Ar': 'مكاتب المحاماه',
  },
  {
    'Nature En': 'AGENCIES',
    'Nature Ar': 'الوكالات',
    'Subnature En': 'Advertising Agent',
    'Subnature Ar': 'وكيل دعاية واعلان',
  },
  {
    'Nature En': 'AGENCIES',
    'Nature Ar': 'الوكالات',
    'Subnature En': 'Commercial Agent',
    'Subnature Ar': 'وكيل تجاري',
  },
  {
    'Nature En': 'AGENCIES',
    'Nature Ar': 'الوكالات',
    'Subnature En': 'Insurance Agent',
    'Subnature Ar': 'وكيل تأمين',
  },
  {
    'Nature En': 'AGENCIES',
    'Nature Ar': 'الوكالات',
    'Subnature En': 'Liner Agent (Land, Air, Marine)',
    'Subnature Ar': 'وكيل خطوط ( بري - جوي- بحري )',
  },
  {
    'Nature En': 'AGENCIES',
    'Nature Ar': 'الوكالات',
    'Subnature En': 'Postal Agency',
    'Subnature Ar': 'وكالات بريدية',
  },
  {
    'Nature En': 'AGENCIES',
    'Nature Ar': 'الوكالات',
    'Subnature En': 'Registration Agent',
    'Subnature Ar': 'وكلاء تسجيل',
  },
  {
    'Nature En': 'AGRICULTURE',
    'Nature Ar': 'الزراعة',
    'Subnature En': 'Agricultural Services',
    'Subnature Ar': 'الخدمات الزراعية',
  },
  {
    'Nature En': 'AGRICULTURE',
    'Nature Ar': 'الزراعة',
    'Subnature En': 'Crop Farming',
    'Subnature Ar': 'زراعة المحاصيل',
  },
  {
    'Nature En': 'AGRICULTURE',
    'Nature Ar': 'الزراعة',
    'Subnature En': 'Crustacean And Fish Farms',
    'Subnature Ar': 'مزرعة اسماك وقشريات',
  },
  {
    'Nature En': 'AGRICULTURE',
    'Nature Ar': 'الزراعة',
    'Subnature En': 'Pearl Farming',
    'Subnature Ar': 'زراعة اللؤلؤ',
  },
  {
    'Nature En': 'ANIMAL HUSBANDRY',
    'Nature Ar': 'تربية الحيوانات',
    'Subnature En': 'Animal Husbandry',
    'Subnature Ar': 'تربية الحيوانات',
  },
  {
    'Nature En': 'ANIMAL HUSBANDRY',
    'Nature Ar': 'تربية الحيوانات',
    'Subnature En': 'Animal Production',
    'Subnature Ar': 'الانتاج الحيواني',
  },
  {
    'Nature En': 'ANIMAL HUSBANDRY',
    'Nature Ar': 'تربية الحيوانات',
    'Subnature En': 'Animal Slaughter (Slaughterhouses)',
    'Subnature Ar': 'ذبح الحيوانات (المسالخ)',
  },
  {
    'Nature En': 'ANIMAL SHELTERING SERVICES',
    'Nature Ar': 'خدمات إيواء الحيوانات',
    'Subnature En': 'Animal Sheltering Services',
    'Subnature Ar': 'خدمات إيواء الحيوانات',
  },
  {
    'Nature En': 'ART GALLERY',
    'Nature Ar': 'صالات عرض الاعمال الفنية',
    'Subnature En': 'Art Gallery',
    'Subnature Ar': 'صالات عرض الاعمال الفنية',
  },
  {
    'Nature En': 'AUDITING OFFICES',
    'Nature Ar': 'مكاتب تدقيق الحسابات',
    'Subnature En': 'Auditing Offices',
    'Subnature Ar': 'مكاتب تدقيق الحسابات',
  },
  {
    'Nature En': 'BAKERIES AND SWEETS',
    'Nature Ar': 'المخابز والحلويات',
    'Subnature En': 'Bakeries And Sweets',
    'Subnature Ar': 'المخابز والحلويات',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Brokerage Services',
    'Subnature Ar': 'خدمات  الوساطة',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Business Bank',
    'Subnature Ar': 'مصرف أعمال',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Credit And Finance Bank',
    'Subnature Ar': 'مصرف ائتمان و تمويل',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Development Funds',
    'Subnature Ar': 'صناديق التنمية',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Exchange Facilities',
    'Subnature Ar': 'محلات الصرافة',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Finance',
    'Subnature Ar': 'التمويل',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Finance Lease Services',
    'Subnature Ar': 'خدمات التأجير المالي',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Financial Market Management',
    'Subnature Ar': 'إدارة الأسواق المالية',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Financial Services',
    'Subnature Ar': 'الخدمات المالية',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Foreign Commercial Bank',
    'Subnature Ar': 'مصرف تجاري اجنبي',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Investment Bank',
    'Subnature Ar': 'مصرف استثماري',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Islamic Bank',
    'Subnature Ar': 'مصرف أسلامى',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Local Commercial Bank',
    'Subnature Ar': 'مصرف تجاري محلي',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Savings Bank',
    'Subnature Ar': 'مصرف ادخاري',
  },
  {
    'Nature En': 'BANKS AND FINANCIAL SERVICES',
    'Nature Ar': 'المصارف والخدمات المالية',
    'Subnature En': 'Shares, Currencies And Securities Sales Brokerage',
    'Subnature Ar': 'الوساطه في بيع الاسهم والسندات والعملات',
  },
  {
    'Nature En': 'BEAUTY',
    'Nature Ar': 'التجميل',
    'Subnature En':
      'Gents And Ladies Beauty Salons In (Hotels - Authorized Places)',
    'Subnature Ar':
      'مراكز التجميل النسائية والرجالية في (الفنادق - والمواقع المصرح بها)',
  },
  {
    'Nature En': 'BEAUTY',
    'Nature Ar': 'التجميل',
    'Subnature En': 'Gents Beauty Salons',
    'Subnature Ar': 'مراكز التجميل الرجالية',
  },
  {
    'Nature En': 'BEAUTY',
    'Nature Ar': 'التجميل',
    'Subnature En': 'Hairdressing Salons For Gents/ Kids',
    'Subnature Ar': 'صالونات الحلاقة للرجال / الاطفال',
  },
  {
    'Nature En': 'BEAUTY',
    'Nature Ar': 'التجميل',
    'Subnature En': 'Ladies Beauty Salons',
    'Subnature Ar': 'مراكز التجميل النسائية',
  },
  {
    'Nature En': 'BEAUTY',
    'Nature Ar': 'التجميل',
    'Subnature En': 'Mobile Hair Dressing Salon',
    'Subnature Ar': 'صالون حلاقة متنقل',
  },
  {
    'Nature En': 'BEAUTY',
    'Nature Ar': 'التجميل',
    'Subnature En': 'Pets Grooming Salon',
    'Subnature Ar': 'صالون الحلاقة للحيوانات',
  },
  {
    'Nature En': 'BROKERAGE SERVICES',
    'Nature Ar': 'خدمات الوساطة',
    'Subnature En': 'Brokerage Services',
    'Subnature Ar': 'خدمات  الوساطة',
  },
  {
    'Nature En': 'BUILDING CLEANING AND OTHER CLEANING SERVICES',
    'Nature Ar': 'خدمات تنظيف المباني والتنظيفات الاخرى',
    'Subnature En': 'Building Cleaning And Other Cleaning Services',
    'Subnature Ar': 'خدمات تنظيف المباني والتنظيفات الاخرى',
  },
  {
    'Nature En': 'CARGO SERVICES',
    'Nature Ar': 'خدمات الشحن',
    'Subnature En': 'Cargo Services',
    'Subnature Ar': 'خدمات الشحن',
  },
  {
    'Nature En': 'CEREMONY AND PARTY AND HALLS',
    'Nature Ar': 'صالات الافراح والمناسبات',
    'Subnature En': 'Party And Ceremony Halls',
    'Subnature Ar': 'صالات الافراح والمناسبات',
  },
  {
    'Nature En': 'CINEMAS AND THEATERS',
    'Nature Ar': 'صالات العرض السينمائية والمسارح',
    'Subnature En': 'Cinemas And Theaters',
    'Subnature Ar': 'صالات العرض السينمائية والمسارح',
  },
  {
    'Nature En': 'CREATIVE ACTIVITIES',
    'Nature Ar': 'أنشطة مبدعة',
    'Subnature En': 'Creative Activities',
    'Subnature Ar': 'أنشطة مبدعة',
  },
  {
    'Nature En': 'DECORATION WORKS',
    'Nature Ar': 'أعمال تنفيذ الديكور',
    'Subnature En': 'Decoration Works',
    'Subnature Ar': 'أعمال تنفيذ الديكور',
  },
  {
    'Nature En': 'EDUCATION',
    'Nature Ar': 'التعليم',
    'Subnature En':
      'Education (Kindergarten, Primary, Intermediate And Secondary)',
    'Subnature Ar': 'التعليم (- رياض الاطفال - ابتدائي  - اعدادي - ثانوني)',
  },
  {
    'Nature En': 'EDUCATION',
    'Nature Ar': 'التعليم',
    'Subnature En': 'Faculties',
    'Subnature Ar': 'الكليات',
  },
  {
    'Nature En': 'EDUCATION',
    'Nature Ar': 'التعليم',
    'Subnature En': 'Nurseries',
    'Subnature Ar': 'الحضانات',
  },
  {
    'Nature En': 'EDUCATION',
    'Nature Ar': 'التعليم',
    'Subnature En':
      'Specialized Technical And Occupational Training Institutes',
    'Subnature Ar': 'المعاهد الفنية والمهنية المتخصصة',
  },
  {
    'Nature En': 'EDUCATION',
    'Nature Ar': 'التعليم',
    'Subnature En': 'Universities',
    'Subnature Ar': 'الجامعات',
  },
  {
    'Nature En': 'EDUCATIONAL TRAVEL SERVICES',
    'Nature Ar': 'خدمات تنظيم الرحلات التربوية',
    'Subnature En': 'Event And Exhibition Organizing',
    'Subnature Ar': 'خدمات تنظيم الرحلات التربوية',
  },
  {
    'Nature En': 'EXTRACTION ACTIVITIES (EXPLORATION)',
    'Nature Ar': 'الأنشطة الاستخراجية (البحث والتنقيب)',
    'Subnature En': 'Exploration And Excavation',
    'Subnature Ar': 'البحث والتنقيب',
  },
  {
    'Nature En': 'FISHING',
    'Nature Ar': 'الصيد',
    'Subnature En': 'Fishing And Related Services',
    'Subnature Ar': 'الصيد والخدمات المتعلقة به',
  },
  {
    'Nature En': 'FLOORING AND FURNITURE INSTALLATION',
    'Nature Ar': 'تركيب الأثاث والارضيات',
    'Subnature En': 'Flooring And Furniture Installation',
    'Subnature Ar': 'تركيب الأثاث والارضيات',
  },
  {
    'Nature En': 'FORUMS AND BUSINESSMEN COUNCILS',
    'Nature Ar': 'المنتديات ومجالس رجال الاعمال',
    'Subnature En':
      'Businessmen Councils And Forums (Embassies, Hotels And Governmental Entities)',
    'Subnature Ar':
      'المنتديات ومجالس رجال الاعمال ( السفارات والجهات الحكومية والفنادق)',
  },
  {
    'Nature En': 'FUNERALS AND RELATED SERVICES',
    'Nature Ar': 'الجنازات ومايتصل بها',
    'Subnature En': 'Funeral And Related Services',
    'Subnature Ar': 'الجنازات ومايتصل بها',
  },
  {
    'Nature En': 'GOVERNMENT LIAISON OFFICES AND INTERNATIONAL ORGANIZATIONS',
    'Nature Ar': 'مكاتب الارتباط الحكومي والمنظمات الدولية',
    'Subnature En': 'Commercial Governmental Liaison Office',
    'Subnature Ar': 'مكتب ارتباط تجاري حكومي',
  },
  {
    'Nature En': 'GOVERNMENT LIAISON OFFICES AND INTERNATIONAL ORGANIZATIONS',
    'Nature Ar': 'مكاتب الارتباط الحكومي والمنظمات الدولية',
    'Subnature En': 'Private Commercial Liaison Office',
    'Subnature Ar': 'مكتب ارتباط  تجاري خاص',
  },
  {
    'Nature En': 'HAJJ AND UMRAH SERVICES',
    'Nature Ar': 'خدمات تنظيم رحلات الحج والعمرة',
    'Subnature En': 'Landscaping Services',
    'Subnature Ar': 'خدمات تنظيم رحلات الحج والعمرة',
  },
  {
    'Nature En': 'HANDICRAFTS',
    'Nature Ar': 'الأعمال الحرفية الفنية',
    'Subnature En': 'Handicrafts',
    'Subnature Ar': 'المشغولات اليدوية',
  },
  {
    'Nature En': 'INDUSTRY',
    'Nature Ar': 'الصناعة',
    'Subnature En': 'Industry',
    'Subnature Ar': 'الصناعة',
  },
  {
    'Nature En': 'INSURANCE SERVICES',
    'Nature Ar': 'خدمات التأمين',
    'Subnature En': 'All Types Of Insurance',
    'Subnature Ar': 'التأمين بأنواعه',
  },
  {
    'Nature En': 'INSURANCE SERVICES',
    'Nature Ar': 'خدمات التأمين',
    'Subnature En': 'Insurance-Related Services',
    'Subnature Ar': 'الخدمات المتعلقه بالتأمين',
  },
  {
    'Nature En': 'KEY DUPLICATION SERVICES',
    'Nature Ar': 'نسخ المفاتيح',
    'Subnature En': 'Key Duplication Services',
    'Subnature Ar': 'خدمات نسخ المفاتيح',
  },
  {
    'Nature En': 'LABOR SUPPLY OFFICES',
    'Nature Ar': 'مكاتب تزويد العمالة',
    'Subnature En': 'Labor Supply Agent',
    'Subnature Ar': 'مكاتب تزويد العماله',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Agricultural Laboratory',
    'Subnature Ar': 'مختبر زراعي',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Building Material Laboratory',
    'Subnature Ar': 'مختبر مواد بناء',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Foodstuff Laboratory',
    'Subnature Ar': 'مختبر مواد غذائية',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Forged Document Inspection Laboratory',
    'Subnature Ar': 'مختبر كشف مستندات التزوير',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Laboratories',
    'Subnature Ar': 'المختبرات',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Laboratory For The Inspection Of Fire Causes',
    'Subnature Ar': 'مختبر مسببات الحريق',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Mechanical, Physics And Chemical Laboratory',
    'Subnature Ar': 'مختبر كيميائي فيزيائي ميكانيكي',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Medical Laboratory',
    'Subnature Ar': 'مختبر طبي',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Soil Testing Laboratory',
    'Subnature Ar': 'مختبر فحص التربة',
  },
  {
    'Nature En': 'LABORATORIES',
    'Nature Ar': 'المختبرات',
    'Subnature En': 'Veterinary Laboratory',
    'Subnature Ar': 'مختبر بيطري',
  },
  {
    'Nature En': 'LANDSCAPING SERVICES',
    'Nature Ar': 'خدمات التجميل والتنسيق للمواقع',
    'Subnature En': 'Educational Trip Organization Services',
    'Subnature Ar': 'خدمات التجميل والتنسيق للمواقع',
  },
  {
    'Nature En': 'LEATHER PRODUCTS REPAIRING AND CLEANING',
    'Nature Ar': 'اصلاح وتنظيف المنتجات الجلدية',
    'Subnature En': 'Leather Product Repairing And Cleaning',
    'Subnature Ar': 'اصلاح وتنظيف المنتجات الجلدية',
  },
  {
    'Nature En': 'LIBRARIES',
    'Nature Ar': 'مكتبات خاصة للقراءة',
    'Subnature En': 'Rentals Of Garments And Their Accessories',
    'Subnature Ar': 'مكتبات خاصة للقراءة وتأجير الكتب',
  },
  {
    'Nature En': 'MAINTENANCE, INSTALLATION AND CONTRACTING WORKS',
    'Nature Ar': 'أعمال المقاولات والصيانه والتركيبات',
    'Subnature En': 'Car Parking Installation Works',
    'Subnature Ar': 'أعمال تركيب مواقف السيارات',
  },
  {
    'Nature En': 'MAINTENANCE, INSTALLATION AND CONTRACTING WORKS',
    'Nature Ar': 'أعمال المقاولات والصيانه والتركيبات',
    'Subnature En': 'Contracting, Maintenance And Installation Works',
    'Subnature Ar': 'أعمال المقاولات والصيانه والتركيبات',
  },
  {
    'Nature En': 'MAINTENANCE, INSTALLATION AND CONTRACTING WORKS',
    'Nature Ar': 'أعمال المقاولات والصيانه والتركيبات',
    'Subnature En': 'Contracting-Related Works',
    'Subnature Ar': 'أعمال تركيب المعدات',
  },
  {
    'Nature En': 'MAINTENANCE, INSTALLATION AND CONTRACTING WORKS',
    'Nature Ar': 'أعمال المقاولات والصيانه والتركيبات',
    'Subnature En': 'Installation Works',
    'Subnature Ar': 'اعمال تركيب الكهربائيات للمناسبات',
  },
  {
    'Nature En': 'MAINTENANCE, INSTALLATION AND CONTRACTING WORKS',
    'Nature Ar': 'أعمال المقاولات والصيانه والتركيبات',
    'Subnature En': 'Scaffolding Rental And Installation Works',
    'Subnature Ar': 'أعمال تركيب وتأجير السقالات',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Airport Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل المطارات',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Car Parking Management And Operation',
    'Subnature Ar': 'ادارة وتشغيل مواقف السيارات',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Celebration Hall Management',
    'Subnature Ar': 'إدارة صالات الافراح',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Computer Network Management And Operation',
    'Subnature Ar': 'إدارة  وتشغيل شبكات الحاسب الالي',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Contracting, Maintenance And Installation Works',
    'Subnature Ar': 'أعمال المقاولات والصيانه والتركيبات',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Dancing Hall Operation',
    'Subnature Ar': 'تشغيل قاعات الرقص',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Dry Dock Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل الاحواض الجافة',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Educational Facility Management',
    'Subnature Ar': 'إدارة المنشآت التعليمية',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Estate Risk Management',
    'Subnature Ar': 'إدارة مخاطر التركات',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Factory Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل المصانع',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Farm Management And Operation',
    'Subnature Ar': 'ادارة وتشغيل المزارع',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Insurance Claim And Extending Management',
    'Subnature Ar': 'إدارة تمديد ومطالبات التأمين',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Labor Camp Management',
    'Subnature Ar': 'إدارة مساكن العاملين',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Management And Operating Of Petrol Stations',
    'Subnature Ar': 'إدارة وتشغيل محطات الوقود',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En':
      'Management And Operation Of Sanctuaries For Sports Purposes',
    'Subnature Ar': 'إدارة وتشغيل المحميات للاغراض الرياضية',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En':
      'Management And Operation Of Ships And Port Shipping Terminals',
    'Subnature Ar': 'إدارة وتشغيل السفن ومحطات الشحن للموانىء',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Management Office',
    'Subnature Ar': 'مكتب ادارة',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Marketing Operations Management',
    'Subnature Ar': 'إدارة العمليات التسويقية',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Medical Facility Management',
    'Subnature Ar': 'إدارة المنشآت الطبية',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Museum Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل المتاحف',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Platform And Hot Air Balloon Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل المناطيد والمنصات',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Power Plant Operation',
    'Subnature Ar': 'تشغيل محطات الكهرباء',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Private Company Management',
    'Subnature Ar': 'إدارة الشركات الخاصة',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Railway Management',
    'Subnature Ar': 'إدارة السكك الحديدية',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Receiving Station Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل محطات الاستقبال',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Restaurant Management',
    'Subnature Ar': 'إدارة المطاعم',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Restaurants And Cafeterias (Franchises)',
    'Subnature Ar': 'المطاعم والكافتيريات حق الامتياز (الفرينشايز)',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Road Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل الطرق',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Shore Management And Operation',
    'Subnature Ar': 'إدارة وتشغيل الشواطىء',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Slaughterhouse Management',
    'Subnature Ar': 'إدارة المسالخ',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Specialized Management',
    'Subnature Ar': 'إدارة المشاريع',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Sports Clubs And Events Management',
    'Subnature Ar': 'إدارة الاندية والاحداث الرياضية',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Theater And Cinema Management',
    'Subnature Ar': 'إدارة المسارح ودور العرض',
  },
  {
    'Nature En': 'MANAGEMENT AND OPERATION OFFICES',
    'Nature Ar': 'مكاتب الإدارة والتشغيل',
    'Subnature En': 'Warehouse Management And Operation',
    'Subnature Ar': 'ادارة وتشغيل المخازن',
  },
  {
    'Nature En': 'MARKETING SERVICES',
    'Nature Ar': 'الخدمات التسويقية',
    'Subnature En': 'Marketing Services',
    'Subnature Ar': 'الخدمات التسويقية',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En':
      '(Newspapers _ Magazines _ Books _ Publications) Distribution',
    'Subnature Ar': 'إصدار الصحف',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Advertising',
    'Subnature Ar': 'الدعاية والاعلان',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Advertising Services',
    'Subnature Ar': 'خدمات الاعلامية',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Advertising Services Through Websites',
    'Subnature Ar': 'خدمات إعلانية عبر المواقع الالكترونية',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Cinema And Tv Production',
    'Subnature Ar': 'الانتاج والتوزيع التلفزيزني والسينمائي',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Event And Party Organization',
    'Subnature Ar': 'توزيع (الصحف - المجلات -الكتب -المطبوعات)',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Line And Drawing Services',
    'Subnature Ar': 'خدمات الخط والرسم',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Magazine Publishing',
    'Subnature Ar': 'إصدار المجلات',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'News Services Through Websites',
    'Subnature Ar': 'خدمات إخبارية عبر المواقع الالكترونية',
  },
  {
    'Nature En': 'MEDIA AND ADVERTISING SERVICES',
    'Nature Ar': 'الخدمات الاعلانية والاعلامية',
    'Subnature En': 'Television Channels',
    'Subnature Ar': 'قنوات ومحطات تلفزيونية',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Clinics',
    'Subnature Ar': 'العيادات',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Hospitals',
    'Subnature Ar': 'المستشفيات',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Medical Complex',
    'Subnature Ar': 'مجمع طبي',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Medical Services',
    'Subnature Ar': 'الخدمات الطبية',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Pharmacy',
    'Subnature Ar': 'صيدلية',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Specialized Medical Center',
    'Subnature Ar': 'مركز طبي متخصص',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Veterinary Clinic',
    'Subnature Ar': 'عيادة (بيطرية)',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Veterinary Hospitals',
    'Subnature Ar': 'المستشفيات (البيطرية)',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Veterinary Pharmacy',
    'Subnature Ar': 'صيدلية بيطرية',
  },
  {
    'Nature En': 'MEDICAL AND VETERINARY SERVICES',
    'Nature Ar': 'الخدمات الطبية والبيطرية',
    'Subnature En': 'Veterinary Services',
    'Subnature Ar': 'الخدمات البيطرية',
  },
  {
    'Nature En': 'MINING AND METAL PROCESSING',
    'Nature Ar': 'تعدين  ومعالجة المعادن',
    'Subnature En': 'Metallurgy',
    'Subnature Ar': 'معالجة المعادن',
  },
  {
    'Nature En': 'MONEY TRANSPORT AND BANK SECURITY SERVICES',
    'Nature Ar': 'خدمات أمن البنوك ونقل الاموال',
    'Subnature En': 'Money Transport And Bank Security Services',
    'Subnature Ar': 'خدمات أمن البنوك ونقل الاموال',
  },
  {
    'Nature En': 'MUSEUMS',
    'Nature Ar': 'المتاحف',
    'Subnature En': 'Museums',
    'Subnature Ar': 'المتاحف',
  },
  {
    'Nature En': 'MUSEUMS',
    'Nature Ar': 'المتاحف',
    'Subnature En': 'Personal Museums',
    'Subnature Ar': 'المتاحف الشخصية',
  },
  {
    'Nature En': 'NATURAL RESERVES',
    'Nature Ar': 'المحميات',
    'Subnature En': 'Wildlife Reserve',
    'Subnature Ar': 'محمية برية',
  },
  {
    'Nature En': 'OIL AND GAS EXTRACTION AND THE RELEVANT SERVICES',
    'Nature Ar': 'استخراج النفط والغاز والخدمات ذات العلاقة',
    'Subnature En': 'Oil And Gas Extraction And The Relevant Services',
    'Subnature Ar': 'استخراج النفط والغاز والخدمات ذات العلاقة',
  },
  {
    'Nature En': 'OIL AND GAS EXTRACTION AND THE RELEVANT SERVICES',
    'Nature Ar': 'استخراج النفط والغاز والخدمات ذات العلاقة',
    'Subnature En': 'Petrol Station',
    'Subnature Ar': 'محطة وقود',
  },
  {
    'Nature En': 'OIL AND GAS EXTRACTION AND THE RELEVANT SERVICES',
    'Nature Ar': 'استخراج النفط والغاز والخدمات ذات العلاقة',
    'Subnature En': 'Petroleum Product Promotion And Marketing',
    'Subnature Ar': 'التسويق والترويج للمنتجات البترولية',
  },
  {
    'Nature En': 'OIL AND GAS EXTRACTION AND THE RELEVANT SERVICES',
    'Nature Ar': 'استخراج النفط والغاز والخدمات ذات العلاقة',
    'Subnature En': 'Petroleum Product Transport And Distribution',
    'Subnature Ar': 'توزيع ونقل المنتجات البترولية',
  },
  {
    'Nature En':
      'ORGANIZATIONAL SERVICES (EVENTS - CONFERENCES - EXHIBITIONS - CEREMONIES)',
    'Nature Ar': 'خدمات تنظيم (الفعاليات - المؤتمرات - المعارض والمناسبات)',
    'Subnature En': 'Festival And Recreation Event Organization',
    'Subnature Ar': 'خدمات تنظيم الحفلات والمناسبات',
  },
  {
    'Nature En':
      'ORGANIZATIONAL SERVICES (EVENTS - CONFERENCES - EXHIBITIONS - CEREMONIES)',
    'Nature Ar': 'خدمات تنظيم (الفعاليات - المؤتمرات - المعارض والمناسبات)',
    'Subnature En': 'Hajj And Umrah Services',
    'Subnature Ar': 'تنفيذ المهرجانات والتعهدات الترفيهيه',
  },
  {
    'Nature En':
      'ORGANIZATIONAL SERVICES (EVENTS - CONFERENCES - EXHIBITIONS - CEREMONIES)',
    'Nature Ar': 'خدمات تنظيم (الفعاليات - المؤتمرات - المعارض والمناسبات)',
    'Subnature En': 'Private Libraries For Reading And Book Rental',
    'Subnature Ar': 'تنظيم الفعاليات والمعارض',
  },
  {
    'Nature En': 'OTHER OCCUPATIONS',
    'Nature Ar': 'الأعمال الحرفية الأخرى',
    'Subnature En': 'Leather Dyeing',
    'Subnature Ar': 'دباغة الجلود',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Accounting System Analysis And Organization',
    'Subnature Ar': 'تنظيم وتحليل نظم المحاسبه',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Airport Services',
    'Subnature Ar': 'الخدمات المتعلقة بالمطارات',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Business Incupators Services',
    'Subnature Ar': 'خدمات حاضنات الاعمال',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Businessmen Services',
    'Subnature Ar': 'خدمات رجال الاعمال',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Call Distribution Services',
    'Subnature Ar': 'خدمات توزيع المكالمات',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Company Evaluation And Merger',
    'Subnature Ar': 'تقييم واندماج الشركات',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Computer System And Program Design Services',
    'Subnature Ar': 'خدمات التصميم لنظم وبرامج الحاسب الالي',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Customer Service Centers',
    'Subnature Ar': 'مراكز خدمة العملاء',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Data Collection And Preparation Services',
    'Subnature Ar': 'خدمات تجهيز وجمع البيانات',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Debt Collection Services',
    'Subnature Ar': 'خدمات تحصيل الديون',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Diving And Lifesaving Services',
    'Subnature Ar': 'خدمات الغطس والانقاذ',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Environmental Services',
    'Subnature Ar': 'الخدمات البيئية',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Guest Reception Services',
    'Subnature Ar': 'خدمات استقبال الضيوف',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Immigration And Visa Processing Services',
    'Subnature Ar': 'خدمات استخراج التأشيرات والهجرة',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Insurance-Related Services',
    'Subnature Ar': 'الخدمات المتعلقه بالتأمين',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Jewelry Design',
    'Subnature Ar': 'تصميم المجوهرات',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Legal Correspondence Services',
    'Subnature Ar': 'خدمات المراسلات القانونية',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Marriage Office Services',
    'Subnature Ar': 'خدمات مكاتب الزواج',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Notary Public Services',
    'Subnature Ar': 'خدمات كاتب العدل',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Payment Settlement Service',
    'Subnature Ar': 'خدمات  سداد المدفوعات',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Refilling Services',
    'Subnature Ar': 'خدمات إعادة التعبئة',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Road Assistance And Accident Inspection Services',
    'Subnature Ar': 'خدمات معاينة الحوادث والدعم على الطرق',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Security Surveillance Services',
    'Subnature Ar': 'خدمات المراقبة الامنية',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Stored-Value And Discount Card Issuance Services',
    'Subnature Ar': 'خدمات اصدار بطاقات القيمة المخزنة والاسعار المخفضة',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Technical And Occupational Inspection Services',
    'Subnature Ar': 'خدمات الفحص الفني والمهني',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Ticket Sales Outlet',
    'Subnature Ar': 'منفذ بيع تذاكر',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Tour Operating Outlet',
    'Subnature Ar': 'منفذ تنظيم الرحلات السياحية',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Translation Services',
    'Subnature Ar': 'خدمات الترجمة',
  },
  {
    'Nature En': 'OTHER SERVICES',
    'Nature Ar': 'الخدمات الاخرى',
    'Subnature En': 'Valet Parking Services',
    'Subnature Ar': 'خدمات ايقاف السيارات',
  },
  {
    'Nature En': 'PARKS AND RECREATIONAL ACTIVITIES',
    'Nature Ar': 'الحدائق والخدمات الترفيهية',
    'Subnature En': 'Parks And Recreational Services',
    'Subnature Ar': 'الحدائق والخدمات الترفيهية',
  },
  {
    'Nature En': 'PARKS AND RECREATIONAL ACTIVITIES',
    'Nature Ar': 'الحدائق والخدمات الترفيهية',
    'Subnature En': 'Recreation Halls',
    'Subnature Ar': 'صالات ألعاب التسلية',
  },
  {
    'Nature En': 'PEOPLE OF DETERMINATION ACTIVITIES',
    'Nature Ar': 'أنشطة اصحاب الهمم',
    'Subnature En': 'People Of Determination Activities',
    'Subnature Ar': 'أنشطة اصحاب الهمم',
  },
  {
    'Nature En': 'PHOTOGRAPHY',
    'Nature Ar': 'التصوير',
    'Subnature En': 'Aerial And Construction Project Photography',
    'Subnature Ar': 'التصوير الجوي والانشائي للمشاريع',
  },
  {
    'Nature En': 'PHOTOGRAPHY',
    'Nature Ar': 'التصوير',
    'Subnature En': 'Personal Photography Studio',
    'Subnature Ar': 'استوديو تصوير شخصي',
  },
  {
    'Nature En': 'PHOTOGRAPHY',
    'Nature Ar': 'التصوير',
    'Subnature En': 'Photocopy Vending Machine',
    'Subnature Ar': 'التصوير بواسطة معدات البيع الآلي',
  },
  {
    'Nature En': 'PRINTING, PUBLISHING AND RELATED SERVICE',
    'Nature Ar': 'الطباعة والنشر  والخدمات المتعلقه بها',
    'Subnature En': 'Paperwork Follow-Up Services',
    'Subnature Ar': 'خدمات الطباعة والتصوير',
  },
  {
    'Nature En': 'PRINTING, PUBLISHING AND RELATED SERVICE',
    'Nature Ar': 'الطباعة والنشر  والخدمات المتعلقه بها',
    'Subnature En':
      'Printing And Distribution Of Newspaper, Magazine And Books',
    'Subnature Ar': 'طباعة (الصحف -المجلات - الكتب )ونشرها',
  },
  {
    'Nature En': 'PRINTING, PUBLISHING AND RELATED SERVICE',
    'Nature Ar': 'الطباعة والنشر  والخدمات المتعلقه بها',
    'Subnature En': 'Printing Works',
    'Subnature Ar': 'أعمال الطباعة',
  },
  {
    'Nature En': 'PRINTING, PUBLISHING AND RELATED SERVICE',
    'Nature Ar': 'الطباعة والنشر  والخدمات المتعلقه بها',
    'Subnature En': 'Publishing',
    'Subnature Ar': 'النشر',
  },
  {
    'Nature En': 'PROFESSIONAL ACTIVITIES',
    'Nature Ar': 'الانشطة المهنية',
    'Subnature En': 'Professional Consultancy',
    'Subnature Ar': 'الاستشارات  المهنية',
  },
  {
    'Nature En': 'PROJECT INVESTMENTS',
    'Nature Ar': 'الاستثمارات في المشاريع',
    'Subnature En': 'Investments',
    'Subnature Ar': 'الاستثمارات',
  },
  {
    'Nature En': 'PUBLIC AUCTION HALLS',
    'Nature Ar': 'صالات المزاد العلني',
    'Subnature En': 'Public Auction Halls',
    'Subnature Ar': 'صالات المزاد العلني',
  },
  {
    'Nature En': 'REAL ESTATE SERVICES',
    'Nature Ar': 'الخدمات العقارية',
    'Subnature En': 'Real Estate Services',
    'Subnature Ar': 'الخدمات العقارية',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Agricultural Equipment And Tools Rental',
    'Subnature Ar': 'تأجير أجهزة  الاتصالات',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Aircraft Rental',
    'Subnature Ar': 'تأجير الطائرات',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Baby Cart Rentals',
    'Subnature Ar': 'تأجير الملابس ولوازمها',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Bicycle Rentals And Games',
    'Subnature Ar': 'تأجير الدراجات والألعاب',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Car Parking Lease Services',
    'Subnature Ar': 'خدمات تأجير مواقف السيارات',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Car Rental',
    'Subnature Ar': 'تأجير السيارات',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Electric Bike Rentals',
    'Subnature Ar': 'تأجير عربات الاطفال',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Equipment And Vehicles Rental',
    'Subnature Ar': 'تأجير المعدات والأليات',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Furniture Rental',
    'Subnature Ar': 'تأجير الالات والمعدات المكتبية',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Medical Equipment Rental',
    'Subnature Ar': 'تأجير الادوات والمعدات الزراعية',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Mobile Phones Rental',
    'Subnature Ar': 'تأجير الاثاث',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Rental Of Cabins And Furnished Houses',
    'Subnature Ar': 'تأجير البيوت الجاهزه و الكبائن',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Rental Of Shops And Marine Arches',
    'Subnature Ar': 'تأجير السفن والقناطر البحرية',
  },
  {
    'Nature En': 'RENT SERVICES',
    'Nature Ar': 'خدمات التأجير',
    'Subnature En': 'Truck And Bus Rental',
    'Subnature Ar': 'تأجير الحافلات والشاحنات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Agricultural Equipment And Repair',
    'Subnature Ar': 'إصلاح وصيانة المعدات الزراعية',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Aircraft Maintenance And Repair',
    'Subnature Ar': 'إصلاح وصيانة  الطائرات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Antiques And Precious Belongings Repairing',
    'Subnature Ar': 'إصلاح لمقتنيات الاثرية والثمينه',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Bike Repairing',
    'Subnature Ar': 'إصلاح الدراجات الهوائية',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Computer And Printer Repair',
    'Subnature Ar': 'إصلاح الحاسب الالي والطابعات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Generator And Pump Maintenance  And Repairs',
    'Subnature Ar': 'إصلاح وصيانة المولدات والمضحات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Jewelry Repair',
    'Subnature Ar': 'اصلاح المجوهرات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Repair Of Home Electric Equipment And Devices And Others',
    'Subnature Ar': 'إصلاح الاجهزه والأدوات الكهربائية المنزلية وغيرها',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Ship And Marine Equipment Repair',
    'Subnature Ar': 'إصلاح وصيانة السفن والمعدات البحرية',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Sports Equipment Maintenance And Repair',
    'Subnature Ar': 'إصلاح وصيانة  المعدات الرياضية',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Tool And Equipment Maintenance And Repairs',
    'Subnature Ar': 'إصلاح وصيانة المعدات والاليات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Tool Repairs',
    'Subnature Ar': 'أدوات إصلاح',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Train Maintenance And Repair',
    'Subnature Ar': 'إصلاح وصيانة  القطارات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Upholstery And Furniture Repairs',
    'Subnature Ar': 'إصلاح الأثاث والتنجيد',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Watch Repair',
    'Subnature Ar': 'إصلاح الساعات',
  },
  {
    'Nature En': 'REPAIRING AND MAINTENANCE',
    'Nature Ar': 'الاصلاح والصيانة',
    'Subnature En': 'Weapon And Rifle Repair',
    'Subnature Ar': 'إصلاح البنادق والاسلحة',
  },
  {
    'Nature En': 'REPRESENTATION OFFICES',
    'Nature Ar': 'مكاتب التمثيل',
    'Subnature En': 'Representation Of Companies',
    'Subnature Ar': 'تمثيل شركات',
  },
  {
    'Nature En': 'REPRESENTATION OFFICES',
    'Nature Ar': 'مكاتب التمثيل',
    'Subnature En': 'Representation Of Foreign Company Branches',
    'Subnature Ar': 'مكاتب تمثيل الشركات لأفرع الشركات الاجنبية',
  },
  {
    'Nature En':
      'RESTAURANTS, CAFETERIAS, CATERING AND MEAL PREPARATION SERVICES.',
    'Nature Ar': 'المطاعم  والكافتيريات وخدمات التموين اعداد الوجبات',
    'Subnature En': 'Restaurants And Cafeterias (Franchises)',
    'Subnature Ar': 'المطاعم والكافتيريات حق الامتياز (الفرينشايز)',
  },
  {
    'Nature En':
      'RESTAURANTS, CAFETERIAS, CATERING AND MEAL PREPARATION SERVICES.',
    'Nature Ar': 'المطاعم  والكافتيريات وخدمات التموين اعداد الوجبات',
    'Subnature En':
      'Restaurants, Cafeterias, Catering And Meal Preparation Services',
    'Subnature Ar': 'المطاعم  والكافتيريات وخدمات التموين اعداد الوجبات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Animal Feeds Kiosk',
    'Subnature Ar': 'أكشاك بيع الاعلاف',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Audiovisual Compact Disc Retail  And Rental',
    'Subnature Ar': 'بيع وتأجير  الاقراص السمعية والبصرية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Baqala (Grocery)',
    'Subnature Ar': 'البقالات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Books And Recordings Kiosk',
    'Subnature Ar': 'أكشاك الكتب والتسجيلات(السمعية - المرئية)',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Butchery',
    'Subnature Ar': 'الملحمة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Charity Market',
    'Subnature Ar': 'أسواق خيرية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Clothes And Garments Kiosk',
    'Subnature Ar': 'أكشاك الملابس والمنسوجات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Consumables Market',
    'Subnature Ar': 'المتاجر الاستهلاكية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Cooperative Society',
    'Subnature Ar': 'الجمعيات التعاونية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'E-Commerce',
    'Subnature Ar': 'المتاجرة الالكترونية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Fish Retail Kiosk',
    'Subnature Ar': 'أكشاك بيع الأسماك',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Foodstuff Kiosk',
    'Subnature Ar': 'أكشاك المواد الغذائية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Gas Filling And Distribution To Consumers',
    'Subnature Ar': 'توزيع وتعبئة الغاز للمستهلكين',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Industrial Products Showroom',
    'Subnature Ar': 'معرض لبيع المنتجات الصناعية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Mills',
    'Subnature Ar': 'المطحنة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Outlets In Petrol Stations And Tourism Sites',
    'Subnature Ar': 'المتاجر الاستهلاكية لمحطات الوقود والمواقع السياحية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Pharmacy',
    'Subnature Ar': 'صيدلية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail And Lease Of Music Equipment And Instrument',
    'Subnature Ar': 'بيع وتأجير الآلات والادوات الموسيقية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En':
      'Retail Of (Readymade Garments, Perfume, Footwear, Accessories, Bags, Cosmetics)',
    'Subnature Ar':
      'بيع (الملابس الجاهزة - عطور - الاحذية - والاكسسورات - الحقائب - مواد التجميل )',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Agricultural Equipment And Tools',
    'Subnature Ar': 'البيع بالتجزئة للمعدات وأدوات الزراعة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Aircraft',
    'Subnature Ar': 'بيع الطائرات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Aircraft Spare Parts And Accessories',
    'Subnature Ar': 'بيع قطع غيار الطائرات ولوازمها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Alarm, Control And Fire Prevention Equipment',
    'Subnature Ar': 'بيع  معدات  الانذار والمراقية ومكافحة الحريق',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Alternative Energy Equipment And  Installation',
    'Subnature Ar': 'بيع معدات الطاقة البديلة وتركيبها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of And Installation Of Receivers',
    'Subnature Ar': 'بيع اجهزة الاستقبال وتركيبها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Antiques And Used Furniture',
    'Subnature Ar': 'بيع التحف والاثاث المستعمل',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Book And Stationary (Bookshops)',
    'Subnature Ar': 'بيع القرطاسية  والكتب (المكتبات)',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Camel And Horse Equipment And Accessories',
    'Subnature Ar': 'بيع ادوات ولوازم الخيل والهجن',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Chemicals',
    'Subnature Ar': 'البيع بالتجزئة للكيماويات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Cigarette, Tobacco And Smokers Accessories',
    'Subnature Ar': 'بيع السجائر والتبغ ولوازم التدخين',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Computer And Computer Accessories',
    'Subnature Ar': 'بيع الحاسب الالي ومستلزماته',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Construction Materials And Equipment',
    'Subnature Ar': 'بيع مواد وادوات البناء ولوازمها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Cosmetics And Beauty Equipment',
    'Subnature Ar': 'بيع مواد التجميل ومعدات  وأدوات التجميل',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Dairy And Pickles',
    'Subnature Ar': 'بيع الالبان والمخللات ومنتجاتها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Dates',
    'Subnature Ar': 'بيع التمور ومنتجاتها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Decoration Materials',
    'Subnature Ar': 'بيع مواد الديكور',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Dietary Supplements',
    'Subnature Ar': 'بيع المكملات الغذائية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En':
      'Retail Of Electric And Electronic Equipment And Accessories',
    'Subnature Ar': 'بيع المعدات الكهربائية والالكترونية ولوازمها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Electronics And Devices',
    'Subnature Ar': 'بيع الالكترونيات والاجهزة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Equipment And Machine',
    'Subnature Ar': 'بيع المعدات والاليات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Feeds, Coal, And Woods',
    'Subnature Ar': 'البيع بالتجزئة (الأعلاف - الفحم - الحطب)',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Fish',
    'Subnature Ar': 'بيع الاسماك',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Fishing Equipment And Tools',
    'Subnature Ar': 'البيع بالتجزئة للمعدات وأدوات الصيد',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Flower And Chocolate',
    'Subnature Ar': 'بيع الزهور والشوكولا',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Foodstuff  (Frozen _ Preserved)',
    'Subnature Ar': 'بيع المواد الغذائية (المجمدة - المحفوظة )',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Fruit And Vegetable',
    'Subnature Ar': 'بيع الخضروات والفواكه',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Furniture And Lighting Accessories',
    'Subnature Ar': 'بيع الاثاث ومستلزمات الانارة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Gift',
    'Subnature Ar': 'بيع الهدايا',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Glasses And Lenses',
    'Subnature Ar': 'بيع النظارات الطبية والعدسات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Gold, Jewelry And Luxury Watches',
    'Subnature Ar': 'بيع الذهب والمجوهرات والساعات الثمينه',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Home Tools And Utensils',
    'Subnature Ar': 'بيع الادوات والاواني المنزلية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Honey',
    'Subnature Ar': 'بيع العسل ومنتجاته',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Ice',
    'Subnature Ar': 'بيع الثلج',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Incense And Perfume',
    'Subnature Ar': 'بيع العطور والبخور',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Insecticides And Cleaning Material',
    'Subnature Ar': 'بيع المنظفات والمبيدات الحشرية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Live Animal',
    'Subnature Ar': 'بيع الحيوانات الحية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En':
      'Retail Of Medical And Pharmaceutical Equipment And Accessories',
    'Subnature Ar': 'بيع  المعدات والمستلزمات  الطبية والصيدلانية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Metal And Ironworks',
    'Subnature Ar': 'بيع المنتجات المعدنية والحديدية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Mobile Phones And Landline Phones',
    'Subnature Ar': 'بيع الهواتف المتحركة والثابته',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Monitoring, Measurement And Control Devices',
    'Subnature Ar': 'بيع اجهزة الرصد والقياس والتحكم',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Organic Foodstuff',
    'Subnature Ar': 'بيع المواد الغذائية العضوية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Party Supplies And Accessories',
    'Subnature Ar': 'بيع مستلزمات الحفلات ولوازمها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Pet Fish And Birds And Their Accessories',
    'Subnature Ar': 'بيع اسماك وطيور الزينه ومستلزماتها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Photography Equipment And Accessories',
    'Subnature Ar': 'بيع أدوات ولوازم التصوير',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Poultry',
    'Subnature Ar': 'بيع الدواجن',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Road Signs And Installation',
    'Subnature Ar': 'بيع اللوحات المرورية وتركيبها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Ship And Marine Vehicles',
    'Subnature Ar': 'بيع السفن والآليات البحرية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Soda, Mineral Water And Refreshment',
    'Subnature Ar': 'بيع المياه المعدنية والغازية والمرطبات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Spices And Herbs',
    'Subnature Ar': 'بيع التوابل ومواد العطارة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Sports Equipment And Accessories',
    'Subnature Ar': 'البيع بالتجزئة للادوات والمعدات الرياضية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Tailoring Tools And Accessories',
    'Subnature Ar': 'بيع لوازم وأدوات الخياطة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Tea',
    'Subnature Ar': 'بيع الشاي',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Tents And Trip Accessories',
    'Subnature Ar': 'بيع وتاجير الخيم ولوازم الرحلات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Textile And Fabrics',
    'Subnature Ar': 'بيع الاقمشة والمنسوجات',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Tools',
    'Subnature Ar': 'بيع المعدات بالتجزئة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Toy And Gift',
    'Subnature Ar': 'بيع الالعاب والهدايا',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Train Spare Parts And Accessories',
    'Subnature Ar': 'بيع قطع غيارالقطارات ولوازمها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Used Book',
    'Subnature Ar': 'بيع الكتب المستعملة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Used Equipment And Devices',
    'Subnature Ar': 'بيع الادوات والاجهزة المستعملة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Used Garment',
    'Subnature Ar': 'بيع الملابس المستعملة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Used Vehicle And Equipment',
    'Subnature Ar': 'بيع  المعدات والاليات المستعملة',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Veterinary Equipment And Tools',
    'Subnature Ar': 'البيع بالتجزئة للاجهزة والمواد البيطرية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Retail Of Weapons And Military Equipment And Supplies',
    'Subnature Ar': 'البيع بالتجزئة للأسلحة والمعدات العسكرية ولوازمها',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Roaster',
    'Subnature Ar': 'المحمصه',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Selling Through Vending Machines',
    'Subnature Ar': 'البيع بواسطة معدات البيع الالي',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Sports Entertainment Kiosk',
    'Subnature Ar': 'أكشاك التسلية الرياضية',
  },
  {
    'Nature En': 'RETAIL',
    'Nature Ar': 'البيع بالتجزئة',
    'Subnature En': 'Tobacco Kiosk',
    'Subnature Ar': 'أكشاك بيع  التبغ',
  },
  {
    'Nature En': 'SECURITY AND GUARDING SERVICES',
    'Nature Ar': 'خدمات الامن والحراسة',
    'Subnature En': 'Security And Guarding Services',
    'Subnature Ar': 'خدمات الامن والحراسة',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Administrative Consulting',
    'Subnature Ar': 'الاستشارات الادارية',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Arts Consulting',
    'Subnature Ar': 'استشارات الفنون',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Computer And It Consulting',
    'Subnature Ar': 'استشارات الحاسب الالي وتقنية المعلومات',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Computer System And Program Design Services',
    'Subnature Ar': 'خدمات التصميم لنظم وبرامج الحاسب الالي',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Engineering Consulting',
    'Subnature Ar': 'الاستشارات الهندسية',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Insurance Consulting',
    'Subnature Ar': 'استشارات التأمين',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Legal Consulting For Foreign Company Branches',
    'Subnature Ar': 'استشارات قانونية لأفرع الشركات الاجنبية',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Legal Consulting For Local Companies',
    'Subnature Ar': 'استشارات قانونية للشركات المحلية',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Military And Security Consulting',
    'Subnature Ar': 'الاستشارات الامنية والعسكرية',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Mortgage And Financial Analysis Consulting',
    'Subnature Ar': 'استشارات التحليل المالي والرهن',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Research Centers',
    'Subnature Ar': 'مراكز الابحاث',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Third Party Auditing Services',
    'Subnature Ar': 'خدمات مكاتب تدقيق الطرف الثالث',
  },
  {
    'Nature En': 'SERVICES (CONSULTANCY - DESIGN AND RESEARCH CENTER)',
    'Nature Ar': 'خدمات (الاستشارات  - التصميم ومراكز الابحاث)',
    'Subnature En': 'Transport Consulting (Air _ Land _ Marine)',
    'Subnature Ar': 'استشارات النقل (جوي - بري - بحري)',
  },
  {
    'Nature En': 'SERVICES ACTIVITIES',
    'Nature Ar': 'انشطة الخدمات',
    'Subnature En': 'Ground And Air Transportation',
    'Subnature Ar': 'خدمات النقل البري والنقل الجوي',
  },
  {
    'Nature En': 'SERVICES ACTIVITIES',
    'Nature Ar': 'انشطة الخدمات',
    'Subnature En': 'Management And Operations',
    'Subnature Ar': 'الإدارة و التشغيل',
  },
  {
    'Nature En': 'SMALL PRODUCER ACTIVITIES',
    'Nature Ar': 'أنشطة صغار المنتجين',
    'Subnature En': 'Small Producer Activities',
    'Subnature Ar': 'أنشطة صغار المنتجين',
  },
  {
    'Nature En': 'SOCIAL AND CULTURAL SERVICES',
    'Nature Ar': 'الخدمات الاجتماعية والثقافية',
    'Subnature En': 'Care Home For The Elderly And People With Special Needs',
    'Subnature Ar': 'دور الرعاية لكبار السن وذوي الاحتياجات الخاصة',
  },
  {
    'Nature En': 'SOCIAL AND CULTURAL SERVICES',
    'Nature Ar': 'الخدمات الاجتماعية والثقافية',
    'Subnature En': 'Charity Societies',
    'Subnature Ar': 'جمعيات خيرية',
  },
  {
    'Nature En': 'SOCIAL AND CULTURAL SERVICES',
    'Nature Ar': 'الخدمات الاجتماعية والثقافية',
    'Subnature En': 'Rehabilitation Center For People With Special Needs',
    'Subnature Ar': 'مراكز إعادة التأهيل لذوي الاحتياجات الخاصة',
  },
  {
    'Nature En': 'SOCIAL AND CULTURAL SERVICES',
    'Nature Ar': 'الخدمات الاجتماعية والثقافية',
    'Subnature En': 'Social And Cultural Centers And Clubs',
    'Subnature Ar': 'الاندية والمراكز الاجتماعية والثقافية',
  },
  {
    'Nature En': 'SOCIAL AND CULTURAL SERVICES',
    'Nature Ar': 'الخدمات الاجتماعية والثقافية',
    'Subnature En': 'Social And Cultural Consulting',
    'Subnature Ar': 'الاستشارات الاجتماعية والثقافية',
  },
  {
    'Nature En': 'SPORTS CLUBS AND RELEVANT SERVICES',
    'Nature Ar': 'الاندية الرياضية والخدمات المتعلقه بها',
    'Subnature En': 'Sports Clubs',
    'Subnature Ar': 'الاندية الرياضية',
  },
  {
    'Nature En': 'SPORTS CLUBS AND RELEVANT SERVICES',
    'Nature Ar': 'الاندية الرياضية والخدمات المتعلقه بها',
    'Subnature En': 'Sports Services',
    'Subnature Ar': 'الخدمات الرياضية',
  },
  {
    'Nature En': 'STORAGE',
    'Nature Ar': 'التخزين',
    'Subnature En': 'Storage',
    'Subnature Ar': 'التخزين',
  },
  {
    'Nature En': 'TAILORING',
    'Nature Ar': 'تفصيل وخياطة المنسوجات',
    'Subnature En': 'Flag Tailoring',
    'Subnature Ar': 'خياطة الاعلام',
  },
  {
    'Nature En': 'TAILORING',
    'Nature Ar': 'تفصيل وخياطة المنسوجات',
    'Subnature En': 'Tailoring',
    'Subnature Ar': 'تفصيل وخياطة الملابس',
  },
  {
    'Nature En': 'TAILORING',
    'Nature Ar': 'تفصيل وخياطة المنسوجات',
    'Subnature En': 'Tent And Protective Covers  Tailoring',
    'Subnature Ar': 'خياطة الخيم والطرابيل',
  },
  {
    'Nature En': 'TAILORING',
    'Nature Ar': 'تفصيل وخياطة المنسوجات',
    'Subnature En': 'Uniform And Military Outfit Tailoring',
    'Subnature Ar': 'تفصيل وخياطة الملابس العسكرية والمهنية',
  },
  {
    'Nature En': 'TAJER ABUDHABI ACTIVITIES',
    'Nature Ar': 'أنشطة تاجر أبوظبي',
    'Subnature En': 'Tajir Abu Dhabi ( Food Mobile Car) Activities',
    'Subnature Ar': 'أنشطة تاجر أبوظبي الغذائية (سيارة متنقلة)',
  },
  {
    'Nature En': 'TAJER ABUDHABI ACTIVITIES',
    'Nature Ar': 'أنشطة تاجر أبوظبي',
    'Subnature En': 'Tajir Abu Dhabi (Mobile Car) Activities',
    'Subnature Ar': 'أنشطة تاجر أبوظبي (سيارة متنقلة)',
  },
  {
    'Nature En': 'TAXATION SERVICES',
    'Nature Ar': 'الخدمات الضريبية',
    'Subnature En': 'Taxation Services',
    'Subnature Ar': 'الخدمات الضريبية',
  },
  {
    'Nature En': 'TECHNICAL AND OCCUPATIONAL INSPECTION SERVICES',
    'Nature Ar': 'خدمات الفحص الفني والمهني',
    'Subnature En': 'Technical And Occupational Inspection Services',
    'Subnature Ar': 'خدمات الفحص الفني والمهني',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Advanced Materials And Manufacturing',
    'Subnature Ar': 'المواد المتقدمة والتصنيع',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Autonomous And Near-Autonomous Vehicles',
    'Subnature Ar': 'المركبات ذاتية وشبه ذاتية التحكم',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Biomedical Science And Human Augmentation',
    'Subnature Ar': 'العلوم الطبية الحيوية والتعزيز البشري',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Cloud Services And Cloud Computing',
    'Subnature Ar': 'الخدمات السحابية والحوسبة السحابية',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Communications And Sensing',
    'Subnature Ar': 'الاتصالات والاستشعار',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Energy Technology',
    'Subnature Ar': 'تكنولوجيا الطاقة',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Mixed Reality And Digital Mimicry',
    'Subnature Ar': 'الواقع المختلط والمحاكاة الرقمية',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Quantum Computing',
    'Subnature Ar': 'الحوسبة الكمية',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Robotics, Ai And Autonomous Systems',
    'Subnature Ar': 'الربوتات, الذكاء الاصطناعي والأنظمة الذاتية',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Space Technology',
    'Subnature Ar': 'تكنولوجيا الفضاء',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Synthetic Biology',
    'Subnature Ar': 'البيولوجيا التركيبية',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Technology For Climate Change Adaptation',
    'Subnature Ar': 'تكنولوجيا التكيف مع تغير المناخ',
  },
  {
    'Nature En': 'TECHNOLOGY',
    'Nature Ar': 'تكنولوجيا',
    'Subnature En': 'Technology For Food And Water Security',
    'Subnature Ar': 'تكنولوجيا الأمن الغذائي والمائي',
  },
  {
    'Nature En': 'TECHNOLOGY ACTIVITIES',
    'Nature Ar': 'انشطة التكنولوجيا',
    'Subnature En': 'Food And Water Security Technology',
    'Subnature Ar': 'تكنولوجيا الأمن الغذائي والمائي',
  },
  {
    'Nature En': 'TELECOMMUNICATIONS',
    'Nature Ar': 'الاتصالات',
    'Subnature En': 'Telecommunications Services',
    'Subnature Ar': 'خدمات الاتصالات',
  },
  {
    'Nature En': 'TEXTILE AND CARPET CLEANING SERVICES',
    'Nature Ar': 'خدمات غسيل المنسوجات والسجاد',
    'Subnature En': 'Textile And Carpet Cleaning Services',
    'Subnature Ar': 'خدمات غسيل المنسوجات والسجاد',
  },
  {
    'Nature En': 'TOURISM',
    'Nature Ar': 'السياحة',
    'Subnature En': 'Tourism',
    'Subnature Ar': 'السياحة',
  },
  {
    'Nature En': 'TRADE CENTERS',
    'Nature Ar': 'المراكز التجارية',
    'Subnature En': 'Trade Center',
    'Subnature Ar': 'مركز تجاري',
  },
  {
    'Nature En': 'TRADE CENTERS',
    'Nature Ar': 'المراكز التجارية',
    'Subnature En': 'Trade Center Comprising Residential Units',
    'Subnature Ar': 'مركز تجاري يضم وحدات سكنية',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Administrative Training',
    'Subnature Ar': 'التدريب الاداري',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Arts Training',
    'Subnature Ar': 'التدريب على الفنون',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Driving Institute',
    'Subnature Ar': 'معاهد تعليم القيادة',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Medical Training',
    'Subnature Ar': 'التدريب الطبي',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Occupational Training',
    'Subnature Ar': 'التدريب المهني',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Professional Training',
    'Subnature Ar': 'التدريب الحرفي',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Quran Memorization Institutes',
    'Subnature Ar': 'معاهد تحفيظ القران',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Security Training',
    'Subnature Ar': 'التدريب الامني',
  },
  {
    'Nature En': 'TRAINING CENTERS AND INSTITUTES',
    'Nature Ar': 'المراكز والمعاهد  التدريبية',
    'Subnature En': 'Training Centers And Institutions',
    'Subnature Ar': 'مراكز ومعاهد التدريب',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Air Transport',
    'Subnature Ar': 'النقل الجوي',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Bus Transport Services',
    'Subnature Ar': 'نقل الركاب بالحافلات',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Land Transport',
    'Subnature Ar': 'النقل البري',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Marine Transport',
    'Subnature Ar': 'النقل البحري',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Package Transport And Delivery Services',
    'Subnature Ar': 'خدمات نقل وتوصيل الطرود',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Rail Transport',
    'Subnature Ar': 'النقل بواسطة السكك الحديدية',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Taxi Transport Services',
    'Subnature Ar': 'خدمات النقل بسيارات الاجرة',
  },
  {
    'Nature En': 'TRANSPORTATION SERVICES',
    'Nature Ar': 'خدمات النقل',
    'Subnature En': 'Transport Services',
    'Subnature Ar': 'خدمات النقل',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Agencies For Vehicle And Spare Part Trading',
    'Subnature Ar': 'تجارة المركبات وقطع غيارها وكالات',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Driver License And Deportation Certificate Issue Services',
    'Subnature Ar': 'خدمات إصدار شهادة تسفير ورخص القيادة',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Jet Ski And Boat Trading',
    'Subnature Ar': 'تجارة الدراجات والقوارب',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'New And Used Vehicle Spare Part Trading',
    'Subnature Ar': 'تجارة قطع غيار المركبات الجديدة والمستعملة',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Trading Of New And Used Containers And Trailers',
    'Subnature Ar': 'تجارة الحاويات والمقطورات الجديدة والمستعملة',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Trading Of New And Used Semi-Trailers',
    'Subnature Ar': 'تجارة اشباه المقطورات الجديدة والمستعملة',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Vehicle Accessories Trading And Installation Services',
    'Subnature Ar': 'تجارة اكسسوارات وتركيب الاجزاء الاضافية للمركبات',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Vehicle Cleaning Services',
    'Subnature Ar': 'خدمات تنظيف المركبات',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Vehicle Inspection And Registration Services',
    'Subnature Ar': 'خدمات تسجيل وفحص المركبات',
  },
  {
    'Nature En':
      'VEHICLE AND MOTORCYCLE TRADING AND SERVICES (ELECTRIC - MOTOR - WATER)',
    'Nature Ar':
      'خدمات وتجارة  المركبات والدراجات (الكهربائية - النارية - المائية)',
    'Subnature En': 'Vehicle Maintenance And Repair Services',
    'Subnature Ar': 'خدمات الاصلاح والصيانه للمركبات',
  },
  {
    'Nature En': 'WASTE COLLECTION WORKS',
    'Nature Ar': 'أعمال تجميع النفايات',
    'Subnature En': 'Transport Vehicle Dismantling',
    'Subnature Ar': 'خدمات التفكيك وتحطيم وسائل النقل',
  },
  {
    'Nature En': 'WASTE COLLECTION WORKS',
    'Nature Ar': 'أعمال تجميع النفايات',
    'Subnature En': 'Used Garment Collection Services',
    'Subnature Ar': 'خدمات تجميع الملابس المستعملة',
  },
  {
    'Nature En': 'WASTE COLLECTION WORKS',
    'Nature Ar': 'أعمال تجميع النفايات',
    'Subnature En': 'Waste Collection Services',
    'Subnature Ar': 'خدمات تجميع النفايات',
  },
  {
    'Nature En': 'WASTE TREATMENT',
    'Nature Ar': 'معالجة النفايات',
    'Subnature En': 'Waste Treatment',
    'Subnature Ar': 'معالجة النفايات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Car Chassis Trading',
    'Subnature Ar': 'تجارة هياكل القطارات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'General Trading',
    'Subnature Ar': 'تجارة عامة',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Restaurants And Cafeterias (Franchises)',
    'Subnature Ar': 'المطاعم والكافتيريات حق الامتياز (الفرينشايز)',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Scrap Car Trading',
    'Subnature Ar': 'تجارة خردة السيارات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Tank And Tanker Wholesale',
    'Subnature Ar': 'التجارة بالجملة للخزانات والصهاريج',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Trade Of Oil And Its Derivatives',
    'Subnature Ar': 'تجارة النفط  ومشتقاته',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Trading In Explosives For Civil Uses',
    'Subnature Ar': 'تجارة المتفجرات للأغراض المدنية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale   Gases',
    'Subnature Ar': 'التجارة بالجملة للغازات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale   Raw Material',
    'Subnature Ar': 'التجارة بالجملة للمواد الخام',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Catering Services And Foodstuff',
    'Subnature Ar': 'التجارة بالجملة للمواد الغذائية وخدمات التموين',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Construction Materials And Equipment',
    'Subnature Ar': 'التجاره بالجمله لمواد وادوات البناء ولوازمها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Dietary Supplement',
    'Subnature Ar': 'التجارة بالجملة للمكملات الغذائية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Leathers And Animal Bones',
    'Subnature Ar': 'التجارة بالجملة للجلود وعظام الحيوانات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En':
      'Wholesale  Medical And Pharmaceutical Equipment And Accessories',
    'Subnature Ar': 'التجارة بالجملة للمعدات والمستلزمات  الطبية والصيدلانية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Monitoring, Measurement And Control Device',
    'Subnature Ar': 'التجارة بالجملة لأجهزة الرصد والقياس والتحكم',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Party Supplies And Accessories',
    'Subnature Ar': 'التجارة بالجملة لمستلزمات الحفلات ولوازمها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Photography Equipment And Accessories',
    'Subnature Ar': 'التجارة بالجملة لادوات ولوازم التصوير',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale  Train Spare Parts And Accessories',
    'Subnature Ar': 'التجارة بالجملة لقطع غيارالقطارات ولوازمها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En':
      'Wholesale Of   And Installation Of Alternative Energy Equipment',
    'Subnature Ar': 'التجارة بالجملة معدات الطاقة البديلة وتركيبها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of   Pets, Fish, Birds And Their Accessories',
    'Subnature Ar':
      'التجارة بالجملة للحيوانات الاليفة وأسماك وطيور الزينه ومستلزماتها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of  Flowers And Chocolate',
    'Subnature Ar': 'التجارة بالجملة للشوكولاه والزهور',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of  Ship And Water Vehicle',
    'Subnature Ar': 'التجارة بالجملة للسفن والآليات البحرية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of  Upholstery Equipment',
    'Subnature Ar': 'التجارة بالجملة للوازم التنجيد',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En':
      'Wholesale Of (Readymade Garments _ Perfume _ Footwear _ Accessories _ Bags _ Cosmetics)',
    'Subnature Ar':
      'التجارة بالجملة (الملابس الجاهزة - عطور - الاحذية - والاكسسورات - الحقائب - مواد التجميل )',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Agricultural Equipment And Tools',
    'Subnature Ar': 'التجارة بالجملة للمعدات وأدوات الزراعة',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En':
      'Wholesale Of Aircrafts And Their Accessories And Spare Parts',
    'Subnature Ar': 'التجارة بالجملة للطائرات و قطع غيارها  ولوازمها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Airport And Train Equipment And Accessories',
    'Subnature Ar': 'التجارة بالجملة لمعدات المطارات والقطارات ولوازمها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Alarm, Control And Fire Prevention Equipment',
    'Subnature Ar': 'التجارة بالجملة  لمعدات  الانذار والمراقية ومكافحة الحريق',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Camel And Horse Equipment And Accessories',
    'Subnature Ar': 'التجارة بالجملة لادوات ولوازم الخيل والهجن',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Chemicals',
    'Subnature Ar': 'التجارة بالجملة للكيماويات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Cigarettes, Tobaccos And Smokers Accessories',
    'Subnature Ar': 'التجارة بالجملة  لسجائر والتبغ ولوازم التدخين',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Compact Discs',
    'Subnature Ar': 'التجارة بالجملة الاقراص السمعية والبصرية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Computers And Their Accessories',
    'Subnature Ar': 'التجارة بالجملة للحاسب الالي ومستلزماته',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Cosmetics And Beauty Tools & Equipment',
    'Subnature Ar': 'التجارة بالجملة لمواد التجميل ومعدات  وأدوات التجميل',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Cotton And Plastic Products',
    'Subnature Ar': 'التجارة بالجملة للاقطان والبلاستك ومنتجاتها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En':
      'Wholesale Of Electronic And Electric Equipment And Accessories',
    'Subnature Ar': 'التجارة بالجملة للمعدات الكهربائية والإلكترونية ولوازمها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Electronics And Devices',
    'Subnature Ar': 'التجارة بالجمله للالكترونيات والاجهزة',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Equipment And Machine',
    'Subnature Ar': 'التجارة بالجمله للمعدات والاليات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Feeds, Coal, And Woods',
    'Subnature Ar': 'التجارة بالجملة (الأعلاف - الفحم - الحطب )',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Fishing Equipment And Tools',
    'Subnature Ar': 'التجارة بالجملة للمعدات وأدوات الصيد',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Flags And Flag Poles',
    'Subnature Ar': 'التجارة بالجملة للاعلام والسواري',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Furniture And Its Accessories',
    'Subnature Ar': 'التجارة بالجملة للاثاث ومستلزماته',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Glasses And Lenses',
    'Subnature Ar': 'التجارة بالجملة للعدسات والنظارات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Gold, Jewelry And Precious Watches',
    'Subnature Ar': 'التجارة بالجملة لذهب والمجوهرات والساعات الثمينه',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Handcrafts',
    'Subnature Ar': 'التجارة بالجملة للمشغولات اليدوية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Home Tools And Utensils',
    'Subnature Ar': 'التجارة بالجملة للادوات والاواني المنزلية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Insecticides And Cleaning Material',
    'Subnature Ar': 'التجارة بالجملة للمنظفات والمبيدات الحشرية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Live Animals',
    'Subnature Ar': 'التجارة بالجملة للحيوانات الحية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Medicines',
    'Subnature Ar': 'التجارة بالجملة للأدوية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Metals And Metallic Products',
    'Subnature Ar': 'التجارة بالجملة للمعادن ومنتجاتها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Phones And Their Accessories',
    'Subnature Ar': 'التجارة بالجملة للهواتف ومستلزماتها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Seeds And Plants',
    'Subnature Ar': 'التجارة بالجملة للبذور والشتلات الزراعية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Sports Equipment And Accessories',
    'Subnature Ar': 'التجارة بالجملة للادوات والمعدات الرياضية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Stationary And Books',
    'Subnature Ar': 'التجارة بالجملة للقرطاسية والكتب',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Tailoring Tools And Accessories',
    'Subnature Ar': 'التجارة بالجملة للوازم وأدوات الخياطة',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Tents And Trip Accessories',
    'Subnature Ar': 'التجارة بالجملة للخيم ولوازم الرحلات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Textiles',
    'Subnature Ar': 'التجارة بالجملة للمنسوجات والاقمشة',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Toys And Gifts',
    'Subnature Ar': 'التجارة بالجمله للألعاب  والهدايا',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Veterinary Equipment And Tools',
    'Subnature Ar': 'التجارة بالجملة للاجهزة والمواد البيطرية',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Wastes',
    'Subnature Ar': 'التجارة بالجملة للمخلفات',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Of Weapons And Military Equipment And Supplies',
    'Subnature Ar': 'التجارة بالجملة للأسلحة والمعدات العسكرية ولوازمها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Road Signs  And Installation',
    'Subnature Ar': 'التجارة بالجملة لللوحات المرورية وتركيبها',
  },
  {
    'Nature En': 'WHOLESALE',
    'Nature Ar': 'التجارة بالجملة',
    'Subnature En': 'Wholesale Trading In Ice',
    'Subnature Ar': 'التجارة بالجملة للثلج',
  },
  {
    'Nature En': 'WORKSHOP AND PAINTING WORKS',
    'Nature Ar': 'أعمال الورش والطلاء',
    'Subnature En': 'Carpentry Services',
    'Subnature Ar': 'ورشة نجارة',
  },
  {
    'Nature En': 'WORKSHOP AND PAINTING WORKS',
    'Nature Ar': 'أعمال الورش والطلاء',
    'Subnature En': 'Workshop And Painting Works',
    'Subnature Ar': 'أعمال الورش والطلاء',
  },
];

const getCategories = (locale: string) => {
  const lang = upperFirst(locale);
  return CATEGORIES.map((i: IVariables) => {
    const label =
      locale === 'en'
        ? startCase(camelCase(i[`Nature ${lang}`]))
        : i[`Nature ${lang}`];
    return {
      id: i[`Nature ${lang}`],
      label,
    };
  });
};

const getSubcategories = (locale: string, category: string) => {
  const lang = upperFirst(locale);
  const a = SUBCATEGORIES.filter(
    (i: IVariables) => i[`Nature ${lang}`] === category,
  ).map((i: IVariables) => {
    const label =
      locale === 'en'
        ? startCase(camelCase(i[`Subnature ${lang}`]))
        : i[`Subnature ${lang}`];
    return {
      id: i[`Subnature ${lang}`],
      label,
    };
  });
  return a;
};

export { getCategories, getSubcategories };
