import * as func from './functions';

const pageConfig = [
  {
    title: 'Upload Document',
    pageId: 'WlgdkVXQJ5EGiP2b7be1_',
    expanded: true,
    path: '/upload-document',
    template: 'custom',
    layout: 'sidebar',
    props: {
      definitions: [
        {
          componentId: 'qP5M5KOOT3aLbpNJj2iY0',
          type: 'text',
          props: {
            variant: 'h3',
            content: "i18n('UploadDocuments_UploadDocuments')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'mdErAo6yH0zLOpY8w7QwN',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('UploadDocuments_UploadDocsDesc')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'ljsLbhhdy-thga_Jz65yo',
          type: 'grid',
          props: {
            columns: 2,
            flexColumns: {
              xl: 2,
              lg: 2,
              md: 2,
              sm: 2,
            },
            space: {
              marginTop: 'lg',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'jlZ6SEoRBAFHnLuYoHl3Q',
              type: 'fileUpload',
              props: {
                tabIndex: 1,
                multiple: false,
                validateStatus: '${state.newLeaseContractValidateStatus}',
                validationMessage: '${state.newLeaseContractValidationMessage}',
                help: "i18n('ApplicationReturned_FileType')",
                disabled: false,
                label: "i18n('UploadDocuments_NewLeaseContract')",
                accept: ['application/pdf', 'image/png', 'image/jpg'],
                files: '${state.newLeaseContractFiles}',
                removeAriaLabel: 'file-remove-button',
                uploadAriaLabel: 'file-upload',
                removeAcceptForIOS: false,
                i18n: '',
                maxSize: 20971520,
                space: {
                  marginBottom: 'lg',
                },
                name: 'newLeaseContract',
                onChange: func.call_f1_onChange,
                onRemove: func.call_f2_onRemove,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'newLeaseContractValidateStatus',
                'newLeaseContractValidationMessage',
                'newLeaseContractFiles',
                'actions',
              ],
            },
            {
              componentId: 'oTqjkU9pSIP3C44Eu39g1',
              type: 'fileUpload',
              props: {
                tabIndex: 1,
                multiple: false,
                validateStatus: '${state.adEnvironmentPermitValidateStatus}',
                validationMessage:
                  '${state.adEnvironmentPermitValidationMessage}',
                help: "i18n('ApplicationReturned_FileType')",
                disabled: false,
                label: "i18n('UploadDocuments_ADEnvironmentPermit')",
                accept: ['image/png', 'application/pdf', 'image/jpg'],
                files: '${state.adEnvironmentPermitFiles}',
                removeAriaLabel: 'file-remove-button',
                uploadAriaLabel: 'file-upload',
                removeAcceptForIOS: false,
                i18n: '',
                maxSize: 20971520,
                name: 'adEnvironmentPermit',
                onChange: func.call_f3_onChange,
                onRemove: func.call_f4_onRemove,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'adEnvironmentPermitValidateStatus',
                'adEnvironmentPermitValidationMessage',
                'adEnvironmentPermitFiles',
                'actions',
              ],
            },
            {
              componentId: '8nCl9Pxi-295pSk6wkSqS',
              type: 'fileUpload',
              props: {
                tabIndex: 1,
                multiple: false,
                validateStatus:
                  '${state.civilDefenceCertificateValidateStatus}',
                validationMessage:
                  '${state.civilDefenceCertificateValidationMessage}',
                help: "i18n('ApplicationReturned_FileType')",
                disabled: false,
                label: "i18n('UploadDocuments_CivilDefenceCertificate')",
                accept: ['application/pdf', 'image/jpg', 'image/png'],
                files: '${state.civilDefenceCertificateFiles}',
                removeAriaLabel: 'file-remove-button',
                uploadAriaLabel: 'file-upload',
                removeAcceptForIOS: false,
                i18n: '',
                maxSize: 20971520,
                space: {
                  marginBottom: 'lg',
                },
                name: 'civilDefenceCertificate',
                onChange: func.call_f5_onChange,
                onRemove: func.call_f6_onRemove,
              },
              layout: 'base',
              columnIndex: 1,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'civilDefenceCertificateValidateStatus',
                'civilDefenceCertificateValidationMessage',
                'civilDefenceCertificateFiles',
                'actions',
              ],
            },
          ],
        },
        {
          componentId: 'JwlHyRMv-aac_n3J0u3gD',
          type: 'symbol',
          props: {
            symbol: 'xMN4736fUZ8gSHW5TTWMb',
            space: {
              marginTop: 'md',
              marginBottom: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'autoSaveStatus'],
        },
        {
          componentId: 'LpT09ryCzdYLus0iBGP7Y',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: 'md',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: '7wi0OL9Aa49PmVcxGApfw',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_BackButton')",
                type: 'button',
                uiType: 'secondary',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'start',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: '',
                  marginLeft: '',
                },
                onClick: func.f7_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
            {
              componentId: '-RchqyNCoqiJRWTglaqt0',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('ApplicationReturned_SubmitButton')",
                type: 'button',
                uiType: 'primary',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: 'md',
                  marginLeft: 'md',
                },
                onClick: func.call_f8_onClick,
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'history',
                'actions',
                'fetch',
                'bpm',
                'user',
                'licenceNumber',
                'contactInfoEmailAddress',
                'contactInfoName',
                'contactInfoPhNo',
                'leaseAgreementAmount',
                'leaseAgreementDate',
                'leaseAgreementNumber',
                'longitude',
                'latitude',
                'businessKey',
                'actions',
              ],
            },
            {
              componentId: 'BuLyV-clnegV3uN3GZlER',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_CancelButton')",
                type: 'button',
                uiType: 'text-link',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: true,
                onClick: func.f9_onClick,
                space: {
                  marginLeft: '',
                  marginRight: '',
                },
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
          ],
        },
      ],
      symbols: [
        {
          id: 'u_7BA0xr8Q0oku7QtzxvE',
          name: 'Header',
          definitions: [
            {
              componentId: '0nSNUzm6NEjCkToaBdmCl',
              type: 'alert',
              props: {
                status: '',
                message: '',
                onClose: null,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
            {
              componentId: 'Y78zMYB80jxbXDw2WuI6o',
              type: 'flexbox',
              props: {
                flexWrap: true,
                flexDirection: 'column-reverse',
                justifyContent: 'initial',
                alignItems: 'initial',
                alignContent: 'initial',
                classNames: 'container',
                space: {
                  marginBottom: '',
                  paddingBottom: '',
                },
              },
              layout: 'base',
              children: [
                {
                  componentId: 'uQukKScRci0q9DWO9b324',
                  parentComponentId: 'Y78zMYB80jxbXDw2WuI6o',
                  type: 'text',
                  props: {
                    variant: 'h1',
                    content: "i18n('Global_ServiceName')",
                    displayAsHtml: false,
                    space: {
                      paddingBottom: 'md',
                      marginTop: 'md',
                    },
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
                {
                  componentId: 'iyAIP8maLEkaZwI2t7dUy',
                  type: 'breadcrumb',
                  props: {
                    items: [
                      {
                        label: "i18n('bcrumbsHome')",
                        link: 'https://www.tamm.abudhabi/',
                        linkTarget: '',
                        id: 'kbzqdrrl',
                      },
                      {
                        label: "i18n('bcrumbsBusinessInAbuDhabi')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqe5hx',
                      },
                      {
                        label: "i18n('bcrumbsRegisterYourBusiness')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqeewv',
                      },
                      {
                        label: "i18n('bcrumbsIndustrialLicences')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqel7d',
                      },
                    ],
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
              ],
            },
          ],
        },
        {
          id: 'pOuCbjftw6l5xN5WTMEPb',
          name: 'Sidebar_without_card',
          definitions: [
            {
              componentId: 'yeIBuc-dVj7toDnj_7R81',
              type: 'stepTracker',
              props: {
                title: "i18n('ServicePage_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
                classNames: '',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: '2eXUqMf3xlTH9Dity7T6_',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: "i18n('Relevant_entity')",
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address: "i18n('address')",
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: true,
                space: {
                  marginTop: 'xl',
                  paddingBottom: 'lg',
                },
              },
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
        {
          id: 'xMN4736fUZ8gSHW5TTWMb',
          name: 'AutoSaved',
          definitions: [
            {
              componentId: 'Ri1CtARrVz3nuJc_XbMMd',
              type: 'dataLoader',
              props: {
                i18n: '',
                status: '${state.autoSaveStatus}',
                icon: null,
                message: '',
                space: {
                  marginTop: 'sm',
                  marginRight: 'sm',
                },
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'autoSaveStatus'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    customPath: true,
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'adgeName',
        'serviceCode',
        'productName',
        'autoSaveStatus',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'newLeaseContractValidateStatus',
        'newLeaseContractValidationMessage',
        'newLeaseContractFiles',
        'adEnvironmentPermitValidateStatus',
        'adEnvironmentPermitValidationMessage',
        'adEnvironmentPermitFiles',
        'civilDefenceCertificateValidateStatus',
        'civilDefenceCertificateValidationMessage',
        'civilDefenceCertificateFiles',
        'licenceNumber',
        'contactInfoEmailAddress',
        'contactInfoName',
        'contactInfoPhNo',
        'leaseAgreementAmount',
        'leaseAgreementDate',
        'leaseAgreementNumber',
        'longitude',
        'latitude',
        'businessKey',
      ],
      mapDispatch: [
        'newLeaseContractValidationMessage',
        'newLeaseContractValidateStatus',
        'civilDefenceCertificateValidateStatus',
        'civilDefenceCertificateValidationMessage',
        'adEnvironmentPermitValidateStatus',
        'adEnvironmentPermitValidationMessage',
        'loading',
        'showSidebar',
        'currentStepIndex',
        'currentSubStepIndex',
        'expandedStepIndexes',
        'steps',
        'newLeaseContractFiles',
        'adEnvironmentPermitFiles',
        'civilDefenceCertificateFiles',
        'autoSaveStatus',
        'instanceId',
        'businessKey',
      ],
    },
    init: func.init,
    fromProcessState: {
      processName: 'workbench',
      variables: ['capId', 'apTransactionNumber'],
    },
  },
];

export default pageConfig;
