export default {
  Key: 'Arabic content value (REVIEWED)',
  Global_Title: 'طلب إصدار شهادة القيمة المحلية',
  ServiceCard_Start: 'ابدأ',
  ServiceCard_Time: ' 10 أيام عمل  ',
  ServiceCard_DescriptionTitle: 'الوصف',
  ServiceCard_Desc:
    'من خلال هذه الخدمة، يمكنك الحصول على شهادة القيمة المحلية لتتمكن من المشاركة كمورد بفاعلية في برنامج المشتريات الحكومية وشبه الحكومية.',
  ServiceCard_Process: 'الخطوات',
  ServiceCard_Step1: 'املأ الطلب',
  ServiceCard_Step1Desc: 'ادخل المعلومات المطلوبة عن الشركة.',
  ServiceCard_Step2: 'احصل على الشهادة ',
  ServiceCard_Step2Desc:
    'قدّم طلبك للجهة ذات الصلة وفور الموافقة ستحصل على الشهادة.',
  SelectLicence_Title: 'اختر الرخصة ',
  SelectLicence_Desc:
    'يرجى تحديد رقم الرخصة للحصول على الشهادة. فور إكمال الخطوات، يرجى المتابعة للقسم التالي.',
  SelectLicence_MyLicencesTable: 'رُخصي',
  SelectLicence_Search: 'ابحث',
  SelectLicence_LicenceNumberCol: 'رقم الرخصة ',
  SelectLicence_CompanyNameCol: 'اسم الشركة ',
  SelectLicence_ShowingPagination: 'عرض',
  SelectLicence_NoLicence: 'لا يوجد أي رخصة مرتبطة بحسابك.',
  SelectLicence_LinkLicence:
    'إن لم تجد رقم رخصتك مدرجاً أدناه، يرجى ربط رخصتك بحسابك أو التواصل مع دائرة التنمية الاقتصادية على الرقم 0097128158888.',
  ContactDetails_AddContactInformation: 'أضف معلومات الاتصال ',
  ContactDetails_Desc:
    'يُرجى تقديم بيانات الاتصال أدناه، والتي ستُسخدم لغايات التواصل معك بشأن طلبك.',
  ContactDetails_ContactPerson:
    'أنا مسؤول التواصل لهذا الطلب. يمكن الحصول على بيانات الاتصال من تفاصيل الحساب.',
  ContactDetails_Name: 'الاسم <ادخل>',
  ContactDetails_PhoneNumber: 'الهاتف المحمول',
  ContactDetails_EmailAddress: 'البريد الإلكتروني',
  ContactDetails_Disclaimer:
    'أتعهد بالالتزام بكافة الاشتراطات والمتطلبات المنصوص عليها بالقوانين والقرارات المنظمة للأنشطة الاقتصادية من إصدار/تجديد/تعديل التراخيص التجارية، وكافة البيانات الواردة بالطلب، و أتعهد بعدم ممارسة النشاط التجاري إلا بعد الحصول على موافقات الجهات المختصة بالتراخيص، وللدائرة الحق باتخاذ الإجراءات القانونية والإدارية في حال عدم الالتزام بالتعهد.',
  Global_Autosave: 'تم حفظ طلبك بشكل تلقائي',
  Global_Back: 'الرجوع',
  Global_Next: 'التالي',
  Global_Cancel: 'إلغاء',
  Global_FillApplication: 'املأ الطلب',
  Global_HideSteps: 'إخفاء الخطوات',
  Global_SelectLicence: 'اختر الرخصة ',
  Global_SelectCertifiedEntities: 'اختر جهات مراجعة الأداء',
  Global_EnterCompanyDetails: 'ادخل تفاصيل الشركة ',
  Global_UploadDocuments: 'تحميل المستندات',
  Global_AddContactInformation: 'أضف معلومات الاتصال ',
  Global_GetCertificate: 'احصل على الشهادة ',
  Global_ShowSteps: 'عرض الخطوات',
  SelectEntity_SelectCertifiedEntities: 'اختر الهيئات المعتمدة',
  SelectEntity_Desc:
    'يرجى اختيار جميع الجهات التي ترغب في الحصول على عرض سعر منها. \n' +
    'ملاحظة: يمكن اختيار أكثر من جهة',
  SelectEntity_Entity1: 'أردنت للاستشارات المالية والمحاسبة ذ.م.م',
  SelectEntity_Entity2: 'بيكر تلي ام كي ام محاسبون قانونيون',
  SelectEntity_Entity3: 'ديلويت آند توش (الشرق الأوسط)',
  SelectEntity_Entity4: 'إرنست ويونغ - الشرق الاوسط',
  SelectEntity_Entity5: 'بروتيفتي ميمبر فيرم (الشرق الأوسط)',
  SelectEntity_Entity6: 'مازاراس للمحاسبة القانونية ',
  SelectEntity_Entity7: 'كرو الإمارات',
  SelectEntity_Entity8: 'إم بي سي للتدقيق والمحاسبة - أبوظبي',
  SelectEntity_Entity9: 'بيه كي اف -  محاسبون قانونيون ومستشارو أعمال',
  SelectEntity_Entity10: 'طلال أبو غزالة وشركاه الدولية - أبوظبي',
  UploadDocuments_UploadDocuments: 'تحميل المستندات',
  UploadDocuments_Desc: 'يرجى تحميل الملفات المطلوبة.',
  UploadDocuments_SelectFile: 'اختر الملف ',
  UploadDocuments_DropFile: 'أو اسحب الملفات وضعها هنا ',
  UploadDocuments_FileType: 'نوع الملف:   JPG أو  PDF أو  PNG',
  UploadDocuments_FileSize: 'الحجم الأقصى المسموح به: 20 ميجابايت للملف الواحد',
  UploadDocuments_Disclaimer:
    'باختيار هذا المربع، أمنح موافقتي على مشاركة بياناتي والمعلومات المتعلقة بطلبي وجميع الملفات التي قدمتها لمكتب تنمية الصناعة وجميع الجهات ذات الصلة.',
  AwaitingApproval_PleaseWait: 'تم تقديم طلبك بنجاح ',
  Global_SubmittedOn: 'تاريخ التقديم:',
  AwaitingApproval_Refresh: 'سيتم تحديث بيانات الصفحة بعد صدور الرقم المرجعي.',
  AwaitingApproval_Notify:
    'سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجَّل. كما يمكنك مراجعة حالة الطلب بنفسك  في أي وقت من خلال لوحة التحكم "أدِر شركتك".',
  ReceiveQuotations_ReceivingEntityQuotations:
    'عروض الأسعار من الجهات قيد الاستلام',
  Global_ReferenceNo: 'الرقم المرجعي:',
  ReceiveQuotations_Desc:
    'يرجى الانتظار قليلاً ريثما نستلم عروض الأسعار من الجهات التي اخترتها. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجَّل. \n' +
    '\n' +
    'يمكنك تنزيل ومراجعة عروض الأسعار واتخاذ القرار المناسب. فور اختيارك لمزود الخدمة، يُرجى متابعة طلبك وتقديمه للجهة ذات الصلة.',
  ReceiveQuotations_Refresh:
    'سيتم تحديث الجدول وإضافة عروض الأسعار الصادر من الجهات.',
  Global_QuotationSummary: 'ملخص عرض الأسعار',
  Global_EntityCol: 'الجهة',
  Global_QuotationAmountCol: 'قيمة عرض السعر',
  Global_ActionsCol: 'الإجراءات',
  ReceiveQuotations_PendingQuote: 'قيد انتظار عرض السعر',
  ReceiveQuotations_Request:
    'طلبت إحدى الجهات معلومات إضافية. يُرجى مراجعة التعليقات ثم تحديث الطلب.',
  ReceiveQuotations_ViewFeedback: 'مراجعة التعليقات',
  Global_AwardContract: 'ترسية العقد',
  Global_SubmitApplication: 'تقديم الطلب',
  Global_ReviewQuotations: 'مراجعة الأسعار',
  Global_GetApproval: 'الحصول على الموافقة',
  Global_DownloadCertificate: 'تنزيل الشهادة ',
  ApplicationReturned_ApplicationReturned: 'تمت إعادة طلبك',
  ApplicationReturned_Desc:
    'طلبت إحدى الجهات معلومات إضافية. يُرجى مراجعة التعليقات ثم تحديث الطلب.',
  ApplicationReturned_Feedback: 'التعليقات',
  ApplicationReturned_DocumentUpload: 'تحميل المستندات',
  ApplicationReturned_DocumentUploadDesc:
    'يرجى تحميل الملفات المطلوبة بناءً على تعليقات الجهة. يمكنك تحميل أي عدد مطلوب من الملفات.',
  ApplicationReturned_PleaseNote: 'يرجى الانتباه:',
  ApplicationReturned_PleaseNoteDesc:
    'تجد أدناه جميع التعليقات من الجهات المعنية بطلبك. قد يتكرر طلب بعض الملفات نفسها، يمكنك تحميلها مرة واحدة. \n' +
    'ملاحظة: ستستلم جميع الجهات الملفات التي حمّلتها. ',
  ApplicationReturned_ViewQuotationsList: 'الرجوع لقائمة عروض الأسعار',
  QuotationReceived_EntityQuotationsReceived:
    'تم استلام عروض الأسعار من الجهات',
  QuotationReceived_Desc:
    'يمكنك تنزيل ومراجعة عروض الأسعار واتخاذ القرار المناسب. فور اختيارك لمزود الخدمة، يُرجى متابعة طلبك وتقديمه للجهة ذات الصلة.',
  QuotationReceived_Download: 'تنزيل',
  UnderApproval_UnderApproval: 'طلبك قيد الموافقة ',
  UnderApproval_Refresh:
    'سيتم تحديث هذه الصفحة وتأكيدها فور وصول تحديثات جديدة على الطلب.',
  UnderApproval_Desc:
    'تم تقديم طلبك للحصول على موافقة من الجهة التي اخترتها ومن دائرة التنمية الاقتصادية. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجَّل. كما يمكنك مراجعة حالة الطلب بنفسك  في أي وقت من خلال لوحة التحكم "أدِر شركتك".',
  CertificateIssued_Issued: 'صدرت الشهادة',
  CertificateIssued_Desc:
    'تهانينا! صدرت شهادتك وبإمكانك تنزيل نسخة منها أدناه.',
  CertificateIssued_QuotationSummary: 'ملخص الأسعار',
  CertificateIssued_SelectedEntityCol: 'الجهة المختارة',
  CertificateIssued_QuotationAmountCol: 'قيمة عرض السعر',
  CertificateIssued_DownloadCertificate: 'تنزيل الشهادة ',
  CertificateIssued_VisitDashboard: 'زُر لوحة التحكم',
  CertificateIssued_Rate: 'كيف تقيّم تجربتك؟',
  ExistingApplication_Continue: 'هل ترغب في استكمال طلب موجود؟',
  ExistingApplication_Desc:
    'يوجد طلب مفتوح لهذه الرخصة. هل ترغب في استكمال الطلب أم بدء طلب جديد؟\n' +
    'ملاحظة: بدء طلب جديد سيحذف الطلب المفتوح سابقًا.',
  ExistingApplication_Start: 'ابدأ طلب جديد',
  OngoingApplication_OngoingApplication: 'طلبك قيد المراجعة ',
  OngoingApplication_Desc:
    'يوجد طلب مفتوح تم تقديمه مسبقاً لهذه الخدمة. وبما أن هذا الطلب قيد المراجعة، فلن تتمكن من بدء طلب جديد.\n' +
    'هل ترغب في التحقق من حالة الطلب بدلاً من ذلك؟',
  OngoingApplication_ChooseAnotherLicence: 'اختر رخصة أخرى ',
  OngoingApplication_CheckStatus: 'تحقق من الحالة ',
  EnterCompanyDetails_EnterCompanyDetails: 'ادخل معلومات الشركة ',
  EnterCompanyDetails_Desc:
    'يُرجى إدخال معلومات وبيانات الشركة كما هو مطلوب أدناه:',
  EnterCompanyDetails_InCountryValueEmirate: 'إمارة صدور شهادة القيمة المحلية',
  EnterCompanyDetails_Brach: 'فرع الظفرة/العين ',
  EnterCompanyDetails_Subcontracts: 'قيمة المقاولات الفرعية ',
  EnterCompanyDetails_SubcontractsInAbuDhabi:
    'قيمة المقاولات الفرعية في أبوظبي',
  EnterCompanyDetails_SalariesAbuDhabi: 'إجمالي رواتب الموظفين في أبوظبي',
  EnterCompanyDetails_SalariesEmiratiEmployees:
    'إجمالي رواتب ومستحقات الموظفين الإماراتيين ',
  EnterCompanyDetails_SalariesExpatEmployees:
    'إجمالي رواتب ومستحقات الموظفين الأجانب ',
  EnterCompanyDetails_NumberOfEmployees: 'إجمالي عدد الموظفين',
  EnterCompanyDetails_AssetsNetBook:
    'صافي القيمة الدفترية للأصول التي تملكها الشركة',
  EnterCompanyDetails_AssetsNetBookAbuDhabi:
    'صافي القيمة الدفترية للأصول التي تملكها الشركة في أبوظبي',
  EnterCompanyDetails_TotalRevenue: 'إجمالي الأرباح ',
  EnterCompanyDetails_IndustrialInformation: 'ادخل المعلومات الصناعية',
  EnterCompanyDetails_RawMaterialsPurchased: 'قيمة المواد الخام المشتراة',
  EnterCompanyDetails_RawMaterialsPurchasedAbuDhabi:
    'قيمة المواد الخام المشتراة في أبوظبي',
  EnterCompanyDetails_OtherExpenses:
    'قيمة المصاريف الأخرى باستثناء تكلفة العمالة',
  Global_1: 1,
  Global_2: 2,
  Global_3: 3,
  Global_4: 4,
  Global_5: 5,
  'form.cancel': 'إلغاء',
  SelectLicence_ContactPerson:
    'أنا مسؤول التواصل لهذا الطلب. يمكن الحصول على بيانات الاتصال من تفاصيل الحساب.',
  SelectLicence_Name: 'الاسم <ادخل>',
  SelectLicence_PhoneNumber: 'الهاتف المحمول',
  SelectLicence_EmailAddress: 'البريد الإلكتروني',
  pleaseNoteText: 'ar-value',
  licenceStatus_nextStep_title: 'ar-value',
  licenceStatus_nextStep_description: 'ar-value',
  relatedServices_1: 'ar-value',
  relatedServices_2: 'ar-value',
  relatedServices_3: 'ar-value',
  relatedServices_4: 'ar-value',
  relatedServices_5: 'ar-value',
  relatedServices_6: 'ar-value',
  relatedServices_7: 'ar-value',
  relatedServices_8: 'ar-value',
  entityInformationDescription: 'ar-value',
  valueOfRawMaterialsPurchased: 'ar-value',
  valueOfOtherExpensesExcludingManpowerCost: 'ar-value',
  assetsNetBookValueHeldByCompanyInAbuDhabi: 'ar-value',
  assetsNetBookValueHeldByCompany: 'ar-value',
  totalNumberOfEmployees: 'ar-value',
  totalRevenue: 'ar-value',
  valueOfRawMaterialsPurchasedInAbuDhabi: 'ar-value',
  icvEmirate: 'ar-value',
  valueOfSubcontractsInAbuDhabi: 'ar-value',
  valueOfSubcontracts: 'ar-value',
  totalSalariesAndBenefitsOfEmiratis: 'ar-value',
  totalSalariesofEmployeesWithAbuDhabi: 'ar-value',
  totalSalariesAndBenefitsOfExpatEmployees: 'ar-value',
  enterIndustrialEntityInformationDescription: 'ar-value',
  enterIndustrialEntityInformation: 'ar-value',
  no: 'ar-value',
  yes: 'ar-value',
  companyDetailsTitle: 'ar-value',
  companyDetailsDescription: 'ar-value',
  select: 'ar-value',
  branchinAlDhafraAlAin: 'ar-value',
  SelectLicence_Disclaimer:
    'أتعهد بالالتزام بكافة الاشتراطات والمتطلبات المنصوص عليها بالقوانين والقرارات المنظمة للأنشطة الاقتصادية من إصدار\\/تجديد\\/تعديل التراخيص التجارية، وكافة البيانات الواردة بالطلب، و أتعهد بعدم ممارسة النشاط التجاري إلا بعد الحصول على موافقات الجهات المختصة بالتراخيص، وللدائرة الحق باتخاذ الإجراءات القانونية والإدارية في حال عدم الالتزام بالتعهد.',
  abuDhabi: 'ar-value',
  ajman: 'ar-value',
  dubai: 'ar-value',
  rasAlKhaimah: 'ar-value',
  sharjah: 'ar-value',
  ummAlQuwain: 'ar-value',
  alFujairah: 'ar-value',
  upload_documents: 'ar-value',
  enter_company_details: 'ar-value',
  btn_submit: 'ar-value',
  adv_something_went_wrong: 'ar-value',
  adv_something_went_wrong_desc: 'ar-value',
  UploadDocuments_Document1: 'الكشوف المالية المدققة (العام الماضي)',
  UploadDocuments_Document2:
    'قائمة القوة العاملة الصادرة من وزارة الموارد البشرية  والتوطين- أبوظبي',
  UploadDocuments_Document3: 'تفاصيل رواتب العمال',
  UploadDocuments_Document4: 'عدد المواطنين الإماراتيين في القوة العاملة ',
  UploadDocuments_Document5: 'تفاصيل وعدد العمال في كل وردية ',
  UploadDocuments_Document6: 'تفاصيل القوة الكهربائية للموقع ',
  UploadDocuments_Document7: 'تفاصيل ساعات العمل اليومية',
  UploadDocuments_Document8: 'تفاصيل ساعات العمل في الوردية الواحدة',
  SelectLicence_AddContactInformation: 'أضف معلومات الاتصال ',
};
