import * as func from './functions';

const pageConfig = [
  {
    title: 'Licence Issued',
    pageId: '0yLXgfI12gymH5osvEghn',
    expanded: true,
    path: '/licence-issued',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'XZAUjDzuXLNEuLSmSmAU3',
          type: 'notice',
          props: {
            status: 'success',
            icon: null,
            title: "i18n('LicenceIssued_LicenceRenewedTitle')",
            tags: '${state.individualIssuedTags}',
            content: "i18n('LicenceIssued_LicenceRenewedDesc')",
            buttons: [
              {
                label: "i18n('LicenceIssued_DownloadButton')",
                type: 'button',
                uiType: 'primary',
                onClick: func.call_f1_buttons_onClick,
                disabled: '',
                'aria-label': '',
                link: '',
                target: '',
                icon: '',
                alignIcon: 'last',
                withArrow: false,
                id: 'kc0drvb4',
              },
              {
                label: "i18n('LicenceIssued_VisitDashboardButton')",
                type: 'button',
                uiType: 'secondary',
                onClick: func.f2_buttons_onClick,
                disabled: '',
                'aria-label': '',
                link: '',
                target: '',
                icon: '',
                alignIcon: '',
                withArrow: '',
                id: 'kc0drx6v',
              },
            ],
            space: {
              marginBottom: 'lg',
            },
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'fetch',
            'renewalNumber',
            'recordId',
            'instanceId',
            'individualIssuedTags',
            'actions',
          ],
        },
        {
          componentId: 'GOTM6JCp6CeYHwW19z6G_',
          type: 'customerSatisfaction',
          props: {
            i18n: '',
            status: 'idle',
            emotion: '',
            onSubmit: '',
            rates: [
              {
                value: '',
                starsCount: 3,
                min: '',
                max: '',
                step: '',
                id: 'kbu0xo8l',
              },
            ],
            withComment: false,
            space: {
              marginBottom: 'lg',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'k8Cb_69S_zXZI2J39onOZ',
          type: 'text',
          props: {
            variant: 'h4',
            content: "i18n('LicenceIssued_NextSteps')",
            displayAsHtml: false,
            classNames: '',
            space: {
              marginTop: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'TEJTipP-hZOMOgbuU5Zor',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('LicenceIssued_NextStepsDesc')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: '0nuwmZD0GPzPhwEBHaN-T',
          type: 'symbol',
          props: {
            symbol: '_rSFAtv4sbf3yNFwRaLhl',
            space: {
              marginBottom: '',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
      ],
      symbols: [
        {
          id: '_rSFAtv4sbf3yNFwRaLhl',
          name: 'related_services',
          definitions: [
            {
              componentId: '7Dyp8Ryc_Uox5AXD8er46',
              type: 'grid',
              props: {
                columns: 3,
                flexColumns: {
                  xl: 3,
                  lg: 3,
                  md: 3,
                  sm: 3,
                },
                space: {
                  marginBottom: 'xl',
                  marginTop: '',
                },
              },
              layout: 'base',
              children: [
                {
                  componentId: 'IHbxFK7bgcfvbhplRQjpW',
                  type: 'list',
                  props: {
                    i18n: '',
                    title: '',
                    items: [
                      {
                        id: 'kc076fsm',
                        label: "i18n('LicenceIssued_NextStepsLink1')",
                        description: '',
                        link: '',
                        linkTarget: '_parent',
                      },
                      {
                        id: 'kc078fhp',
                        label: "i18n('LicenceIssued_NextStepsLink3')",
                        description: '',
                        link: '',
                        linkTarget: '',
                      },
                      {
                        id: 'kc09mlzw',
                        label: "i18n('LicenceIssued_NextStepsLink5')",
                        description: '',
                        link: '',
                        linkTarget: '',
                      },
                      {
                        id: 'kc09mwa7',
                        label: "i18n('LicenceIssued_NextStepsLink7')",
                        description: '',
                        link: '',
                        linkTarget: '',
                      },
                    ],
                    withArrow: true,
                    withBoldContent: true,
                    expanded: false,
                    allowedNotExpandedLimit: 5,
                    showMoreLabels: [],
                    applyStrictWidth: false,
                    uiType: 'link',
                    onClick: {
                      type: 'func',
                      actions: [],
                    },
                  },
                  layout: 'base',
                  columnIndex: 0,
                  sharedProps: ['i18n', 'locale'],
                },
                {
                  componentId: 'vpaNky4Arb3YrRkdx8fII',
                  type: 'list',
                  props: {
                    i18n: '',
                    title: '',
                    items: [
                      {
                        id: 'kc076fsm',
                        label: "i18n('LicenceIssued_NextStepsLink2')",
                        description: '',
                        link: '',
                        linkTarget: '_parent',
                      },
                      {
                        id: 'kc078fhp',
                        label: "i18n('LicenceIssued_NextStepsLink4')",
                        description: '',
                        link: '',
                        linkTarget: '',
                      },
                      {
                        id: 'kc09nhi3',
                        label: "i18n('LicenceIssued_NextStepsLink6')",
                        description: '',
                        link: '',
                        linkTarget: '',
                      },
                      {
                        id: 'kc09nnms',
                        label: "i18n('LicenceIssued_NextStepsLink8')",
                        description: '',
                        link: '',
                        linkTarget: '',
                      },
                    ],
                    withArrow: true,
                    withBoldContent: true,
                    expanded: false,
                    allowedNotExpandedLimit: 5,
                    showMoreLabels: [],
                    applyStrictWidth: false,
                    uiType: 'link',
                    onClick: {
                      type: 'func',
                      actions: [],
                    },
                  },
                  layout: 'base',
                  columnIndex: 1,
                  sharedProps: ['i18n', 'locale'],
                },
              ],
            },
          ],
        },
        {
          id: 'u_7BA0xr8Q0oku7QtzxvE',
          name: 'Header',
          definitions: [
            {
              componentId: '0nSNUzm6NEjCkToaBdmCl',
              type: 'alert',
              props: {
                status: '',
                message: '',
                onClose: null,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
            {
              componentId: 'Y78zMYB80jxbXDw2WuI6o',
              type: 'flexbox',
              props: {
                flexWrap: true,
                flexDirection: 'column-reverse',
                justifyContent: 'initial',
                alignItems: 'initial',
                alignContent: 'initial',
                classNames: 'container',
                space: {
                  marginBottom: '',
                  paddingBottom: '',
                },
              },
              layout: 'base',
              children: [
                {
                  componentId: 'uQukKScRci0q9DWO9b324',
                  parentComponentId: 'Y78zMYB80jxbXDw2WuI6o',
                  type: 'text',
                  props: {
                    variant: 'h1',
                    content: "i18n('Global_ServiceName')",
                    displayAsHtml: false,
                    space: {
                      paddingBottom: 'md',
                      marginTop: 'md',
                    },
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
                {
                  componentId: 'iyAIP8maLEkaZwI2t7dUy',
                  type: 'breadcrumb',
                  props: {
                    items: [
                      {
                        label: "i18n('bcrumbsHome')",
                        link: 'https://www.tamm.abudhabi/',
                        linkTarget: '',
                        id: 'kbzqdrrl',
                      },
                      {
                        label: "i18n('bcrumbsBusinessInAbuDhabi')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqe5hx',
                      },
                      {
                        label: "i18n('bcrumbsRegisterYourBusiness')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqeewv',
                      },
                      {
                        label: "i18n('bcrumbsIndustrialLicences')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqel7d',
                      },
                    ],
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
              ],
            },
          ],
        },
        {
          id: 'pOuCbjftw6l5xN5WTMEPb',
          name: 'Sidebar_without_card',
          definitions: [
            {
              componentId: 'yeIBuc-dVj7toDnj_7R81',
              type: 'stepTracker',
              props: {
                title: "i18n('ServicePage_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
                classNames: '',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: '2eXUqMf3xlTH9Dity7T6_',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: "i18n('Relevant_entity')",
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address: "i18n('address')",
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: true,
                space: {
                  marginTop: 'xl',
                  paddingBottom: 'lg',
                },
              },
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    customPath: true,
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'adgeName',
        'serviceCode',
        'productName',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'renewalNumber',
        'recordId',
        'instanceId',
        'individualIssuedTags',
      ],
      mapDispatch: [
        'showSidebar',
        'currentStepIndex',
        'currentSubStepIndex',
        'expandedStepIndexes',
        'steps',
        'renewalNumber',
        'recordId',
        'individualIssuedTags',
        'download_value',
        'loading',
      ],
    },
    init: func.init,
    onPageInit: func.onPageInit,
    fromProcessState: {
      processName: 'workbench',
      variables: [
        'renewalNumber',
        'recordId',
        'submitDate',
        'email',
        'continueProcessUrl',
        'feeDetails',
      ],
    },
  },
];

export default pageConfig;
