export default {
  serviceCardServicename: 'طلب إصدار شهادة سجل اقتصادي - صناعي',
  process: 'العملية',
  selectLicenceTitle: 'اختر الرخصة ',
  selectLicenceDescription:
    'يُرجى اختيار رقم رخصة صناعية سارية ترغب بإصدار شهادة سجل اقتصادي لها.',
  globalNext: 'التالي',
  globalCancel: 'إلغاء',
  paymentSummaryPayButton: 'ادفع',
  bc_home: 'الصفحة الرئيسية',
  bc_digitalServices: 'الخدمات الرقمية',
  bc_DED: 'دائرة التنمية الاقتصادية',
  pleaseLogIn: 'يُرجى تسجيل الدخول',
  bc_economicLicences: 'الرخصة الاقتصادية',
  applicantDetailsCheckboxContact: 'أنا مسؤول الاتصال لهذا الطلب.',
  applicantDetailsNameField: 'الاسم ',
  applicantDetailsNumberField: 'رقم الهاتف المحمول',
  applicantDetailsEmailField: 'عنوان البريد الإلكتروني ',
  errorContactName: 'هذه الخانة مطلوبة\t',
  errorContactEmail: 'هذا الخانة مطلوبة ويجب أن تحتوي على عنوان بريد إلكتروني.',
  errorContactMobile: 'هذه الخانة مطلوبة ويجب أن تحتوي على رقم هاتف محمول',
  errorLicenceNotSelected: 'الرجاء اختيار رخصة ',
  applicantDetailsTitle: 'بيانات الاتصال لصاحب الطلب',
  applicantDetailsDescription:
    'يُرجى تقديم بيانات الاتصال أدناه، والتي ستُسخدم لغايات التواصل معك بشأن طلبك.',
  globalBack: 'الرجوع',
  applicationApprovedDownloadCertificate: 'إصدار الرخصة',
  applicationApprovedDownloadReceipt: 'تنزيل الإيصال',
  visitDashboard: 'Visit Dashboard',
  paymentSummaryTitle: 'تمت الموافقة على طلبك',
  paymentSummaryDescription:
    'أصدرت دائرة التنمية الاقتصادية رقماً مرجعياً لهذه المعاملة. ستصلك التحديثات عن طلبك على البريد الإلكتروني ورقم الهاتف المحمول المسجلين. يرجى متابعة عملية الدفع هنا. ',
  paymentSummaryTableTitle: 'ملخص المدفوعات',
  globalReference: 'الرقم المرجعي:',
  globalSubmitted: 'تاريخ التقديم:',
  waitingApprovalDescription:
    'يرجى الانتظار بينما يحدث الاتصال بدائرة التنمية الاقتصادية لبدء عملية الدفع. قد يستغرق هذا مدة تصل إلى 5 دقائق. سيتم تحديث هذه الصفحة بمجرد صدور الرقم المرجعي الخاص بك. سيتم إخطارك بالتغييرات التي تطرأ على حالة طلبك على عنوان البريد الإلكتروني ورقم الهاتف المحمول المسجلين. يمكنك أيضًا التحقق من حالة طلبك في أي وقت عن طريق زيارة لوحة التحكم الخاصة بك.',
  waitingApprovalTitle: 'تأكيد الطلب',
  paymentFailedTitle: 'تمت عملية الدفع بنجاح',
  paymentFailedDescription:
    'عذرًا، لم تنجح عملية الدفع. يمكنك المحاولة مرة أخرى في وقت لاحق. إذا واجهتك أي مشكلة، يُرجى الإبلاغ عنها.',
  tryAgain: 'حاول مرة أخرى',
  somethingWentWrongTitle: 'حصل خطأ ما ',
  somethingWentWrongDescription:
    'حدث خطأ ما أثناء معالجة طلبك. يُرجى المحاولة مرة أخرى.',
  NoInformationFoundTitle: 'لا تتوفر أية معلومات ',
  NoInformationFoundDescription:
    'لم نتكمن من العثور على تفاصيل متعلقة بالمعلومات المذكورة هنا. الرجاء المحاولة مرة أخرى. ',
  step_selectLicence: 'اختر الرخصة ',
  step_enterContactDetails: 'بيانات الاتصال لصاحب الطلب',
  step_makePayment: 'ادفع',
  subStep_requestConfirmation: 'طلب تأكيد',
  subStep_payAmount: 'ادفع الرسوم',
  step_downloadCertificate: 'إصدار الرخصة',
  timeoutMessage: 'انتهت الجلسة. يرجى إعادة التحميل لتحديثها مرة أخرى',
  applicationApprovedTitle: 'صدرت شهادة السجل الاقتصادي الخاصة بك ',
  selectLicenceTableTitle: 'جميع رُخصي',
  accountUpgrade: 'مطلوب تحديث الحساب',
  accoundUpgradeDescription:
    'يجب ترقية حسابك، لتتمكن من الحصول على الخدمة، لترقية الحساب، اضغط على الرابط.',
  upgradeAccount: 'يرجى تحديث حسابك',
  selectLicenceLicenceColumn: 'رقم الرخصة ',
  selectLicenceCompanyColumn: 'اسم الشركة ',
  paymentSummaryDescriptionColumn: 'الوصف',
  paymentSummaryPriceColumn: 'السعر',
  paymentWaitingTitle: 'بانتظار تأكيد الدفع',
  paymentWaitingDescription:
    'سيتم تحديث بيانات الصفحة فور تمام عملية الدفع. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجل. كما يمكنك مراجعة حالة الطلب بنفسك  في أي وقت من خلال لوحة التحكم "أدِر شركتك".',
  relevantEntity: 'الجهة الحكومية ذات الصلة',
  paymentWaitingWaitingMessageDescription:
    'إن لم تفتح الشاشة بشكل تلقائي، الرجاء الضغط هنا.',
  noActiveLicenceTitle: 'لا يوجد أي رخص فعّالة',
  noActiveLicenceDescription: 'لا تظهر أي رخصة مرتبطة بحسابك.',
  waitingApprovalWaitingMessage: 'الرجاء الانتظار للحصول على معلومات إضافية.',
  paymentWaitingWaitingMessage:
    'ستظهر لك شاشة بوابة الدفع تلقائياً في نافذة جديدة.',
  continueProcessTitle: 'سيتم الانتقال للصفحة المطلوبة سريعًا',
  continueProcessDescription: 'يرجى الانتظار قليلاً لحين التحقق من طلبك.',
  start: 'ابدأ',
  applicationApprovedVisitDashboard: 'عرض لوحة التحكم',
  address: 'أبراج بني ياس، شارع الفلاح - شارع 6 فاطمة بنت مبارك، أبوظبي',
  aed: 'درهم',
  nameValidation: 'هذا الحقل إجباري ويجب أن يحتوي على 5 أحرف على الأقل',
  'form.cancel': 'إلغاء',
};
