import * as func from './functions';

const pageConfig = [
  {
    title: 'Application Returned',
    pageId: 'MPpo95XvcGuwj9RZD0LD-',
    path: '/application-returned',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'MmUR-mvnA6rovTzY_4SpY',
          type: 'notice',
          props: {
            status: 'actionRequired',
            icon: null,
            title: "i18n('ApplicationReturned_ApplicationReturned')",
            tags: '${state.returnedPageTags}',
            content: "i18n('ApplicationReturned_Desc')",
            buttons: [],
            space: {
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'returnedPageTags'],
        },
        {
          componentId: 'ps-QPZiBS5xmTkBgtwrM3',
          type: 'table',
          props: {
            status: '',
            size: 'default',
            rowVerticalAlign: 'top',
            selectable: false,
            editable: false,
            searchable: false,
            headerHidden: true,
            disabledSelectionVisible: false,
            clickable: true,
            isSingleSelect: false,
            columns: '${state.feedbackColumns}',
            items: '${state.feedbackStatements}',
            title: "i18n('ApplicationReturned_Feedback')",
            search: '',
            space: {
              marginTop: '',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'feedbackColumns',
            'feedbackStatements',
          ],
        },
        {
          componentId: 'R8MBFWayUdVICoeUuNxHk',
          type: 'text',
          props: {
            variant: 'h3',
            content: "i18n('ApplicationReturned_DocumentUpload')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'gSMDErSPpZcWgZSyfB0mJ',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('ApplicationReturned_DocumentUploadDesc')",
            displayAsHtml: false,
            space: {
              marginBottom: 'lg',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'DGkgX_XTnTijlkszfD3ui',
          type: 'grid',
          props: {
            columns: 2,
            flexColumns: {
              xl: 2,
              lg: 2,
              md: 1,
              sm: 1,
            },
            space: {
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'P209a3TJbl_fjgYvLKcV0',
              type: 'fileUpload',
              props: {
                id: '',
                tabIndex: 0,
                multiple: true,
                validateStatus: '',
                validationMessage: '',
                help: "i18n('UploadDocuments_FileType')",
                disabled: false,
                label: '',
                accept: [],
                files: '${state.files}',
                removeAriaLabel: 'returned-file-remove-button',
                uploadAriaLabel: 'returned-file-upload',
                removeAcceptForIOS: false,
                i18n: '',
                maxSize: 20971520,
                onChange: func.call_f1_onChange,
                onRemove: func.call_f2_onRemove,
                classNames: 'returned-file-upload',
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: ['i18n', 'locale', 'actions', 'files', 'actions'],
            },
          ],
        },
        {
          componentId: 'hWilmI2JeC0xIyBkkQqDw',
          type: 'text',
          props: {
            variant: 'h5',
            content: "i18n('ApplicationReturned_PleaseNote')",
            displayAsHtml: false,
            space: {
              marginTop: '',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'rscHQPoB96yAcfupJ08_Q',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('ApplicationReturned_PleaseNoteDesc')",
            displayAsHtml: false,
            space: {
              marginBottom: 'lg',
              marginRight: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'TnVOCuEqLu_z9FtY07Aly',
          type: 'symbol',
          props: {
            symbol: '_fKRatH62UIjfyCmEg4_8',
            space: {
              marginBottom: 'lg',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'TD0L1-8sYHS57y7Ee7fOx',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: '',
              marginBottom: 'lg',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'aiLOhvPX-Z12V0_WoCGC0',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('ApplicationReturned_ViewQuotationsList')",
                type: 'button',
                uiType: 'secondary',
                disabled: false,
                'aria-label': 'button-view-quotation-list',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                applyAutoWidth: false,
                classNames: 'button-view-quotation-list',
                name: 'button-view-quotation-list',
                onClick: func.f3_onClick,
                space: {
                  marginRight: 'sm',
                  marginBottom: 'md',
                },
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'bpm',
                'businessKey',
                'instanceId',
                'actions',
              ],
            },
            {
              componentId: 'EmYTiPuXI3IcnvxJG1YRy',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_Next')",
                type: 'button',
                uiType: 'primary',
                disabled: '${state.returnedSubmitDisabled}',
                'aria-label': 'adv-returned-submit',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                applyAutoWidth: false,
                name: 'adv-returned-submit',
                classNames: 'adv-returned-submit',
                onClick: func.f4_onClick,
                space: {
                  marginLeft: 'sm',
                  marginBottom: 'md',
                },
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'fetch',
                'bpm',
                'files',
                'businessKey',
                'instanceId',
                'returnedSubmitDisabled',
                'actions',
              ],
            },
          ],
        },
      ],
      symbols: [
        {
          id: 'eauqjPZrppIH9ngzoQH_1',
          name: 'hero',
          definitions: [
            {
              componentId: 'L0vGbvPcFSBE2WAv2Fh7e',
              type: 'hero',
              props: {
                backgroundImage:
                  'https://journeys-stg.tamm.abudhabi/journeys/journey-template/images/hero.jpg',
                backgroundBase64Extension: '',
                internal: true,
                aspectOfLifeType: '',
                breadcrumbs: [
                  {
                    label: "i18n('bc_home')",
                    link: '/',
                  },
                  {
                    id: 'kd4lrtqy',
                    label: "i18n('bc_businessInAbuDhabi')",
                  },
                  {
                    id: 'kd4ltcaj',
                    label: "i18n('bc_registerYourBusiness')",
                  },
                  {
                    id: 'kd4ltg37',
                    label: "i18n('bc_industrialLicences')",
                  },
                ],
                subTitle: '',
                title: "i18n('Global_Title')",
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
        {
          id: 'Tvqi6M5rKJu4JAS3soD9-',
          name: 'Sidebar',
          definitions: [
            {
              componentId: 'yELNRmPQ0-BAvQuT6M0L2',
              type: 'stepTracker',
              props: {
                title: "i18n('ServiceCard_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: 'EGdDKE5QVU6ElyGm7BnMR',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: 'Relevant entity',
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address:
                      'Baniyas Towers, Al Falah Street - Fatima bint Mubarak St 6, Abu Dhabi',
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: false,
                space: {
                  marginTop: 'xl',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
            {
              columnIndex: 0,
              componentId: 'da0TyuQFwqVVGZjOAC_LI',
              type: 'relatedJourneyCard',
              props: {
                aspectOfLifeType: 'business-management',
                icon: null,
                description:
                  'The Manage Your Business journey contains a consolidated dashboard for business owners and representatives to view and...',
                label: 'Manage your business',
                title: 'Related journey',
                space: {
                  marginTop: 'lg',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
          ],
        },
        {
          id: '_fKRatH62UIjfyCmEg4_8',
          name: 'underline',
          definitions: [
            {
              componentId: 's2RFkM-KPxq4WlNEofGH-',
              type: 'text',
              props: {
                variant: 'p',
                content: '<p></p>\n',
                displayAsHtml: true,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    state: {
      mapState: [
        'user',
        'loggedIn',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'returnedPageTags',
        'feedbackColumns',
        'feedbackStatements',
        'files',
        'businessKey',
        'instanceId',
        'returnedSubmitDisabled',
      ],
      mapDispatch: [
        'feedbackStatements',
        'loading',
        'files',
        'returnedSubmitDisabled',
      ],
    },
    init: func.init,
    onPageInit: func.onPageInit,
    fromProcessState: {
      processName: 'workbench',
      variables: ['applicationStatus', 'capId', 'licenseNumber'],
    },
    requires: null,
  },
];

export default pageConfig;
