import * as func from './functions';

const pageConfig = [
  {
    title: 'Select Licence',
    pageId: 'xBgMboYiK3jAIXPp2_G2Q',
    expanded: true,
    path: '/select-licence',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'YJmRrXd-wR5ofEwXUpdiZ',
          type: 'text',
          props: {
            variant: 'h3',
            content: "i18n('SelectLicence_Title')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'eUhKYzcNS-uySViEyCAHX',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('SelectLicence_Desc')",
            displayAsHtml: false,
            space: {
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'quNodOaNmaXQ6KA3X6mk5',
          type: 'table',
          props: {
            size: 'default',
            selectable: true,
            clickable: false,
            columns: '${state.licenceListTableColumns}',
            items: '${state.paginatedLicenceList}',
            title: "i18n('SelectLicence_MyLicencesTable')",
            isSingleSelect: true,
            space: {
              marginTop: '',
              marginBottom: 'xl',
            },
            onSelectionChange: func.call_f1_onSelectionChange,
            searchable: true,
            total: '${state.filteredLicenceListLength}',
            currPage: '${state.licenceListCurrentPage}',
            pageSize: 10,
            onSearch: func.call_f2_onSearch,
            onPageResize: func.f3_onPageResize,
            search: '${state.licenceSearchValue}',
            onClick: func.f4_onClick,
            onPageTurn: func.call_f5_onPageTurn,
            editable: false,
            visible: func.f6_visible,
            status: '${state.fetchingLicencesStatus}',
            selectedItems: '${state.selectedLicencesArr}',
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'analytics',
            'licenceSearchValue',
            'licenceListCurrentPage',
            'licenceList',
            'fetchingLicencesStatus',
            'licenceListTableColumns',
            'paginatedLicenceList',
            'filteredLicenceListLength',
            'selectedLicencesArr',
            'actions',
          ],
        },
        {
          componentId: 'mgY9PvZJHb_j0XiGiarhT',
          type: 'table',
          props: {
            size: 'default',
            selectable: false,
            clickable: false,
            columns: [
              {
                id: 'field-1-kck8qaqh',
                type: '',
                title: 'Field 1',
                renderType: 'default',
              },
            ],
            items: [
              {
                _id: 29,
                'field-1-kck8qaqh': "i18n('SelectLicence_NoLicence')",
              },
            ],
            title: "i18n('SelectLicence_MyLicencesTable')",
            isSingleSelect: true,
            space: {
              marginTop: '',
              marginBottom: 'xl',
            },
            onSelectionChange: func.call_f7_onSelectionChange,
            searchable: false,
            total: '${state.filteredLicenceList}',
            currPage: '${state.licenceListCurrentPage}',
            pageSize: 10,
            onSearch: func.call_f8_onSearch,
            onPageResize: func.f9_onPageResize,
            search: '${state.licenceSearchValue}',
            onClick: func.f10_onClick,
            onPageTurn: func.f11_onPageTurn,
            editable: false,
            pageResizeOptions: '${state.tablePageResizeOptions}',
            filterable: false,
            visible: func.f12_visible,
            headerHidden: true,
            status: '',
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'analytics',
            'licenceList',
            'fetchingLicencesStatus',
            'filteredLicenceList',
            'licenceListCurrentPage',
            'licenceSearchValue',
            'tablePageResizeOptions',
            'actions',
          ],
        },
        {
          componentId: 'qJk9sWvDIE2nXb3nTpQ7p',
          type: 'symbol',
          props: {
            symbol: '3hUcXdivV2rAoRRsJ3pd8',
            space: {
              marginTop: '',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'T48XkizO9-U2TT2hLphSx',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: '',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'o2_6gOugUpI0vrxPxTqBQ',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('next')",
                type: 'button',
                uiType: 'primary',
                disabled: '${state.isSelectLicenceNextButtonDisabled}',
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: 'md',
                  marginLeft: '',
                },
                onClick: func.f13_onClick,
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'history',
                'licenceNumber',
                'isSelectLicenceNextButtonDisabled',
              ],
            },
            {
              componentId: 'pZzoo9_FKr66UUFL71wWv',
              type: 'button',
              props: {
                locale: 'en',
                label: 'Cancel',
                type: 'button',
                uiType: 'text-link',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: true,
                onClick: func.f14_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
          ],
        },
      ],
      symbols: [
        {
          id: 'eauqjPZrppIH9ngzoQH_1',
          name: 'hero',
          definitions: [
            {
              componentId: 'L0vGbvPcFSBE2WAv2Fh7e',
              type: 'hero',
              props: {
                backgroundImage:
                  'https://journeys-stg.tamm.abudhabi/journeys/journey-template/images/hero.jpg',
                backgroundBase64Extension: '',
                internal: true,
                aspectOfLifeType: '',
                breadcrumbs: [
                  {
                    label: "i18n('bc_home')",
                    link: '/',
                  },
                  {
                    id: 'kd4lrtqy',
                    label: "i18n('bc_businessInAbuDhabi')",
                  },
                  {
                    id: 'kd4ltcaj',
                    label: "i18n('bc_registerYourBusiness')",
                  },
                  {
                    id: 'kd4ltg37',
                    label: "i18n('bc_industrialLicences')",
                  },
                ],
                subTitle: '',
                title: "i18n('Global_Title')",
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
        {
          id: 'Tvqi6M5rKJu4JAS3soD9-',
          name: 'Sidebar',
          definitions: [
            {
              componentId: 'yELNRmPQ0-BAvQuT6M0L2',
              type: 'stepTracker',
              props: {
                title: "i18n('ServiceCard_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: 'EGdDKE5QVU6ElyGm7BnMR',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: 'Relevant entity',
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address:
                      'Baniyas Towers, Al Falah Street - Fatima bint Mubarak St 6, Abu Dhabi',
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: false,
                space: {
                  marginTop: 'xl',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
            {
              columnIndex: 0,
              componentId: 'da0TyuQFwqVVGZjOAC_LI',
              type: 'relatedJourneyCard',
              props: {
                aspectOfLifeType: 'business-management',
                icon: null,
                description:
                  'The Manage Your Business journey contains a consolidated dashboard for business owners and representatives to view and...',
                label: 'Manage your business',
                title: 'Related journey',
                space: {
                  marginTop: 'lg',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
          ],
        },
        {
          id: '3hUcXdivV2rAoRRsJ3pd8',
          name: 'link license message',
          definitions: [
            {
              componentId: 'r5LTPsD9K8JKnQbmGYvly',
              type: 'text',
              props: {
                variant: 'h5',
                content: "i18n('ApplicationReturned_PleaseNote')",
                displayAsHtml: false,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
            {
              componentId: 'tnY8J2YguS69fBFdYVYbI',
              type: 'text',
              props: {
                variant: 'p',
                content: "<p>i18n('pleaseNoteText')</p>\n",
                displayAsHtml: true,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'licenceSearchValue',
        'licenceListCurrentPage',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'licenceList',
        'fetchingLicencesStatus',
        'licenceListTableColumns',
        'paginatedLicenceList',
        'filteredLicenceListLength',
        'selectedLicencesArr',
        'filteredLicenceList',
        'tablePageResizeOptions',
        'licenceNumber',
        'isSelectLicenceNextButtonDisabled',
      ],
      mapDispatch: [
        'showSidebar',
        'steps',
        'currentStepIndex',
        'currentSubStepIndex',
        'expandedStepIndexes',
        'fetchingLicencesStatus',
        'licenceList',
        'filteredLicenceList',
        'filteredLicenceListLength',
        'paginatedLicenceList',
        'selectedLicencesArr',
        'licenceNumber',
        'licenceNoError',
        'isSelectLicenceNextButtonDisabled',
        'licenceSearchValue',
        'licenceListCurrentPage',
      ],
    },
    init: func.init,
  },
];

export default pageConfig;
