import * as func from './functions';

const pageConfig = [
  {
    title: 'Application Success',
    pageId: 'nJdZwtxr9ceIE746QXyL_',
    expanded: true,
    path: '/application-success',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'VvUXLlTUjNLLGlG-s1IcB',
          type: 'notice',
          props: {
            status: 'success',
            icon: null,
            title: "i18n('applicationApprovedTitle')",
            tags: '${state.paymentTag}',
            content: '${state.applicationIssuedDescription}',
            buttons: [],
            classNames: '',
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'paymentTag',
            'applicationIssuedDescription',
          ],
        },
        {
          componentId: 'sErpagxnCqt5ULRHoaKSL',
          type: 'alert',
          props: {
            status: 'error',
            message: '${state.camundaMessage}',
            onClose: null,
            space: {
              marginBottom: '',
              marginTop: 'md',
            },
            visible: func.f1_visible,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'camundaMessage'],
        },
        {
          componentId: 'Ir_6JRtYzfkgN_PHkn3mY',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: 'lg',
              marginBottom: 'xl',
            },
            classNames: 'button-wrapper',
          },
          layout: 'base',
          children: [
            {
              componentId: 'b12lMDSHylyL5K1BixqAb',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('applicationApprovedDownloadCertificate')",
                type: 'button',
                uiType: 'primary',
                disabled: false,
                'aria-label': "i18n('applicationApprovedDownloadCertificate')",
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                onClick: func.f2_onClick,
              },
              columnIndex: 1,
              layout: 'base',
              parentComponentId: 'kAAzK8MrdKtX-phVmKE29',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'fetch',
                'instanceId',
                'actions',
              ],
            },
            {
              componentId: 'JHipL8HImLMAJ_EZCcNb9',
              type: 'button',
              props: {
                label: "i18n('applicationApprovedDownloadReceipt')",
                type: 'button',
                uiType: 'secondary',
                disabled: false,
                'aria-label': "i18n('applicationApprovedDownloadReceipt')",
                size: 'default',
                icon: null,
                alignIcon: 'start',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                onClick: func.f3_onClick,
                space: {
                  marginRight: 'md',
                  marginLeft: 'md',
                },
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'kAAzK8MrdKtX-phVmKE29',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'fetch',
                'instanceId',
                'actions',
              ],
            },
            {
              componentId: 'csSbqsGdORIXTrKN3C4-u',
              type: 'button',
              props: {
                label: "i18n('applicationApprovedVisitDashboard')",
                type: 'button',
                uiType: 'secondary',
                disabled: false,
                'aria-label': "i18n('applicationApprovedDownloadReceipt')",
                size: 'default',
                icon: null,
                alignIcon: 'start',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                onClick: func.f4_onClick,
                space: {
                  marginRight: '',
                  marginLeft: '',
                },
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'kAAzK8MrdKtX-phVmKE29',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
        {
          componentId: 'XzBGmIYV-PIKgEfP71wk6',
          type: 'customerSatisfaction',
          props: {
            i18n: '',
            status: 'idle',
            emotion: '',
            onSubmit: '',
            rates: [
              {
                value: 0,
                starsCount: 5,
                min: 1,
                max: 5,
                step: 5,
                id: 'kcd4pffz',
              },
            ],
            withComment: true,
            space: {
              marginTop: 'lg',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
      ],
      symbols: [
        {
          id: 'LRdpV5hJYYHXEeQXvW572',
          name: 'Sidebar',
          definitions: [
            {
              componentId: 'x02R_vTEPQV7EuW80B8-y',
              type: 'stepTracker',
              props: {
                title: "i18n('process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSideBar;"}',
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'showSideBar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: 'bx_ewe29IC5HCtaVmJhKJ',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: "i18n('relevantEntity')",
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address: "i18n('address')",
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: false,
                space: {
                  marginTop: 'xl',
                },
                visible: '{"code":"  return props.state.showSideBar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSideBar'],
            },
          ],
        },
        {
          id: 'SpZNRSS1hcBXpPT30yok2',
          name: 'Header',
          definitions: [
            {
              componentId: 'ZubPbXDHOtVDemU26pYRi',
              type: 'flexbox',
              props: {
                flexWrap: true,
                flexDirection: 'column',
                justifyContent: 'initial',
                alignItems: 'initial',
                alignContent: 'initial',
                classNames: 'container',
              },
              layout: 'base',
              children: [
                {
                  componentId: '7vJvGWTue3wJJTCS3mfAX',
                  type: 'breadcrumb',
                  props: {
                    space: {
                      marginBottom: 'md',
                      marginTop: 'lg',
                    },
                    items: [
                      {
                        id: 'kdmsxtik',
                        label: "i18n('bc_home')",
                        linkTarget: '_self',
                        link: '/',
                      },
                      {
                        id: 'kdmsyjm9',
                        label: "i18n('bc_digitalServices')",
                        link: 'https://www.tamm.abudhabi/tamm-centers-services',
                        linkTarget: '_self',
                      },
                      {
                        id: 'kdmszcbw',
                        label: "i18n('bc_DED')",
                        link:
                          'https://www.tamm.abudhabi/tamm-centers-services/department-of-economic-development',
                        linkTarget: '_self',
                      },
                    ],
                  },
                  parentComponentId: 'no_parent',
                  sharedProps: ['i18n', 'locale'],
                },
                {
                  componentId: '4wTDq9dCLSvn6yueeb1LJ',
                  type: 'text',
                  props: {
                    variant: 'h1',
                    content: "i18n('serviceCardServicename')",
                    displayAsHtml: false,
                  },
                  layout: 'base',
                  parentComponentId: 'no_parent',
                  sharedProps: ['i18n', 'locale'],
                },
              ],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'businessKey',
        'instanceId',
        'licenceNumber',
        'showSideBar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'paymentTag',
        'applicationIssuedDescription',
        'camundaMessage',
      ],
      mapDispatch: [
        'showSideBar',
        'loading',
        'currentStepIndex',
        'currentSubStepIndex',
        'expandedStepIndexes',
        'steps',
        'camundaMessage',
        'paymentTag',
        'applicationIssuedDescription',
        'apTransactionNo',
        'capId',
        'instanceId',
      ],
    },
    init: func.init,
    onPageInit: func.onPageInit,
    fromProcessState: {
      processName: 'workbench',
      variables: ['apTransactionNumber', 'submitDate', 'capId', 'instanceId'],
    },
  },
];

export default pageConfig;
