import * as func from './functions';

const pageConfig = [
  {
    title: 'Entity Details',
    pageId: 'o8XhC2ui1xBWpvdFfveuk',
    path: '/entity-details',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'p5Qh8S2ojozir8maE3PHT',
          type: 'text',
          props: {
            variant: 'h3',
            content: "i18n('SelectEntity_SelectCertifiedEntities')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'L3pBKmsM78CzsPl0KzSue',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('SelectEntity_Desc')",
            displayAsHtml: false,
            space: {
              marginBottom: 'lg',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'K64yCo9bWAspnerRIepjN',
          type: 'grid',
          props: {
            columns: 1,
            flexColumns: {
              xl: 1,
              lg: 1,
              md: 1,
              sm: 1,
            },
            space: {
              marginTop: '',
              marginBottom: 'lg',
              paddingTop: '',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: '6FHdkNF0Z-7WQpux5OG-g',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity1')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f1_onClick,
                checked: '${state.ardentSelected}',
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'ardentSelected',
                'actions',
              ],
            },
            {
              componentId: 'AfLImCzqhPexLwRE5mo3R',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity2')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f2_onClick,
                checked: '${state.bakertillySelected}',
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'B43RH2FfDzrDRFMsGjdF0',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'bakertillySelected',
                'actions',
              ],
            },
            {
              componentId: '4xCDmMnzSto8jRSjRIr-J',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity3')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  paddingBottom: '',
                  marginBottom: 'sm',
                },
                onClick: func.call_f3_onClick,
                checked: '${state.deloitteSelected}',
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'B43RH2FfDzrDRFMsGjdF0',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'deloitteSelected',
                'actions',
              ],
            },
            {
              componentId: 'cwSvcSOKuUrBUV8qa8msu',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity4')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f4_onClick,
                checked: '${state.eySelected}',
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'eySelected',
                'actions',
              ],
            },
            {
              componentId: 'xkcDYJ-tpFQm_3BwGHWTd',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity5')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f5_onClick,
                checked: '${state.provitiSelected}',
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'B43RH2FfDzrDRFMsGjdF0',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'provitiSelected',
                'actions',
              ],
            },
            {
              componentId: '1dEhTLS7uX6wOcyUM3qqd',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity6')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f6_onClick,
                checked: '${state.mazarsSelected}',
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'B43RH2FfDzrDRFMsGjdF0',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'mazarsSelected',
                'actions',
              ],
            },
            {
              componentId: 'z5kIkEtHoUSDDYgSoUG-z',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity7')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f7_onClick,
                checked: '${state.croweSelected}',
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'croweSelected',
                'actions',
              ],
            },
            {
              componentId: '4M5FEuF8RvODCwOYxmVv8',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity8')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f8_onClick,
                checked: '${state.mbcSelected}',
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'B43RH2FfDzrDRFMsGjdF0',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'mbcSelected',
                'actions',
              ],
            },
            {
              componentId: 'sEliTn7ldN1v_QDKXTFwW',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity9')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f9_onClick,
                checked: '${state.pkfSelected}',
              },
              columnIndex: 0,
              layout: 'base',
              parentComponentId: 'B43RH2FfDzrDRFMsGjdF0',
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'pkfSelected',
                'actions',
              ],
            },
            {
              componentId: 'bBY5Tf3FWl7eMlt5waRYS',
              type: 'checkbox',
              props: {
                name: '',
                id: '',
                tabIndex: 0,
                autoFocus: false,
                readOnly: false,
                label: "i18n('SelectEntity_Entity10')",
                disabled: false,
                uiType: 'bold',
                description: '',
                validateStatus: '',
                meta: '',
                space: {
                  marginBottom: 'sm',
                },
                onClick: func.call_f10_onClick,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'selectedEntities',
                'actions',
              ],
            },
          ],
        },
        {
          componentId: 'Vhl5PFELsi2Hbwjr4YiHR',
          type: 'symbol',
          props: {
            symbol: 'zq9vkdjX1HVpzHE4Jcn5k',
            space: {
              marginBottom: 'xl',
            },
          },
          sharedProps: ['i18n', 'locale', 'classNames_decbcfcfbe'],
        },
        {
          componentId: 'z7AX3MfqbCO5-y9Ijgwyz',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: '',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: '-213LVyTKTPNVDdNFg7eU',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_Back')",
                type: 'button',
                uiType: 'secondary',
                disabled: false,
                'aria-label': 'choose-activities-back-btn',
                size: 'default',
                icon: null,
                alignIcon: 'start',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: 'md',
                },
                name: 'choose-activities-back-btn',
                classNames: 'choose-activities-back-btn',
                onClick: func.f11_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
            {
              componentId: 'KPEBYp4vPNAxJcjH394IK',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_Next')",
                type: 'button',
                uiType: 'primary',
                disabled: '${state.isEntityNotSelected}',
                'aria-label': 'choose-activities-next-btn',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: 'sm',
                  marginLeft: 'sm',
                },
                onClick: func.f12_onClick,
                classNames: 'choose-activities-next-btn',
                name: 'choose-activities-next-btn',
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'history',
                'actions',
                'selectedEntities',
                'isEntityNotSelected',
                'actions',
              ],
            },
            {
              componentId: 'H-Sb3d7ypjohSijObiOuH',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_Cancel')",
                type: 'button',
                uiType: 'text-link',
                disabled: false,
                'aria-label': 'choose-activities-cancel-btn',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: true,
                name: 'choose-activities-cancel-btn',
                classNames: 'choose-activities-cancel-btn',
                onClick: func.f13_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
          ],
        },
      ],
      symbols: [
        {
          id: 'eauqjPZrppIH9ngzoQH_1',
          name: 'hero',
          definitions: [
            {
              componentId: 'L0vGbvPcFSBE2WAv2Fh7e',
              type: 'hero',
              props: {
                backgroundImage:
                  'https://journeys-stg.tamm.abudhabi/journeys/journey-template/images/hero.jpg',
                backgroundBase64Extension: '',
                internal: true,
                aspectOfLifeType: '',
                breadcrumbs: [
                  {
                    label: "i18n('bc_home')",
                    link: '/',
                  },
                  {
                    id: 'kd4lrtqy',
                    label: "i18n('bc_businessInAbuDhabi')",
                  },
                  {
                    id: 'kd4ltcaj',
                    label: "i18n('bc_registerYourBusiness')",
                  },
                  {
                    id: 'kd4ltg37',
                    label: "i18n('bc_industrialLicences')",
                  },
                ],
                subTitle: '',
                title: "i18n('Global_Title')",
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
        {
          id: 'Tvqi6M5rKJu4JAS3soD9-',
          name: 'Sidebar',
          definitions: [
            {
              componentId: 'yELNRmPQ0-BAvQuT6M0L2',
              type: 'stepTracker',
              props: {
                title: "i18n('ServiceCard_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: 'EGdDKE5QVU6ElyGm7BnMR',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: 'Relevant entity',
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address:
                      'Baniyas Towers, Al Falah Street - Fatima bint Mubarak St 6, Abu Dhabi',
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: false,
                space: {
                  marginTop: 'xl',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
            {
              columnIndex: 0,
              componentId: 'da0TyuQFwqVVGZjOAC_LI',
              type: 'relatedJourneyCard',
              props: {
                aspectOfLifeType: 'business-management',
                icon: null,
                description:
                  'The Manage Your Business journey contains a consolidated dashboard for business owners and representatives to view and...',
                label: 'Manage your business',
                title: 'Related journey',
                space: {
                  marginTop: 'lg',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
          ],
        },
        {
          id: 'zq9vkdjX1HVpzHE4Jcn5k',
          name: 'AutoSaved',
          definitions: [
            {
              componentId: 'Wg41huxRP35WX0AzJK3FJ',
              type: 'text',
              props: {
                variant: 'p',
                content: '<p>Your application is being autosaved</p>\n',
                displayAsHtml: true,
                space: {
                  marginTop: '',
                  marginBottom: '',
                },
                classNames: '${state.classNames_decbcfcfbe}',
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'classNames_decbcfcfbe'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'classNames_decbcfcfbe',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'selectedEntities',
        'ardentSelected',
        'bakertillySelected',
        'deloitteSelected',
        'eySelected',
        'provitiSelected',
        'mazarsSelected',
        'croweSelected',
        'mbcSelected',
        'pkfSelected',
        'isEntityNotSelected',
      ],
      mapDispatch: [
        'steps',
        'currentSubStepIndex',
        'isEntityNotSelected',
        'selectedEntities',
        'ardentSelected',
        'bakertillySelected',
        'deloitteSelected',
        'eySelected',
        'provitiSelected',
        'mazarsSelected',
        'croweSelected',
        'mbcSelected',
        'pkfSelected',
        'tagSelected',
        'entityPayload',
      ],
    },
    init: func.init,
  },
];

export default pageConfig;
