import * as func from './functions';

import getMapConfig from '../../sharedFunctions/getMapConfig';

const pageConfig = [
  {
    title: 'enter company details',
    pageId: 'uUjZe0JQVnGLJiQ1s4c-o',
    expanded: true,
    path: '/enter-company-details',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'XOWGbTJF-C9lUzFXxrWjo',
          type: 'text',
          props: {
            variant: 'h4',
            content: "i18n('Global_EnterCompanyDetailsStep')",
            displayAsHtml: false,
            space: {
              marginTop: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'y2SJRnNYC7BOFFJjMQDAH',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('CompanyDetails_Description')",
            space: {
              marginBottom: '',
              paddingBottom: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'cHNGwLAhG16GZ6g2auzUV',
          type: 'radioGroup',
          props: {
            i18n: '',
            children: null,
            disabled: false,
            labelStyle: 'default',
            uiType: 'default',
            items: '${state.typesOfCompanyDetails}',
            defaultValue: '${state.companyDetailsType}',
            align: 'horizontal',
            groupLabel: '',
            expanded: false,
            allowedNotExpandedLimit: 5,
            showMoreLabels: [],
            onChange: func.call_f1_onChange,
            space: {
              marginBottom: 'md',
            },
          },
          layout: 'base',
          columnIndex: 0,
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'typesOfCompanyDetails',
            'companyDetailsType',
            'actions',
          ],
        },
        {
          componentId: 'w5cPRRtdHWpJv1bNzDIqF',
          type: 'grid',
          props: {
            columns: 2,
            flexColumns: {
              xl: 2,
              lg: 2,
              md: 2,
              sm: 2,
            },
            space: {
              marginTop: '',
              marginBottom: '',
              paddingTop: '',
              paddingBottom: '',
            },
            visible: func.f2_visible,
          },
          layout: 'base',
          children: [
            {
              componentId: 'a3NhYCEXNdIBX6Lnah_3W',
              type: 'input',
              props: {
                label: "i18n('CompanyDetails_TawtheeqInput')",
                tabIndex: 0,
                value: '${state.tawtheeqNumber}',
                defaultValue: '${state.tawtheeqNumber}',
                'aria-label': 'input',
                validateStatus: '${state.tawtheeqNumberValidateStatus}',
                disabled: false,
                readonly: false,
                help: '${state.tawtheeqNumberHelp}',
                placeholder: "i18n('CompanyDetails_Write')",
                size: 'default',
                textDirection: 'ltr',
                name: 'tawtheeqNumberInput',
                type: 'text',
                space: {
                  marginBottom: 'md',
                },
                onChange: func.call_f3_onChange,
                visible: func.f4_visible,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'companyDetailsType',
                'tawtheeqNumber',
                'tawtheeqNumberValidateStatus',
                'tawtheeqNumberHelp',
                'actions',
              ],
            },
            {
              componentId: 'FZsd5cVa7J2ViBiKfLWYF',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('CompanyDetails_CheckButton')",
                type: 'button',
                uiType: 'secondary',
                disabled: '${state.checkTawtheeqNumberdisabled}',
                'aria-label': 'button',
                size: 'medium',
                icon: null,
                alignIcon: 'end',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginTop: 'md',
                  marginBottom: 'md',
                },
                onClick: func.call_f5_onClick,
                visible: func.f6_visible,
                name: 'checkTawtheeqNumberButton',
              },
              layout: 'base',
              columnIndex: 1,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'fetch',
                'tawtheeqNumber',
                'companyDetailsType',
                'checkTawtheeqNumberdisabled',
                'actions',
              ],
            },
          ],
        },
        {
          componentId: 'yB5U1MoSpS-hfNHiyjkcO',
          type: 'grid',
          props: {
            columns: 2,
            flexColumns: {
              xl: 2,
              lg: 2,
              md: 2,
              sm: 2,
            },
            space: {
              marginTop: '',
              marginBottom: '',
              paddingTop: '',
              paddingBottom: '',
            },
            visible: func.f7_visible,
          },
          layout: 'base',
          children: [
            {
              componentId: 'hbmFpYTAvEVl4kGd9IOp3',
              type: 'input',
              props: {
                label: "i18n('Global_LeaseAgreementNo')",
                tabIndex: 0,
                value: '${state.leaseAgreementNumber}',
                defaultValue: '${state.leaseAgreementNumber}',
                'aria-label': 'input',
                validateStatus: '${state.leaseAgreementNumberValidateStatus}',
                disabled: false,
                readonly: false,
                help: '${state.leaseAgreementNumberHelp}',
                placeholder: "i18n('CompanyDetails_Write')",
                size: 'default',
                textDirection: 'ltr',
                name: 'leaseAgreementNumberInput',
                type: 'text',
                space: {
                  marginBottom: 'md',
                },
                onChange: func.call_f8_onChange,
                visible: func.f9_visible,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'companyDetailsType',
                'leaseAgreementNumber',
                'leaseAgreementNumberValidateStatus',
                'leaseAgreementNumberHelp',
                'actions',
              ],
            },
            {
              componentId: 'hO7KI3AhvrPRjEgNofwPi',
              type: 'input',
              props: {
                label: "i18n('Global_LeaseAmount')",
                tabIndex: 0,
                value: '${state.leaseAgreementAmount}',
                defaultValue: '${state.leaseAgreementAmount}',
                'aria-label': 'input',
                validateStatus: '${state.leaseAgreementAmountValidateStatus}',
                disabled: false,
                readonly: false,
                help: '${state.leaseAgreementAmountHelp}',
                placeholder: "i18n('CompanyDetails_Write')",
                size: 'default',
                textDirection: 'ltr',
                name: 'leaseAgreementAmountInput',
                type: 'text',
                space: {
                  marginBottom: 'md',
                },
                onChange: func.call_f10_onChange,
                visible: func.f11_visible,
              },
              layout: 'base',
              columnIndex: 1,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'companyDetailsType',
                'leaseAgreementAmount',
                'leaseAgreementAmountValidateStatus',
                'leaseAgreementAmountHelp',
                'actions',
              ],
            },
            {
              componentId: 'NG6-irY2gTB-GTwdTSTOn',
              type: 'rangePicker',
              props: {
                tabIndex: 0,
                disabled: false,
                visible: func.f12_visible,
                onChange: func.call_f13_onChange,
                value: '${state.leaseAgreementDate}',
                defaultValue: '${state.leaseAgreementDate}',
                help: '${state.leaseAgreementDateHelp}',
                validateStatus: '${state.leaseAgreementDateValidateStatus}',
                classNames: 'leaseAgreementDate',
                name: 'leaseAgreementDate',
                placeholder: "i18n('CompanyDetails_SelectDates')",
                label: "i18n('Global_LeaseDateRange')",
                rangeSelection: true,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'companyDetailsType',
                'leaseAgreementDate',
                'leaseAgreementDateHelp',
                'leaseAgreementDateValidateStatus',
                'actions',
              ],
            },
          ],
        },
        {
          componentId: '7303LQ7ftidP4zIv7qnq_',
          type: 'text',
          props: {
            variant: 'p',
            content: "<p>i18n('Global_MapDesc')</p>",
            displayAsHtml: '${state.displayAsHtml_fbecddafbc}',
            space: {
              marginBottom: '',
              paddingBottom: '',
              marginTop: 'lg',
            },
            visible: func.f14_visible,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'displayAsHtml_fbecddafbc'],
        },
        {
          componentId: 'YM2sk6o8Jz33J8Dhl8WOb',
          type: 'map',
          props: {
            className: '',
            locale: 'en',
            config: getMapConfig(),
            featureDetailsRenderer: null,
            i18n: '',
            visible: func.f15_visible,
            onMapClick: func.call_f16_onMapClick,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'actions', 'actions'],
        },
        {
          componentId: 'w_O-I4rHElkdAgT0lYNzU',
          type: 'text',
          props: {
            variant: 'p',
            content: '${state.latitudeHelp}',
            displayAsHtml: false,
            visible: func.f17_visible,
            classNames: 'mapCoordinatesHelp',
            space: {
              marginTop: 'md',
            },
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'longitudeValidateStatus',
            'latitudeValidateStatus',
            'latitudeHelp',
          ],
        },
        {
          componentId: 'ynj2l6Z8b5gyvgib5I2o1',
          type: 'text',
          props: {
            variant: 'h5',
            content: "i18n('CompanyDetails_ContactInfoTitle')",
            displayAsHtml: false,
            space: {
              marginTop: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: '310TFmFXwZsIOtBP_nGif',
          type: 'text',
          props: {
            variant: 'p',
            content: "<p>i18n('CompanyDetails_ContactInfoDesc')</p>",
            displayAsHtml: '${state.displayAsHtml_fbecddafbc}',
            space: {
              paddingBottom: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'displayAsHtml_fbecddafbc'],
        },
        {
          componentId: '0fZsVk4AzLTO8IKT_XSQR',
          type: 'checkbox',
          props: {
            name: 'cheTakeContactInfo',
            id: '',
            tabIndex: 0,
            autoFocus: false,
            readOnly: false,
            label: "i18n('CompanyDetails_ContactCheckbox')",
            disabled: false,
            uiType: '',
            description: '',
            validateStatus: '',
            meta: '',
            onChange: func.call_f18_onChange,
            checked: '${state.checkedTakeContactInfo}',
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'fetch',
            'user',
            'checkedTakeContactInfo',
            'actions',
          ],
        },
        {
          componentId: 'ArUTE2iTOalFsmIjBEiHw',
          type: 'grid',
          props: {
            columns: 2,
            flexColumns: {
              xl: 2,
              lg: 2,
              md: 2,
              sm: 2,
            },
            space: {
              marginTop: 'md',
              marginBottom: '',
              paddingTop: '',
              paddingBottom: '',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'Tq9F8EXwThcoeTJMlrlht',
              type: 'input',
              props: {
                label: "i18n('CompanyDetails_NameInput')",
                tabIndex: 0,
                value: '${state.contactInfoName}',
                defaultValue: '',
                'aria-label': 'input',
                validateStatus: '${state.contactInfoNameValidateStatus}',
                disabled: '${state.checkedTakeContactInfo}',
                readonly: false,
                help: '${state.contactInfoNameHelp}',
                placeholder: "i18n('CompanyDetails_Write')",
                size: 'default',
                textDirection: 'ltr',
                name: 'contactInfoName',
                type: 'text',
                space: {
                  marginBottom: 'md',
                },
                onChange: func.call_f19_onChange,
                visible: func.f20_visible,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'contactInfoName',
                'contactInfoNameValidateStatus',
                'checkedTakeContactInfo',
                'contactInfoNameHelp',
                'actions',
              ],
            },
            {
              componentId: '-5geyn5D8qhwH-fMvRcUH',
              type: 'inputTelephone',
              props: {
                i18n: '',
                tabIndex: 0,
                help: '${state.contactInfoPhNoHelp}',
                validateStatus: '${state.contactInfoPhNoValidateStatus}',
                label: "i18n('CompanyDetails_PhoneNumberInput')",
                'aria-label': 'Telephone input',
                disabled: '${state.checkedTakeContactInfo}',
                value: '${state.contactInfoPhNo}',
                code: null,
                countries: [],
                size: 'default',
                defaultValue: {},
                space: {
                  marginBottom: '',
                  paddingBottom: 'lg',
                },
                classNames: '',
                name: 'contactInfoPhNo',
                onSelect: func.call_f21_onSelect,
              },
              layout: 'base',
              columnIndex: 1,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'contactInfoPhNoHelp',
                'contactInfoPhNoValidateStatus',
                'checkedTakeContactInfo',
                'contactInfoPhNo',
                'actions',
              ],
            },
            {
              componentId: 'sJugY0hqFufeAjkBUlQGq',
              type: 'input',
              props: {
                label: "i18n('CompanyDetails_EmailInput')",
                tabIndex: 0,
                value: '${state.contactInfoEmailAddress}',
                defaultValue: '',
                'aria-label': 'input',
                validateStatus:
                  '${state.contactInfoEmailAddressValidateStatus}',
                disabled: '${state.checkedTakeContactInfo}',
                readonly: false,
                help: '${state.contactInfoEmailAddressHelp}',
                placeholder: "i18n('CompanyDetails_Write')",
                size: 'default',
                textDirection: 'ltr',
                name: 'contactInfoEmailAddress',
                type: 'text',
                space: {
                  marginBottom: 'md',
                },
                onChange: func.call_f22_onChange,
                visible: func.f23_visible,
              },
              layout: 'base',
              columnIndex: 0,
              sharedProps: [
                'i18n',
                'locale',
                'actions',
                'contactInfoEmailAddress',
                'contactInfoEmailAddressValidateStatus',
                'checkedTakeContactInfo',
                'contactInfoEmailAddressHelp',
                'actions',
              ],
            },
          ],
        },
        {
          componentId: 'QUYmKz0PpWt3VN87l94Vl',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: 'md',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'eAWOgAqKLMroTDXFjww5V',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_BackButton')",
                type: 'button',
                uiType: 'secondary',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'start',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: 'md',
                },
                name: 'companyDetailsBack',
                onClick: func.f24_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
            {
              componentId: 'vL-O9WBtZFuoIga8vUAO5',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_NextButton')",
                type: 'button',
                uiType: 'primary',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: '',
                },
                onClick: func.call_f25_onClick,
                name: 'companyDetailsSubmit',
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'history',
                'actions',
                'tawtheeqNumber',
                'tawtheeqNumberValidateStatus',
                'leaseAgreementDate',
                'leaseAgreementNumber',
                'leaseAgreementAmount',
                'latitude',
                'longitude',
                'contactInfoName',
                'contactInfoPhNo',
                'contactInfoEmailAddress',
                'companyDetailsType',
                'tawtheeqNumberIsValid',
                'actions',
              ],
            },
            {
              componentId: 'fx4RVYCb0Fc3zxRIaO5GN',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_CancelButton')",
                type: 'button',
                uiType: 'text-link',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: true,
                space: {
                  paddingLeft: 'md',
                  paddingRight: 'md',
                },
                name: 'companyDetailsCancel',
                onClick: func.f26_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
          ],
        },
      ],
      symbols: [
        {
          id: 'u_7BA0xr8Q0oku7QtzxvE',
          name: 'Header',
          definitions: [
            {
              componentId: '0nSNUzm6NEjCkToaBdmCl',
              type: 'alert',
              props: {
                status: '',
                message: '',
                onClose: null,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
            {
              componentId: 'Y78zMYB80jxbXDw2WuI6o',
              type: 'flexbox',
              props: {
                flexWrap: true,
                flexDirection: 'column-reverse',
                justifyContent: 'initial',
                alignItems: 'initial',
                alignContent: 'initial',
                classNames: 'container',
                space: {
                  marginBottom: '',
                  paddingBottom: '',
                },
              },
              layout: 'base',
              children: [
                {
                  componentId: 'uQukKScRci0q9DWO9b324',
                  parentComponentId: 'Y78zMYB80jxbXDw2WuI6o',
                  type: 'text',
                  props: {
                    variant: 'h1',
                    content: "i18n('Global_ServiceName')",
                    displayAsHtml: false,
                    space: {
                      paddingBottom: 'md',
                      marginTop: 'md',
                    },
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
                {
                  componentId: 'iyAIP8maLEkaZwI2t7dUy',
                  type: 'breadcrumb',
                  props: {
                    items: [
                      {
                        label: "i18n('bcrumbsHome')",
                        link: 'https://www.tamm.abudhabi/',
                        linkTarget: '',
                        id: 'kbzqdrrl',
                      },
                      {
                        label: "i18n('bcrumbsBusinessInAbuDhabi')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqe5hx',
                      },
                      {
                        label: "i18n('bcrumbsRegisterYourBusiness')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqeewv',
                      },
                      {
                        label: "i18n('bcrumbsIndustrialLicences')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqel7d',
                      },
                    ],
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
              ],
            },
          ],
        },
        {
          id: 'pOuCbjftw6l5xN5WTMEPb',
          name: 'Sidebar_without_card',
          definitions: [
            {
              componentId: 'yeIBuc-dVj7toDnj_7R81',
              type: 'stepTracker',
              props: {
                title: "i18n('ServicePage_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
                classNames: '',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: '2eXUqMf3xlTH9Dity7T6_',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: "i18n('Relevant_entity')",
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address: "i18n('address')",
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: true,
                space: {
                  marginTop: 'xl',
                  paddingBottom: 'lg',
                },
              },
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    customPath: true,
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'tawtheeqNumber',
        'tawtheeqNumberValidateStatus',
        'leaseAgreementDate',
        'leaseAgreementNumber',
        'leaseAgreementAmount',
        'latitude',
        'longitude',
        'contactInfoName',
        'contactInfoPhNo',
        'contactInfoEmailAddress',
        'companyDetailsType',
        'contactInfoNameHelp',
        'contactInfoNameValidateStatus',
        'contactInfoPhNoHelp',
        'contactInfoPhNoValidateStatus',
        'contactInfoEmailAddressHelp',
        'contactInfoEmailAddressValidateStatus',
        'typesOfCompanyDetails',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'tawtheeqNumberHelp',
        'checkTawtheeqNumberdisabled',
        'leaseAgreementNumberValidateStatus',
        'leaseAgreementNumberHelp',
        'leaseAgreementAmountValidateStatus',
        'leaseAgreementAmountHelp',
        'leaseAgreementDateHelp',
        'leaseAgreementDateValidateStatus',
        'displayAsHtml_fbecddafbc',
        'longitudeValidateStatus',
        'latitudeValidateStatus',
        'latitudeHelp',
        'checkedTakeContactInfo',
        'tawtheeqNumberIsValid',
      ],
      mapDispatch: [
        'tawtheeqNumberValidateStatus',
        'contactInfoEmailAddressValidateStatus',
        'contactInfoPhNoValidateStatus',
        'contactInfoNameValidateStatus',
        'contactInfoEmailAddressHelp',
        'contactInfoPhNoHelp',
        'contactInfoNameHelp',
        'tawtheeqNumberHelp',
        'leaseAgreementDateHelp',
        'leaseAgreementNumberHelp',
        'leaseAgreementAmountHelp',
        'leaseAgreementDateValidateStatus',
        'leaseAgreementNumberValidateStatus',
        'leaseAgreementAmountValidateStatus',
        'latitudeHelp',
        'latitudeValidateStatus',
        'longitudeValidateStatus',
        'typesOfCompanyDetails',
        'companyDetailsType',
        'showSidebar',
        'currentStepIndex',
        'currentSubStepIndex',
        'expandedStepIndexes',
        'steps',
        'tawtheeqNumber',
        'tawtheeqNumberIsValid',
        'checkTawtheeqNumberdisabled',
        'loading',
        'leaseAgreementAmount',
        'leaseAgreementNumber',
        'leaseAgreementDate',
        'locationDetails',
        'latitude',
        'longitude',
        'checkedTakeContactInfo',
        'contactInfoName',
        'contactInfoPhNo',
        'contactInfoEmailAddress',
      ],
    },
    init: func.init,
  },
];

export default pageConfig;
