import * as func from './functions';

const pageConfig = [
  {
    title: 'select licence',
    pageId: '6FQ6nmaEtJ5zLw1IeRxv2',
    expanded: true,
    path: '/select-licence',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'YJmRrXd-wR5ofEwXUpdiZ',
          type: 'text',
          props: {
            variant: 'h2',
            content: "i18n('SelectLicence_Title')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'eUhKYzcNS-uySViEyCAHX',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('SelectLicence_Description')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'OYqxGGl0qYXj498VGuXWL',
          type: 'table',
          props: {
            size: 'default',
            selectable: '${state.myLicenceSelectable}',
            clickable: false,
            columns: '${state.licenceListColumns}',
            items: '${state.licenceListRows}',
            title: "i18n('SelectLicence_MyLicencesTableTitle')",
            isSingleSelect: true,
            space: {
              marginTop: 'md',
            },
            onSelectionChange: func.call_f1_onSelectionChange,
            searchable: '${state.myLicenceSearchable}',
            total: '${state.tableTotalRecords}',
            currPage: '${state.tableCurrPage}',
            pageSize: '${state.tablePageSize}',
            onSearch: func.call_f2_onSearch,
            onPageResize: func.f3_onPageResize,
            search: '${state.licenceSearch}',
            onClick: func.f4_onClick,
            onPageTurn: func.call_f5_onPageTurn,
            editable: false,
            headerHidden: '${state.myLicenceHeaderHidden}',
            status: '',
            classNames: 'myLicenceTable',
            selectedItems: '${state.myLicenceSelectedItems}',
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'analytics',
            'licenceListRows',
            'actualLicenceList',
            'licenceNumber',
            'licenceSearch',
            'myLicenceSelectable',
            'licenceListColumns',
            'myLicenceSearchable',
            'tableTotalRecords',
            'tableCurrPage',
            'tablePageSize',
            'myLicenceHeaderHidden',
            'myLicenceSelectedItems',
            'actions',
          ],
        },
        {
          componentId: '6bOOB2c9gVoEQ_y4gbHL4',
          type: 'text',
          props: {
            variant: 'h5',
            content: "i18n('SelectLicence_NoteTitle')",
            displayAsHtml: false,
            space: {
              marginTop: 'md',
            },
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'GuddDtmjf90EYk4jsTLUM',
          type: 'text',
          props: {
            variant: 'p',
            content:
              "<p>i18n('SelectLicence_NoteDescriptionPart1') <a href=\"/services/business/ded/link-licence\"><u>i18n('SelectLicence_NoteDescriptionPart2')</u></a><u> </u>i18n('SelectLicence_NoteDescriptionPart3')</p>",
            displayAsHtml: true,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'LnSZ1NGSgziOrkZNOzEqI',
          type: 'button',
          props: {
            locale: 'en',
            label: "i18n('SelectLicence_CheckEligibilityButton')",
            type: 'button',
            uiType: 'secondary',
            disabled: '${state.disabled_eligibility}',
            'aria-label': 'button',
            size: 'default',
            icon: null,
            alignIcon: 'end',
            withArrow: false,
            active: false,
            hidden: false,
            iconTooltip: '',
            applyAutoWidth: false,
            onClick: func.call_f6_onClick,
          },
          layout: 'base',
          columnIndex: 0,
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'fetch',
            'licenceNumber',
            'disabled_eligibility',
            'actions',
          ],
        },
        {
          componentId: 'td1j5B4Fx9cqJOCo7tDaD',
          type: 'table',
          props: {
            status: '${state.notificationTableStatus}',
            size: 'default',
            rowVerticalAlign: 'top',
            selectable: false,
            editable: false,
            searchable: false,
            headerHidden: true,
            disabledSelectionVisible: false,
            clickable: false,
            isSingleSelect: false,
            columns: '${state.notificationTablecol}',
            items: '${state.notificationTableItem}',
            title: "i18n('SelectLicence_RenewalEligibilityTitle')",
            search: '',
            selectedItems: [],
            space: {
              marginTop: 'md',
            },
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'notificationTableStatus',
            'notificationTablecol',
            'notificationTableItem',
          ],
        },
        {
          componentId: 'T48XkizO9-U2TT2hLphSx',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: 'md',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'o2_6gOugUpI0vrxPxTqBQ',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_NextButton')",
                type: 'button',
                uiType: 'primary',
                disabled: '${state.disabled_eligible}',
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: '',
                },
                onClick: func.f7_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history', 'disabled_eligible'],
            },
            {
              componentId: 'pZzoo9_FKr66UUFL71wWv',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('Global_CancelButton')",
                type: 'button',
                uiType: 'text-link',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: true,
                onClick: func.f8_onClick,
                space: {
                  paddingLeft: 'md',
                  paddingRight: 'md',
                },
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
      ],
      symbols: [
        {
          id: 'u_7BA0xr8Q0oku7QtzxvE',
          name: 'Header',
          definitions: [
            {
              componentId: '0nSNUzm6NEjCkToaBdmCl',
              type: 'alert',
              props: {
                status: '',
                message: '',
                onClose: null,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
            {
              componentId: 'Y78zMYB80jxbXDw2WuI6o',
              type: 'flexbox',
              props: {
                flexWrap: true,
                flexDirection: 'column-reverse',
                justifyContent: 'initial',
                alignItems: 'initial',
                alignContent: 'initial',
                classNames: 'container',
                space: {
                  marginBottom: '',
                  paddingBottom: '',
                },
              },
              layout: 'base',
              children: [
                {
                  componentId: 'uQukKScRci0q9DWO9b324',
                  parentComponentId: 'Y78zMYB80jxbXDw2WuI6o',
                  type: 'text',
                  props: {
                    variant: 'h1',
                    content: "i18n('Global_ServiceName')",
                    displayAsHtml: false,
                    space: {
                      paddingBottom: 'md',
                      marginTop: 'md',
                    },
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
                {
                  componentId: 'iyAIP8maLEkaZwI2t7dUy',
                  type: 'breadcrumb',
                  props: {
                    items: [
                      {
                        label: "i18n('bcrumbsHome')",
                        link: 'https://www.tamm.abudhabi/',
                        linkTarget: '',
                        id: 'kbzqdrrl',
                      },
                      {
                        label: "i18n('bcrumbsBusinessInAbuDhabi')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqe5hx',
                      },
                      {
                        label: "i18n('bcrumbsRegisterYourBusiness')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqeewv',
                      },
                      {
                        label: "i18n('bcrumbsIndustrialLicences')",
                        link: '',
                        linkTarget: '',
                        id: 'kbzqel7d',
                      },
                    ],
                  },
                  layout: 'base',
                  sharedProps: ['i18n', 'locale'],
                },
              ],
            },
          ],
        },
        {
          id: 'pOuCbjftw6l5xN5WTMEPb',
          name: 'Sidebar_without_card',
          definitions: [
            {
              componentId: 'yeIBuc-dVj7toDnj_7R81',
              type: 'stepTracker',
              props: {
                title: "i18n('ServicePage_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
                classNames: '',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: '2eXUqMf3xlTH9Dity7T6_',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: "i18n('Relevant_entity')",
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address: "i18n('address')",
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: true,
                space: {
                  marginTop: 'xl',
                  paddingBottom: 'lg',
                },
              },
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    customPath: true,
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'notificationTableStatus',
        'notificationTableItem',
        'licenceListColumns',
        'licenceSearch',
        'licenceNumber',
        'licenceListRows',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'actualLicenceList',
        'myLicenceSelectable',
        'myLicenceSearchable',
        'tableTotalRecords',
        'tableCurrPage',
        'tablePageSize',
        'myLicenceHeaderHidden',
        'myLicenceSelectedItems',
        'disabled_eligibility',
        'notificationTablecol',
        'disabled_eligible',
      ],
      mapDispatch: [
        'notificationTableStatus',
        'notificationTableItem',
        'disabled_eligible',
        'licenceListColumns',
        'showSidebar',
        'currentStepIndex',
        'currentSubStepIndex',
        'expandedStepIndexes',
        'steps',
        'actualLicenceList',
        'tablePageSize',
        'licenceListRows',
        'tableCurrPage',
        'tableTotalRecords',
        'myLicenceHeaderHidden',
        'myLicenceSearchable',
        'myLicenceSelectable',
        'licenceNumber',
        'disabled_eligibility',
        'licenceNoError',
        'myLicenceSelectedItems',
        'licenceSearch',
        'licenceNo',
        'totalLicenceList',
        'loading',
        'eligible',
      ],
    },
    init: func.init,
  },
];

export default pageConfig;
