import * as func from './functions';

import customRequires from '../../sharedFunctions/customRequires';

const pageConfig = [
  {
    title: 'SelectLicences',
    pageId: 'Nnqi8j_C5CR7M67tQk-aI',
    expanded: true,
    path: '/selectlicences',
    template: 'custom',
    layout: 'sidebar',
    props: {
      definitions: [
        {
          componentId: 'hBaUjDsYlFjYWype3hF5A',
          type: 'text',
          props: {
            variant: 'h3',
            content: "i18n('selectLicence-title')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'XlAMig-Wnr7986pX2QYCQ',
          type: 'text',
          props: {
            variant: 'p',
            content: "i18n('selectLicence-description')",
            displayAsHtml: false,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale'],
        },
        {
          componentId: 'r5LyTW87RpC7_wBY3ZhmT',
          type: 'table',
          props: {
            size: 'default',
            rowVerticalAlign: 'top',
            selectable: true,
            editable: false,
            searchable: true,
            headerHidden: false,
            disabledSelectionVisible: false,
            clickable: false,
            isSingleSelect: true,
            columns: '${state.table_column}',
            items: '${state.table_row}',
            title: "i18n('selectLicence-tableTitle')",
            onSelectionChange: func.call_f1_onSelectionChange,
            total: '${state.totalRecords}',
            currPage: '${state.currentIndex}',
            pageSize: '${state.currentPageSize}',
            onSearch: func.call_f2_onSearch,
            onPageTurn: func.call_f3_onPageTurn,
            pageResizeOptions: [],
            search: '${state.licenceFilter}',
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'actions',
            'table_row',
            'actualLicenceList',
            'licenceNo',
            'licenceFilter',
            'table_column',
            'totalRecords',
            'currentIndex',
            'currentPageSize',
            'actions',
          ],
        },
        {
          componentId: 'q0V-DvsswsCoFa_D1KYXE',
          type: 'alert',
          props: {
            status: 'error',
            message: "i18n('error_msg')",
            onClose: null,
            space: {
              marginTop: 'md',
              marginBottom: 'sm',
            },
            visible: func.f4_visible,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'alertFlag'],
        },
        {
          componentId: 'k89ANxAR2xHMVu0xeMspb',
          type: 'alert',
          props: {
            status: 'error',
            message: '${state.camundaMessage}',
            onClose: null,
            space: {
              marginBottom: 'md',
              marginTop: 'md',
            },
            visible: func.f5_visible,
          },
          layout: 'base',
          sharedProps: ['i18n', 'locale', 'camundaMessage'],
        },
        {
          componentId: 'h6WuKM-7XqpzZgsGjpET5',
          type: 'flexbox',
          props: {
            flexWrap: true,
            flexDirection: 'initial',
            justifyContent: 'initial',
            alignItems: 'initial',
            alignContent: 'initial',
            space: {
              marginTop: 'lg',
              marginBottom: 'xl',
            },
          },
          layout: 'base',
          children: [
            {
              componentId: 'MnANuJnfyIqJnyEIpu9zO',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('global-next')",
                type: 'button',
                uiType: 'primary',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: true,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                onClick: func.f6_onClick,
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'history',
                'actions',
                'bpm',
                'licenceNo',
                'actions',
              ],
            },
            {
              componentId: 'hYj8WlOyiNUSCuJydZuiu',
              type: 'button',
              props: {
                locale: 'en',
                label: "i18n('button_cancel')",
                type: 'button',
                uiType: 'text-link',
                disabled: false,
                'aria-label': 'button',
                size: 'default',
                icon: null,
                alignIcon: 'end',
                withArrow: false,
                active: false,
                hidden: false,
                iconTooltip: '',
                applyAutoWidth: false,
                space: {
                  marginRight: 'md',
                },
                onClick: func.f7_onClick,
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'history'],
            },
          ],
        },
      ],
      symbols: [
        {
          id: 'XPuuzzSsc1PM7KGrp2LDX',
          name: 'Sidebar',
          definitions: [
            {
              componentId: '_7l1ujJnaZewdBciJZUoA',
              type: 'stepTracker',
              props: {
                title: "i18n('process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":" return props.state.showSideBar;"}',
              },
              layout: 'base',
              sharedProps: [
                'i18n',
                'locale',
                'showSideBar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: 'LlS0jKn4mVvWHElTc4DVL',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: "i18n('relevant_entity')",
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address: "i18n('address')",
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: false,
                space: {
                  marginTop: 'xl',
                  marginBottom: 'xl',
                },
                visible: '{"code":"  return props.state.showSideBar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSideBar'],
            },
          ],
        },
        {
          id: 'zUb_2ox3pxzJj2-JHqAh1',
          name: 'Header',
          definitions: [
            {
              componentId: '_0JdDeDuJ9aLzLvOyksSX',
              type: 'flexbox',
              props: {
                flexWrap: true,
                flexDirection: 'column',
                justifyContent: 'initial',
                alignItems: 'initial',
                alignContent: 'initial',
                classNames: 'container',
              },
              layout: 'base',
              children: [
                {
                  componentId: 'QRUGlUhHpBbWipDuiJI1l',
                  type: 'breadcrumb',
                  props: {
                    space: {
                      marginBottom: 'md',
                      marginTop: 'lg',
                    },
                    items: [
                      {
                        id: 'kdmsxtik',
                        label: "i18n('bc_home')",
                        linkTarget: '_self',
                        link: '/',
                      },
                      {
                        id: 'kdmsyjm9',
                        label: "i18n('bc_digitalServices')",
                        link: 'https://www.tamm.abudhabi/tamm-centers-services',
                        linkTarget: '_self',
                      },
                      {
                        id: 'kdmszcbw',
                        label: "i18n('bc_DED')",
                        link:
                          'https://www.tamm.abudhabi/tamm-centers-services/department-of-economic-development',
                        linkTarget: '_self',
                      },
                    ],
                  },
                  parentComponentId: 'no_parent',
                  sharedProps: ['i18n', 'locale'],
                },
                {
                  componentId: '68aenTCGP0X-L3br5r-li',
                  type: 'text',
                  props: {
                    variant: 'h1',
                    content: "i18n('serviceCard-desc')",
                    displayAsHtml: false,
                  },
                  layout: 'base',
                  parentComponentId: 'no_parent',
                  sharedProps: ['i18n', 'locale'],
                },
              ],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
      {
        type: 'REQUIRES_CUSTOM',
        redirectTo: '/login',
        codeId: '1593585945432',
        test: customRequires,
      },
    ],
    customPath: true,
    state: {
      mapState: [
        'user',
        'loggedIn',
        'showSideBar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'table_row',
        'actualLicenceList',
        'licenceNo',
        'licenceFilter',
        'table_column',
        'totalRecords',
        'currentIndex',
        'currentPageSize',
        'alertFlag',
        'camundaMessage',
      ],
      mapDispatch: [
        'businessKey',
        'instanceId',
        'licenceNo',
        'licenceFilter',
        'showSideBar',
        'camundaMessage',
        'loading',
        'alertFlag',
        'currentStepIndex',
        'expandedStepIndexes',
        'steps',
        'table_row',
        'currentIndex',
        'totalRecords',
        'currentPageSize',
        'actualLicenceList',
        'table_column',
        'totalLicenceList',
      ],
    },
    init: func.init,
    onPageInit: func.onPageInit,
  },
];

export default pageConfig;
