import * as func from './functions';

const pageConfig = [
  {
    title: 'Enter company details',
    pageId: 'fhg_Le7xNC5N21D0plnj_',
    path: '/enter-company-details',
    template: 'custom',
    props: {
      definitions: [
        {
          componentId: 'pXSUeDLCa2_cyHSyupvYl',
          type: 'form',
          props: {
            definitions: [
              {
                componentId: 'SjZWyVNNm7xGrdovmxP1p',
                type: 'fieldset',
                props: {
                  title: '',
                  description: '',
                  children: [
                    {
                      rowTitle: 'Row 1',
                      componentId: 'oUOy5OWdjQdpxjr1NUqeH',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle: 'icvEmirates',
                          componentId: 's0J7GcSTFX2mn-4t3Vg_J',
                          type: 'select',
                          props: {
                            id: '',
                            tabIndex: 0,
                            placeholder: "i18n('select')",
                            label:
                              "i18n('EnterCompanyDetails_InCountryValueEmirate')",
                            items: [
                              {
                                id: 'Abu Dhabi',
                                label: "i18n('abuDhabi')",
                              },
                              {
                                id: 'Ajman',
                                label: "i18n('ajman')",
                              },
                              {
                                id: 'Dubai',
                                label: "i18n('dubai')",
                              },
                              {
                                id: 'Ras Al Khaimah',
                                label: "i18n('rasAlKhaimah')",
                              },
                              {
                                id: 'Sharjah',
                                label: "i18n('sharjah')",
                              },
                              {
                                id: 'Umm Al Quwain',
                                label: "i18n('ummAlQuwain')",
                              },
                              {
                                id: 'Al Fujairah',
                                label: "i18n('alFujairah')",
                              },
                            ],
                            value: null,
                            isOpen: false,
                            disabled: false,
                            isStatic: false,
                            multi: false,
                            showSearch: true,
                            validateStatus: null,
                            help: '',
                            size: 'default',
                            'aria-label': 'select-control',
                            popupWidth: 0,
                            popupAlign: 'start',
                            name: 'icvEmirates',
                            isRequired: true,
                          },
                          layout: 'base',
                        },
                        {
                          fieldTitle: 'isThereBranchCompanyInAlDhafraOrAlAin',
                          componentId: 'XsxnQxpSERtMY54mDc1K-',
                          type: 'select',
                          props: {
                            id: '',
                            tabIndex: 0,
                            placeholder: "i18n('select')",
                            label: "i18n('EnterCompanyDetails_Brach')",
                            items: [
                              {
                                id: 'Yes',
                                label: "i18n('yes')",
                              },
                              {
                                id: 'No',
                                label: "i18n('no')",
                              },
                            ],
                            value: null,
                            isOpen: false,
                            disabled: false,
                            isStatic: false,
                            multi: false,
                            showSearch: true,
                            validateStatus: null,
                            help: '',
                            size: 'default',
                            'aria-label': 'select-control',
                            popupWidth: 0,
                            popupAlign: 'start',
                            name: 'isThereBranchCompanyInAlDhafraOrAlAin',
                            isRequired: true,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                    {
                      rowTitle: 'Row 7',
                      componentId: 'kx6ppTcCcvkRXtyrO7wZT',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                          sm: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle: 'valueSubcontracts',
                          componentId: 'FWMK4I3YZxpYcvi7ONqnT',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label: "i18n('EnterCompanyDetails_Subcontracts')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'valueSubcontracts',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                          },
                          layout: 'base',
                        },
                        {
                          fieldTitle: 'valueSubcontractsInAbuDhabi',
                          componentId: 'h9YdBCodTApSuMJCx-giI',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_SubcontractsInAbuDhabi')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'valueSubcontractsInAbuDhabi',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                    {
                      rowTitle: 'Row 3',
                      componentId: 'gRf5tzFsT3KyUN0bfWt_d',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle: 'totalSalariesEmployeesWithinAbuDhabi',
                          componentId: 'zNBPW7098Bb9SGhvMX93d',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_SalariesAbuDhabi')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'totalSalariesEmployeesWithinAbuDhabi',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                            isValid: true,
                            isValidFunc: func.f1_isValidFunc,
                          },
                          layout: 'base',
                        },
                        {
                          fieldTitle: 'totalSalariesBenefitsEmiratiEmployees',
                          componentId: '_Zgn6DN0cTD-eetV9Lb-o',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_SalariesEmiratiEmployees')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'totalSalariesBenefitsEmiratiEmployees',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                            isValid: true,
                            isValidFunc: func.f2_isValidFunc,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                    {
                      rowTitle: 'Row 4',
                      componentId: 'TGErkSFqEWTS8kCvpgZBL',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle: 'totalSalariesBenefitsExpatEmployees',
                          componentId: 'wJkZspLR7QfZiYSZe5rKR',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_SalariesExpatEmployees')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'totalSalariesBenefitsExpatEmployees',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                            isRequiredFunc: '',
                            onAddClick: func.f3_onAddClick,
                          },
                          layout: 'base',
                        },
                        {
                          fieldTitle: 'totalNumberEmployeesInCompany',
                          componentId: 'ZDTn0Sjt0KuIm-cf0Ve0J',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_NumberOfEmployees')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'totalNumberEmployeesInCompany',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                    {
                      rowTitle: 'Row 5',
                      componentId: 'IG1T2d-rttJ_Uw0MngJ8c',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle: 'netBookValueAssetsHeldByCompany',
                          componentId: 'yTpWmHLGY5q3a8-fHaD2G',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label: "i18n('EnterCompanyDetails_AssetsNetBook')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'netBookValueAssetsHeldByCompany',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                          },
                          layout: 'base',
                        },
                        {
                          fieldTitle:
                            'netBookValueAssetsHeldByCompanyInAbuDhabi',
                          componentId: 'g_FHG_Tp_MY-JYPkoiZ-k',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_AssetsNetBookAbuDhabi')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'netBookValueAssetsHeldByCompanyInAbuDhabi',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                    {
                      rowTitle: 'Row 6',
                      componentId: 'QPg_6DAopKEKgVBD9ZbQK',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle: 'totalRevenue',
                          componentId: 'Ccp_PGNuKm5XY0IADXsuD',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label: "i18n('EnterCompanyDetails_TotalRevenue')",
                            'aria-label': 'input-number',
                            max: 0,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'totalRevenue',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                            isValid: true,
                            isValidFunc: func.f4_isValidFunc,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                  ],
                },
                layout: 'base',
              },
              {
                componentId: 'vfY7NMSL4iTlUGFOc5DdK',
                type: 'fieldset',
                props: {
                  title: "i18n('EnterCompanyDetails_IndustrialInformation')",
                  description:
                    "<p>i18n('enterIndustrialEntityInformationDescription')</p>\n",
                  children: [
                    {
                      rowTitle: 'Row 1',
                      componentId: '1JaCAw3KkO0_shfweW9I8',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle: 'valueOfRawMaterialsPurchased',
                          componentId: 'O3KzxGed_VNGcfm86AEkf',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_RawMaterialsPurchased')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'valueOfRawMaterialsPurchased',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                            isRequiredFunc: '',
                            isValid: true,
                            isValidFunc: func.f5_isValidFunc,
                          },
                          layout: 'base',
                        },
                        {
                          fieldTitle:
                            'valueOfRawMaterialsPurchasedFromAbuDhabi',
                          componentId: '68H5cu-7P-nIE8ylW6B-5',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label:
                              "i18n('EnterCompanyDetails_RawMaterialsPurchasedAbuDhabi')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'valueOfRawMaterialsPurchasedFromAbuDhabi',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                            isRequiredFunc: '',
                            isValid: true,
                            isValidFunc: func.f6_isValidFunc,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                    {
                      rowTitle: 'Row 2',
                      componentId: 'H1qf9FG9q3U_nFV9TOC5m',
                      type: 'grid',
                      props: {
                        columns: 2,
                        flexColumns: {
                          xl: 6,
                          lg: 6,
                          md: 12,
                        },
                        style: {
                          marginTop: '2rem',
                        },
                      },
                      layout: 'base',
                      children: [
                        {
                          fieldTitle:
                            'valueOfOtherExpensesExcludingManpowerCost',
                          componentId: 'P7AJYoh0w90_Mw_CsGQVz',
                          type: 'inputNumber',
                          props: {
                            id: '',
                            tabIndex: 0,
                            uiType: 'horizontal',
                            label: "i18n('EnterCompanyDetails_OtherExpenses')",
                            'aria-label': 'input-number',
                            max: 100,
                            min: 0,
                            step: 1,
                            precision: 0,
                            formatted: false,
                            value: '',
                            defaultValue: '',
                            disabled: false,
                            readonly: false,
                            validateStatus: '',
                            help: '',
                            placeholder: '',
                            name: 'valueOfOtherExpensesExcludingManpowerCost',
                            size: 'default',
                            roundToStepOnBlur: false,
                            isRequired: false,
                          },
                          layout: 'base',
                        },
                      ],
                    },
                  ],
                },
                layout: 'base',
              },
              {
                componentId: 'MVfZeIST0mC_meCb64SwX',
                symbolTitle: 'Symbol 1',
                type: 'symbol',
                props: {
                  symbol: '_yXTD_hRr98et9R1OspXM',
                },
                layout: 'base',
              },
            ],
            description: '<p></p>\n',
            title: "i18n('EntityCompanyDetails_EnterCompanyDetails')",
            formValues: 'companyDetailsForm',
            btnSubmitLabel: "i18n('Global_Next')",
            includeCancelButton: true,
            includeBackButton: true,
            btnBackLabel: "i18n('Global_Back')",
            validateStatus: {
              valid: true,
              message: '',
            },
            btnSubmitArrow: 'end',
            btnBackArrow: 'start',
            btnSubmitClick: func.f7_btnSubmitClick,
            btnSubmitDisabled: func.f8_btnSubmitDisabled,
            btnBackClick: func.f9_btnBackClick,
            btnCancelClick: func.f10_btnCancelClick,
          },
          layout: 'base',
          sharedProps: [
            'i18n',
            'locale',
            'history',
            'companyDetailsForm',
            'companyDetailsForm',
            'actions',
          ],
        },
      ],
      symbols: [
        {
          id: 'eauqjPZrppIH9ngzoQH_1',
          name: 'hero',
          definitions: [
            {
              componentId: 'L0vGbvPcFSBE2WAv2Fh7e',
              type: 'hero',
              props: {
                backgroundImage:
                  'https://journeys-stg.tamm.abudhabi/journeys/journey-template/images/hero.jpg',
                backgroundBase64Extension: '',
                internal: true,
                aspectOfLifeType: '',
                breadcrumbs: [
                  {
                    label: "i18n('bc_home')",
                    link: '/',
                  },
                  {
                    id: 'kd4lrtqy',
                    label: "i18n('bc_businessInAbuDhabi')",
                  },
                  {
                    id: 'kd4ltcaj',
                    label: "i18n('bc_registerYourBusiness')",
                  },
                  {
                    id: 'kd4ltg37',
                    label: "i18n('bc_industrialLicences')",
                  },
                ],
                subTitle: '',
                title: "i18n('Global_Title')",
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale'],
            },
          ],
        },
        {
          id: 'Tvqi6M5rKJu4JAS3soD9-',
          name: 'Sidebar',
          definitions: [
            {
              componentId: 'yELNRmPQ0-BAvQuT6M0L2',
              type: 'stepTracker',
              props: {
                title: "i18n('ServiceCard_Process')",
                steps: '${state.steps}',
                expandedStepIndexes: '${state.expandedStepIndexes}',
                currentStepIndex: '${state.currentStepIndex}',
                i18n: '',
                currentSubStepIndex: '${state.currentSubStepIndex}',
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: [
                'i18n',
                'locale',
                'showSidebar',
                'steps',
                'expandedStepIndexes',
                'currentStepIndex',
                'currentSubStepIndex',
              ],
            },
            {
              columnIndex: 0,
              componentId: 'EGdDKE5QVU6ElyGm7BnMR',
              type: 'relevantEntity2-0-0',
              props: {
                i18n: '',
                title: 'Relevant entity',
                entities: [
                  {
                    logo:
                      'https://www.tamm.abudhabi/en/tamm-centers-services/-/media/Project/TAMM/Home/Footer%20Logos/Department%20of%20Economic%20Development',
                    address:
                      'Baniyas Towers, Al Falah Street - Fatima bint Mubarak St 6, Abu Dhabi',
                    phones: [],
                    website: 'www.adeconomy.ae',
                    email: 'email@domain.com',
                  },
                ],
                closedAll: false,
                space: {
                  marginTop: 'xl',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
            {
              columnIndex: 0,
              componentId: 'da0TyuQFwqVVGZjOAC_LI',
              type: 'relatedJourneyCard',
              props: {
                aspectOfLifeType: 'business-management',
                icon: null,
                description:
                  'The Manage Your Business journey contains a consolidated dashboard for business owners and representatives to view and...',
                label: 'Manage your business',
                title: 'Related journey',
                space: {
                  marginTop: 'lg',
                },
                visible: '{"code":"  return props.state.showSidebar;"}',
              },
              sharedProps: ['i18n', 'locale', 'showSidebar'],
            },
          ],
        },
        {
          id: '_yXTD_hRr98et9R1OspXM',
          name: 'auto save without underline',
          definitions: [
            {
              componentId: 'Wg41huxRP35WX0AzJK3FJ',
              type: 'text',
              props: {
                variant: 'p',
                content: '<p>Your application is being autosaved</p>\n',
                displayAsHtml: true,
                space: {
                  marginTop: 'xl',
                  marginBottom: '',
                  paddingTop: '',
                },
                classNames: '${state.classNames_decbcfcfbe}',
              },
              layout: 'base',
              sharedProps: ['i18n', 'locale', 'classNames_decbcfcfbe'],
            },
          ],
        },
      ],
      sharedFunctions: {},
    },
    layout: 'sidebar',
    requires: [
      {
        type: 'REQUIRES_LOGIN',
        redirectTo: '/login',
      },
    ],
    state: {
      mapState: [
        'user',
        'loggedIn',
        'classNames_decbcfcfbe',
        'showSidebar',
        'steps',
        'expandedStepIndexes',
        'currentStepIndex',
        'currentSubStepIndex',
        'companyDetailsForm',
      ],
      mapDispatch: ['steps', 'currentSubStepIndex', 'companyDetailsForm'],
    },
    init: func.init,
  },
];

export default pageConfig;
