export default {
  Global_Title:
    'طلب الاستفادة من برنامج تحفيز القطاع الصناعي عبر تعرفة الكهرباء',
  ServiceCard_Process: 'الخطوات',
  SelectLicence_Title: 'اختر الرخصة ',
  SelectLicence_Desc:
    'يرجى تحديد رقم الرخصة من القائمة أدناه للحصول على شهادة تعرفة الكهرباء. تشترط شركات توزيع الكهرباء (شركة أبوظبي للتوزيع وشركة العين للتوزيع) هذا لتطبيق الخصم واحتساب التعريفة النهائية. يُرجى تحديد الرخصة والمتابعة إلى القسم التالي.',
  'form.cancel': 'إلغاء',
  Global_Next: 'التالي',
  Global_Cancel: 'إلغاء',
  SelectLicence_ContactPerson:
    'أنا مسؤول التواصل لهذا الطلب. يمكن الحصول على بيانات الاتصال من تفاصيل الحساب.',
  SelectLicence_Name: 'الاسم <ادخل>',
  SelectLicence_PhoneNumber: 'الهاتف المحمول',
  SelectLicence_EmailAddress: 'البريد الإلكتروني',
  Global_AddContactInformation: 'أضف معلومات الاتصال ',
  Global_Back: 'الرجوع',
  Global_DownloadCertificate: 'تنزيل الشهادة ',
  CertificateIssued_VisitDashboard: 'زُر لوحة التحكم',
  Global_SubmittedOn: 'تاريخ التقديم:',
  Global_ReferenceNo: 'الرقم المرجعي:',
  CertificateIssued_Issued: 'صدرت الشهادة',
  SelectLicence_MyLicencesTable: 'رُخصي',
  SelectLicence_LicenceNumberCol: 'رقم الرخصة ',
  SelectLicence_CompanyNameCol: 'اسم الشركة ',
  ApplicationReturned_PleaseNote: 'يرجى الانتباه:',
  pleaseNoteText: 'ar-value',
  UploadDocuments_Desc: 'يُرجى تحميل الملفات المطلوبة.',
  UploadDocuments_Disclaimer:
    'باختيار هذا المربع، أمنح موافقتي على مشاركة بياناتي والمعلومات المتعلقة بطلبي وجميع الملفات التي قدمتها لمكتب تنمية الصناعة وجميع الجهات ذات الصلة.',
  licenceStatus_nextStep_title: 'ar-value',
  licenceStatus_nextStep_description: 'ar-value',
  CertificateIssued_Desc:
    'تهانينا! صدرت شهادتك وبإمكانك تنزيل نسخة منها أدناه.',
  relatedServices_1: 'ar-value',
  relatedServices_2: 'ar-value',
  relatedServices_3: 'ar-value',
  relatedServices_4: 'ar-value',
  relatedServices_5: 'ar-value',
  relatedServices_6: 'ar-value',
  relatedServices_7: 'ar-value',
  relatedServices_8: 'ar-value',
  UnderApproval_Desc:
    'تم تقديم طلبك للحصول على موافقة من الجهة التي اخترتها ومن دائرة التنمية الاقتصادية. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجَّل. كما يمكنك مراجعة حالة الطلب بنفسك  في أي وقت من خلال لوحة التحكم \\"أدِر شركتك\\".',
  AwaitingApproval_Refresh: 'سيتم تحديث بيانات الصفحة بعد صدور الرقم المرجعي.',
  Global_SelectCertifiedEntities: 'اختر جهات مراجعة الأداء',
  SelectEntity_Desc:
    'يرجى اختيار جميع الجهات التي ترغب في الحصول على عرض سعر منها. \\nملاحظة: يمكن اختيار أكثر من جهة',
  entityInformationDescription: 'ar-value',
  valueOfRawMaterialsPurchased: 'ar-value',
  valueOfOtherExpensesExcludingManpowerCost: 'ar-value',
  assetsNetBookValueHeldByCompanyInAbuDhabi: 'ar-value',
  assetsNetBookValueHeldByCompany: 'ar-value',
  totalNumberOfEmployees: 'ar-value',
  totalRevenue: 'ar-value',
  valueOfRawMaterialsPurchasedInAbuDhabi: 'ar-value',
  icvEmirate: 'ar-value',
  valueOfSubcontractsInAbuDhabi: 'ar-value',
  valueOfSubcontracts: 'ar-value',
  totalSalariesAndBenefitsOfEmiratis: 'ar-value',
  totalSalariesofEmployeesWithAbuDhabi: 'ar-value',
  totalSalariesAndBenefitsOfExpatEmployees: 'ar-value',
  enterIndustrialEntityInformationDescription: 'ar-value',
  enterIndustrialEntityInformation: 'ar-value',
  no: 'ar-value',
  yes: 'ar-value',
  SelectLicence_NoLicence: 'لا يوجد أي رخصة مرتبطة بحسابك.',
  companyDetailsTitle: 'ar-value',
  companyDetailsDescription: 'ar-value',
  select: 'ar-value',
  branchinAlDhafraAlAin: 'ar-value',
  SelectLicence_Disclaimer:
    'أتعهد بالالتزام بكافة الاشتراطات والمتطلبات المنصوص عليها بالقوانين والقرارات المنظمة للأنشطة الاقتصادية من إصدار\\/تجديد\\/تعديل التراخيص التجارية، وكافة البيانات الواردة بالطلب، و أتعهد بعدم ممارسة النشاط التجاري إلا بعد الحصول على موافقات الجهات المختصة بالتراخيص، وللدائرة الحق باتخاذ الإجراءات القانونية والإدارية في حال عدم الالتزام بالتعهد.',
  abuDhabi: 'ar-value',
  ajman: 'ar-value',
  dubai: 'ar-value',
  rasAlKhaimah: 'ar-value',
  sharjah: 'ar-value',
  ummAlQuwain: 'ar-value',
  alFujairah: 'ar-value',
  upload_documents: 'ar-value',
  enter_company_details: 'ar-value',
  Global_SelectLicence: 'اختر الرخصة ',
  Global_FillApplication: 'املأ الطلب',
  SelectEntity_Entity1: 'أردنت للاستشارات المالية والمحاسبة ذ.م.م',
  SelectEntity_Entity2: 'بيكر تلي ام كي ام محاسبون قانونيون',
  SelectEntity_Entity3: 'ديلويت آند توش (الشرق الأوسط)',
  SelectEntity_Entity4: 'إرنست ويونغ - الشرق الاوسط',
  SelectEntity_Entity5: 'بروتيفتي ميمبر فيرم (الشرق الأوسط)',
  SelectEntity_Entity6: 'مازاراس للمحاسبة القانونية ',
  SelectEntity_Entity7: 'كرو الإمارات',
  SelectEntity_Entity8: 'إم بي سي للتدقيق والمحاسبة - أبوظبي',
  SelectEntity_Entity9: 'بيه كي اف -  محاسبون قانونيون ومستشارو أعمال',
  SelectEntity_Entity10: 'طلال أبو غزالة وشركاه الدولية - أبوظبي',
  SelectEntity_SelectCertifiedEntities: 'اختر جهات مراجعة الأداء',
  ApplicationReturned_ApplicationReturned: 'تمت إعادة طلبك',
  ApplicationReturned_Desc:
    'طلبت إحدى الجهات معلومات إضافية. يُرجى مراجعة التعليقات ثم تحديث الطلب.',
  ApplicationReturned_Feedback: 'التعليقات',
  ApplicationReturned_DocumentUpload: 'تحميل المستندات',
  ApplicationReturned_DocumentUploadDesc:
    'يرجى تحميل الملفات المطلوبة بناءً على تعليقات الجهة. يمكنك تحميل أي عدد مطلوب من الملفات.',
  UploadDocuments_FileType: 'نوع الملف:   JPG أو  PDF أو  PNG',
  ApplicationReturned_PleaseNoteDesc:
    'تجد أدناه جميع التعليقات من الجهات المعنية بطلبك. قد يتكرر طلب بعض الملفات نفسها، يمكنك تحميلها مرة واحدة. \\nملاحظة: ستستلم جميع الجهات الملفات التي حمّلتها. ',
  ApplicationReturned_ViewQuotationsList: 'الرجوع لقائمة عروض الأسعار',
  btn_submit: 'ar-value',
  QuotationReceived_EntityQuotationsReceived:
    'تم استلام عروض الأسعار من الجهات',
  ReceiveQuotations_Desc:
    'يرجى الانتظار قليلاً ريثما نستلم عروض الأسعار من الجهات التي اخترتها. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجَّل. \\n\\nيمكنك تنزيل ومراجعة عروض الأسعار واتخاذ القرار المناسب. فور اختيارك لمزود الخدمة، يُرجى متابعة طلبك وتقديمه للجهة ذات الصلة.',
  ReceiveQuotations_Refresh:
    'سيتم تحديث الجدول وإضافة عروض الأسعار الصادر من الجهات.',
  CertificateIssued_QuotationSummary: 'ملخص الأسعار',
  CertificateIssued_QuotationAmountCol: 'قيمة عرض السعر',
  Global_AwardContract: 'ترسية العقد',
  Global_EntityCol: 'الجهة',
  ReceiveQuotations_ViewFeedback: 'مراجعة التعليقات',
  Global_GetApproval: 'الحصول على الموافقة',
  Global_ReviewQuotations: 'مراجعة عروض الأسعار',
  Global_SubmitApplication: 'تقديم الطلب',
  adv_something_went_wrong: 'ar-value',
  adv_something_went_wrong_desc: 'ar-value',
  ReceiveQuotations_PendingQuote: 'قيد انتظار عرض السعر',
  UploadDocuments_Document1: 'الكشوف المالية المدققة (العام الماضي)',
  UploadDocuments_Document2:
    'قائمة القوة العاملة الصادرة من وزارة الموارد البشرية  والتوطين- أبوظبي',
  UploadDocuments_Document3: 'تفاصيل رواتب العمال',
  UploadDocuments_Document4: 'عدد المواطنين الإماراتيين في القوة العاملة ',
  UploadDocuments_Document5: 'تفاصيل وعدد العمال في كل وردية ',
  UploadDocuments_Document6: 'تفاصيل القوة الكهربائية للموقع ',
  UploadDocuments_Document7: 'تفاصيل ساعات العمل اليومية',
  UploadDocuments_Document8: 'تفاصيل ساعات العمل في الوردية الواحدة',
  Global_UploadDocuments: 'تحميل المستندات',
  UploadDocuments_UploadDocuments: 'تحميل المستندات',
  SelectLicence_AddContactInformation: 'أضف معلومات الاتصال ',
  AwaitingApproval_PleaseWait: 'تم تقديم طلبك بنجاح ',
  ReceiveQuotations_ReceivingEntityQuotations:
    'عروض الأسعار من الجهات قيد الاستلام',
  ReceiveQuotations_Request:
    'طلبت إحدى الجهات معلومات إضافية. يُرجى مراجعة التعليقات ثم تحديث الطلب.',
  Global_QuotationSummary: 'ملخص عرض الأسعار',
  CertificateIssued_DownloadCertificate: 'تنزيل الشهادة ',
  Global_GetCertificate: 'احصل على الشهادة ',
  Global_QuotationAmountCol: 'قيمة عرض السعر',
};
