export default {
  Global_Title: 'Request for Industrial Electricity Tariff',
  ServiceCard_Process: 'Process',
  SelectLicence_Title: 'Select Licence',
  SelectLicence_Desc:
    'Please select a licence number to obtain the Electricity Tariff Certificate. This is required by the electricity distribution companies (Abu Dhabi Distribution Company and Al Ain Distribution Company) for issuing the rebate and the final tariff rate. Please make your selection and proceed to the next section. ',
  'form.cancel': 'Cancel',
  Global_Next: 'NEXT',
  Global_Cancel: 'Cancel',
  bc_home: 'Home',
  bc_businessInAbuDhabi: 'Business In Abu Dhabi',
  bc_registerYourBusiness: 'Register Your Business',
  pleaseLogIn: 'Please Login',
  bc_industrialLicences: 'Industrial Licences',
  SelectLicence_ContactPerson:
    'I am the contact person for this application. Take my contact information from the account details.',
  SelectLicence_Name: 'NAME',
  SelectLicence_PhoneNumber: 'MOBILE NUMBER',
  SelectLicence_EmailAddress: 'EMAIL ADDRESS',
  errorContactName: 'This field is required',
  errorContactEmail: 'This field is required and must be an email address',
  errorContactMobile: 'This field is required and must be a mobile number',
  errorLicenceNotSelected: 'Select at least one Licence',
  Global_AddContactInformation: 'Add Contact Information',
  applicantDetailsDescription:
    'Please provide the details below. These contact details will be used for any future correspondences related to this application.  ',
  Global_Back: 'BACK',
  Global_DownloadCertificate: 'Download Certificate',
  CertificateIssued_VisitDashboard: 'VISIT DASHBOARD',
  Global_SubmittedOn: 'Submitted On:',
  Global_ReferenceNo: 'Reference Number:',
  waitingApprovalTitle: 'Confirming Request',
  somethingWentWrongTitle: 'Something Went Wrong',
  somethingWentWrongDescription:
    'An error occurred while trying to complete your request. Please try again.',
  CertificateIssued_Issued: 'Your Certificate Has Been Issued',
  SelectLicence_MyLicencesTable: 'My Licences',
  SelectLicence_LicenceNumberCol: 'Licence Number',
  SelectLicence_CompanyNameCol: 'Company Name',
  ApplicationReturned_PleaseNote: 'Please note:',
  pleaseNoteText:
    "If your licence number is not listed here, please <a href='#'>link your licence</a> or contact the Department of Economic Development on + 971 2 816 8888",
  UploadDocuments_Desc: 'Please upload the requested documents.',
  UploadDocuments_Disclaimer:
    'By checking here, I give my approval to share my data, information and all other documents being submitted, with the Bureau of Industry Development, and all other relevant parties.',
  licenceStatus_nextStep_title: 'Your next steps to setup your business',
  licenceStatus_nextStep_description:
    'Now that your licence has been issued, you may consider the following services to continue with your business setup.',
  CertificateIssued_Desc:
    'Congratulations! Your certificate has been issued and you can download it below.',
  relatedServices_1: 'Fund your business',
  relatedServices_2: 'Open a bank account',
  relatedServices_3: 'Learn about maintenance permits',
  relatedServices_4: 'Learn more about hiring',
  relatedServices_5: 'Recruitment tracker',
  relatedServices_6: 'Employment documents',
  relatedServices_7: 'Financing and funding options',
  relatedServices_8: 'Trademark Registration',
  UnderApproval_Desc:
    'Your application has been sent for approval to the selected entity and the Department of Economic Development. You will be notified about changes to your application\\u2019s status on the registered email address and mobile number. You may also check the status of your application at any time by visiting the Manage Your Business dashboard.',
  AwaitingApproval_Refresh:
    'This page will refresh and update you after the reference number has been generated.',
  Global_SelectCertifiedEntities: 'Select Certified Entities',
  SelectEntity_Desc:
    'Please select all the entities you are seeking to receive a quote. Note: Multiple selections possible',
  entityInformationDescription: 'company details',
  valueOfRawMaterialsPurchased: 'value of raw materials purchased',
  valueOfOtherExpensesExcludingManpowerCost:
    'value of other expenses excluding manpower cost',
  assetsNetBookValueHeldByCompanyInAbuDhabi:
    'assets net book value held by company in abu dhabi',
  assetsNetBookValueHeldByCompany: 'assets net book value held by company',
  totalNumberOfEmployees: 'total number of employees',
  totalRevenue: 'total revenue',
  valueOfRawMaterialsPurchasedInAbuDhabi:
    'value of raw materials purchased in abu dhabi',
  icvEmirate: 'icv emirate',
  valueOfSubcontractsInAbuDhabi: 'value of subcontracts in abu dhabi',
  valueOfSubcontracts: 'value of subcontracts',
  totalSalariesAndBenefitsOfEmiratis:
    'total salaries and benefits of emirati employees',
  totalSalariesofEmployeesWithAbuDhabi:
    'total salaries of employees with abu dhabi',
  totalSalariesAndBenefitsOfExpatEmployees:
    'total salaries and benefits of expat employees',
  enterIndustrialEntityInformationDescription:
    'Please select the entities you would like to validate your details with.',
  enterIndustrialEntityInformation: 'Enter Industrial Entity Information',
  no: 'No',
  yes: 'Yes',
  SelectLicence_NoLicence:
    'You do not have any licences linked to your account.',
  companyDetailsTitle: 'Enter Company Details',
  companyDetailsDescription:
    'Please enter your company details requested below',
  select: 'Select',
  branchinAlDhafraAlAin: 'branch in al dhafra/al ain',
  SelectLicence_Disclaimer:
    'I do hereby undertake to comply with all the conditions and requirements stipulated in the laws and resolutions regulating the economic activities related to issuing/renewing and amendment of the commercial licences and all the data included in the application. I also undertake not to practice the commercial activity unless after obtaining the approvals of the relevant authorities. The DED has the right to take all the legal and administrative actions in case of any breach of this undertaking.',
  abuDhabi: 'Abu Dhabi',
  ajman: 'Ajman',
  dubai: 'Dubai',
  rasAlKhaimah: 'Ras Al Khaimah',
  sharjah: 'Sharjah',
  ummAlQuwain: 'Umm Al Quwain',
  alFujairah: 'Al Fujairah',
  upload_documents: 'Upload Documents',
  enter_company_details: 'Enter Details Company',
  Global_SelectLicence: 'Select Licence',
  Global_FillApplication: 'Fill up Application',
  SelectEntity_Entity1: 'Ardent Advisory & Accounting',
  SelectEntity_Entity2: 'Baker Tilly MKM Chartered Accountants',
  SelectEntity_Entity3: 'Deloitte & Touche (Middle East)',
  SelectEntity_Entity4: 'Ernst & Young (Middle East)',
  SelectEntity_Entity5: 'Proviti Member Firm Middle East Consultancy',
  SelectEntity_Entity6: 'Mazars Chartered Accountants',
  SelectEntity_Entity7: 'Crowe Mask',
  SelectEntity_Entity8: 'MBC Auditing and Accounting - ADH',
  SelectEntity_Entity9: 'PKF Accountants and Business Advisors',
  SelectEntity_Entity10: 'Talal Abu Ghazzalah & Co. International Abu Dhabi',
  SelectEntity_SelectCertifiedEntities: 'Select Certified Entities',
  ApplicationReturned_ApplicationReturned: 'Your Application Has Been Returned',
  ApplicationReturned_Desc:
    'One or more entities have requested for additional information. Please review the feedback below and update your application to proceed further. ',
  ApplicationReturned_Feedback: 'Feedback',
  ApplicationReturned_DocumentUpload: 'Upload Document ',
  ApplicationReturned_DocumentUploadDesc:
    'Please upload the required documents based on the feedback above. You can upload as many documents as needed.',
  UploadDocuments_FileType: 'File types: JPG, PDF, PNG',
  ApplicationReturned_PleaseNoteDesc:
    'As this is a collective feedback from the selected entities, some requested documents may be redundant and required to be uploaded only once. \\nNote: All entities will receive the document(s) you upload.',
  ApplicationReturned_ViewQuotationsList: 'GO BACK TO QUOTATIONS',
  btn_submit: 'SUBMIT',
  QuotationReceived_EntityQuotationsReceived:
    'Quotations From Entities Being Received',
  ReceiveQuotations_Desc:
    "Please wait while we receive the quotation from your preferred entities. You will be notified about changes to your application's status on the registered email address and mobile number. You can download and review the quotes and make an informed decision. Once you have chosen your service provider, please proceed with your application by awarding the contract to the relevant entity.",
  ReceiveQuotations_Refresh:
    'This table will refresh and update with the quotes received from the entities.',
  CertificateIssued_QuotationSummary: 'Quotation Summary',
  CertificateIssued_QuotationAmountCol: 'Quotation Value',
  Global_AwardContract: 'AWARD CONTRACT',
  Global_EntityCol: 'Entity',
  ReceiveQuotations_ViewFeedback: 'REVIEW THE FEEDBACK',
  Global_GetApproval: 'Get Approval',
  Global_ReviewQuotations: 'Review Quotations',
  Global_SubmitApplication: 'Submit Application',
  adv_something_went_wrong: 'Something went wrong',
  adv_something_went_wrong_desc: 'Something went wrong Details',
  ReceiveQuotations_PendingQuote: 'Pending Quote',
  UploadDocuments_Document1: 'AUDITED FINANCIAL STATEMENTS (PREVIOUS YEAR)',
  UploadDocuments_Document2: 'CERTIFIED LABOURERS LIST ISSUED BY MOHRE',
  UploadDocuments_Document3: 'LABOUR SALARIES DETAILS',
  UploadDocuments_Document4: 'NUMBER OF UAE NATIONALS IN THE WORKFORCE',
  UploadDocuments_Document5: 'NUMBER OF LABOURERS PER SHIFT DETAILS',
  UploadDocuments_Document6: 'SITE POWER CONNECTION DETAILS',
  UploadDocuments_Document7: 'WORKING HOURS PER DAY DETAILS',
  UploadDocuments_Document8: 'WORKING HOURS PER SHIFT DETAILS',
  Global_UploadDocuments: 'Upload Documents',
  UploadDocuments_UploadDocuments: 'Upload Documents',
  SelectLicence_AddContactInformation: 'Add Contact Information',
  AwaitingApproval_PleaseWait: 'Your Application Has Been Submitted',
  ReceiveQuotations_ReceivingEntityQuotations:
    'Quotations From Entities Being Received',
  ReceiveQuotations_Request:
    'One or more entities have requested for additional information. Please review this feedback and update your application.',
  Global_QuotationSummary: 'Quotation Summary',
  CertificateIssued_DownloadCertificate: 'DOWNLOAD CERTIFICATE',
  Global_GetCertificate: 'Get Certificate',
  Global_QuotationAmountCol: 'Quotation Value',
};
