

interface IVariables {
  [key: string]: any;
}

const contactType = (key: string) => {
  const contactTypesObj: IVariables = {
    'Non-Local Company': 100,
    'Free Zone': 104,
    'Foreign Company': 12,
    Governmental: 13,
    Individual: 10,
  };
  if (Object.prototype.hasOwnProperty.call(contactTypesObj, key)) {
    return contactTypesObj[key];
  }
  return null;
};

const representativeType = (key: string) => {
  const representativeTypeObj: IVariables = {
    Owner: 1,
    Partner: 2,
    Sponsor: 3,
    Manager: 4,
    'Heirs Representative': 5,
    'Commissioner to Sign': 7,
  };
  if (Object.prototype.hasOwnProperty.call(representativeTypeObj, key)) {
    return representativeTypeObj[key];
  }
  return null;
};

const nationalityCode = (key: string) => {
  const nationalityObj: IVariables = {
    Afghanistan: 'AFG',
    Albania: 'ALB',
    Algeria: 'DZA',
    'American Samoa': 'ASM',
    Andorra: 'AND',
    Angola: 'AGO',
    Anguilla: 'AIA',
    'Antarctica‬': 'ATA',
    'Antigua and Barbuda‬': 'ATG',
    Argentina: 'ARG',
    'Armenia‬': 'ARM',
    'Aruba‬': 'ABW',
    'Australia‬': 'AUS',
    'Austria‬': 'AUT',
    'Azerbaijan‬': 'AZE',
    Bahamas: 'BHS',
    Bahrain: 'BHR',
    Bangladesh: 'BGD',
    Barbados: 'BRB',
    Belarus: 'BLR',
    Belgium: 'BEL',
    Belize: 'BLZ',
    Benin: 'BEN',
    Bermuda: 'BMU',
    Bhutan: 'BTN',
    Bolivia: 'BOL',
    'Bosnia and Herzegovina': 'BIH',
    Botswana: 'BWA',
    'Bouvet Island': 'BVT',
    Brazil: 'BRA',
    'British Indian Ocean Territory': 'IOT',
    Brunei: 'BRN',
    Bulgaria: 'BGR',
    'Burkina Faso': 'BFA',
    Burundi: 'BDI',
    Cambodia: 'KHM',
    Cameroon: 'CMR',
    Canada: 'CAN',
    'Cayman Islands‬': 'CYM',
    'Central African Republic': 'CAF',
    Chad: 'TCD',
    Chile: 'CHL',
    China: 'CHN',
    'Christmas Island‬': 'CXR',
    Colombia: 'COL',
    'Comoros‬': 'COM',
    Congo: 'COG',
    'Cook Islands': 'COK',
    'Costa Rica': 'CRI',
    Croatia: 'HRV',
    Cuba: 'CUB',
    Cyprus: 'CYP',
    'Czech Republic': 'CZE',
    Denmark: 'DNK',
    Djibouti: 'DJI',
    Dominica: 'DMA',
    'Dominican Republic': 'DOM',
    Ecuador: 'ECU',
    Egypt: 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    Eritrea: 'ERI',
    Estonia: 'EST',
    Ethiopia: 'ETH',
    'Falkland Islands': 'FLK',
    'Faroe Islands': 'FRO',
    Fiji: 'FJI',
    Finland: 'FIN',
    France: 'FRA',
    'French Guiana': 'GUF',
    'French Southern Territories': 'ATF',
    Gabon: 'GAB',
    Gambia: 'GMB',
    Georgia: 'GEO',
    Germany: 'DEU',
    Ghana: 'GHA',
    Gibraltar: 'GIB',
    Greece: 'GRC',
    Greenland: 'GRL',
    Grenada: 'GRD',
    Guadeloupe: 'GLP',
    Guam: 'GUM',
    Guatemala: 'GTM',
    Guinea: 'GIN',
    'Guinea-Bissau': 'GNB',
    Guyana: 'GUY',
    Haiti: 'HTI',
    'Heard Island And McDonald Islands': 'HMD',
    Honduras: 'HND',
    'Hong Kong': 'HKG',
    Hungary: 'HUN',
    Iceland: 'ISL',
    India: 'IND',
    Indonesia: 'IDN',
    Iran: 'IRN',
    Iraq: 'IRQ',
    Ireland: 'IRL',
    Italy: 'ITA',
    Jamaica: 'JAM',
    Japan: 'JPN',
    Jordan: 'JOR',
    Kazakhstan: 'KAZ',
    Kenya: 'KEN',
    Kiribati: 'KIR',
    Kuwait: 'KWT',
    Kyrgyzstan: 'KGZ',
    Laos: 'LAO',
    Latvia: 'LVA',
    Lebanon: 'LBN',
    Lesotho: 'LSO',
    Liberia: 'LBR',
    Libya: 'LBY',
    Liechtenstein: 'LIE',
    Lithuania: 'LTU',
    Luxembourg: 'LUX',
    Macao: 'MAC',
    Macedonia: 'MKD',
    Madagascar: 'MDG',
    Malawi: 'MWI',
    Malaysia: 'MYS',
    Maldives: 'MDV',
    Mali: 'MLI',
    Malta: 'MLT',
    'Marshall Islands': 'MHL',
    Martinique: 'MTQ',
    Mauritania: 'MRT',
    Mauritius: 'MUS',
    Mayotte: 'MYT',
    Mexico: 'MEX',
    Micronesia: 'FSM',
    Moldova: 'MOA',
    Monaco: 'MCO',
    Mongolia: 'MNG',
    Montserrat: 'MSR',
    Morocco: 'MAR',
    Mozambique: 'MOZ',
    Myanmar: 'MMR',
    Namibia: 'NAM',
    Nauru: 'NRU',
    Nepal: 'NPL',
    Netherlands: 'NLD',
    'Netherlands Antilles': 'ANT',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    Nicaragua: 'NIC',
    Niger: 'NER',
    Nigeria: 'NGA',
    Niue: 'NIU',
    'Norfolk Island': 'NFK',
    'North Korea': 'PRK',
    'Northern Mariana Islands': 'MNP',
    Norway: 'NOR',
    Oman: 'OMN',
    Pakistan: 'PAK',
    Palau: 'PLW',
    Palestine: 'PSE',
    Panama: 'PAN',
    'Papua New Guinea': 'PNG',
    Paraguay: 'PRY',
    Peru: 'PER',
    Philippines: 'PHL',
    Pitcairn: 'PCN',
    Poland: 'POL',
    Portugal: 'PRT',
    'Puerto Rico': 'PRI',
    Qatar: 'QAT',
    Reunion: 'REU',
    Romania: 'ROU',
    Russia: 'RUS',
    Rwanda: 'RWA',
    'Saint Helena': 'SHN',
    'Saint Kitts And Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Pierre And Miquelon': 'SPM',
    Samoa: 'WSM',
    'San Marino': 'SMR',
    'Saudi Arabia': 'SAU',
    Senegal: 'SEN',
    Serbia: 'SRB',
    'Serbia and Montenegro': 'SCG',
    Seychelles: 'SYC',
    'Sierra Leone': 'SLE',
    Singapore: 'SGP',
    Slovakia: 'SVK',
    Slovenia: 'SVN',
    'Solomon Islands': 'SLB',
    Somalia: 'SOM',
    'South Africa': 'ZAF',
    'South Korea': 'KOR',
    Spain: 'ESP',
    'Sri Lanka': 'LKA',
    Sudan: 'SDN',
    Suriname: 'SUR',
    'Svalbard And Jan Mayen': 'SJM',
    Swaziland: 'SWZ',
    Sweden: 'SWE',
    Switzerland: 'CHE',
    Syria: 'SYR',
    Taiwan: 'TWN',
    Tajikistan: 'TJK',
    Tanzania: 'TZA',
    Thailand: 'THA',
    'Timor-Leste': 'TLS',
    Togo: 'TGO',
    Tokelau: 'TKL',
    Tonga: 'TON',
    'Trinidad and Tobago': 'TTO',
    Tunisia: 'TUN',
    Turkey: 'TUR',
    Turkmenistan: 'TKM',
    'Turks And Caicos Islands': 'TCA',
    Tuvalu: 'TUV',
    'U.S. Virgin Islands': 'UMI',
    Uganda: 'UGA',
    Ukraine: 'UKR',
    'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR',
    'United States': 'USA',
    Uruguay: 'URY',
    Uzbekistan: 'UZB',
    Vanuatu: 'VUT',
    Venezuela: 'VEN',
    Vietnam: 'VNM',
    'Wallis And Futuna': 'WLF',
    'Western Sahara': 'ESH',
    Yemen: 'YEM',
    Zambia: 'ZMB',
    Zimbabwe: 'ZWE',
  };
  if (Object.prototype.hasOwnProperty.call(nationalityObj, key)) {
    return nationalityObj[key];
  }
  return null;
};

export { contactType, representativeType, nationalityCode };
