export default {
  Global_ServiceName: 'طلب تجديد رخصة اقتصادية - صناعية',
  ServicePage_StartButton: 'ابدأ',
  ServicePage_ServiceTime: 'أقل من 6 دقائق',
  ServicePage_Fees: 'الرسوم التقريبية: 10,000 درهم إماراتي',
  ServicePage_DescriptionTitle: 'الوصف',
  ServicePage_Description:
    'من خلال هذه الخدمة، يمكنك تجديد رخصتك الصناعية التي على وشك أن تنتهي صلاحيتها خلال 60 يوماً. بعد إدخال رقم الرخصة، إن كنت مخولاً للتجديد، يتعين عليك تقديم الملفات وإتمام الدفع. فور تجديد رخصتك، ستتمكن من إصدار الرخصة الجديدة وتنزيل الملف.',
  ServicePage_Process: 'الخطوات',
  ServicePage_Step1: 'املأ الطلب',
  ServicePage_Step1Desc: 'الرجاء إدخال التفاصيل المطلوبة عن الشركة.',
  ServicePage_Step2: 'احصل على الرخصة',
  ServicePage_Step2Desc: 'أرسل طلبك للموافقة عليه من دائرة التنمية الاقتصادية.',
  ServicePage_FeesTableTitle: 'الرسوم المطلوبة',
  ServicePage_Column1Title: 'المستند',
  ServicePage_Column2Title: 'الرسوم',
  ServicePage_PaymentMethods: 'وسيلة الدفع: بطاقة الائتمان والدرهم الإلكتروني',
  SelectLicence_Title: 'اختر الرخصة',
  SelectLicence_Description:
    'يُرجى اختيار رقم الرخصة للتحقق من الآهلية. يُرجى العلم أن هذه الخدمة متاحة للرخص التي ستنتهي صلاحيتها خلال 60 يومٍ فقط. فور اختيارك للرخصة، يُرجى الاستمرار بالخطوات التالية.',
  SelectLicence_MyLicencesTableTitle: 'رُخصي',
  SelectLicence_TableSearch: 'بحث',
  SelectLicence_TableColumn1: 'رقم الرخصة',
  SelectLicence_TableColumn2: 'اسم الشركة',
  SelectLicence_PaginationShowing: 'عرض',
  SelectLicence_NoteTitle: 'ملاحظة:',
  SelectLicence_NoteDescription:
    'إن لم يكن رقم الرخصة مدرجاً أدناه، يُرجى ربط رخصتك بحسابك أو المحاولة مرة أخرى أو الاتصال بدائرة التنمية الاقتصادية على الرقم التالي 0097128158888.',
  SelectLicence_CheckEligibilityButton: 'اضغط إن كنت مؤهلًا لهذه الخدمة',
  SelectLicence_RenewalEligibilityTitle: 'حالة طلب التجديد',
  SelectLicence_RenewalEligibilityDesc:
    'تنتهي صلاحية الرخصة التالية خلال 53 يوماً. يُتاح لهذه الرخصة التجديد، يُمكنك متابعة عملية التجديد.',
  Global_NextButton: 'التالي',
  Global_CancelButton: 'إلغاء',
  Global_Process: 'الخطوات',
  Global_FillApplicationStep: 'املأ الطلب',
  Global_HideSteps: 'إخفاء الخطوات',
  Global_SelectLicenceStep: 'اختر الرخصة',
  Global_EnterCompanyDetailsStep: 'ادخل تفاصيل الشركة',
  Global_UploadDocumentsStep: 'تحميل المستندات',
  Global_GetLicenceStep: 'احصل على الرخصة',
  Global_ShowSteps: 'عرض الخطوات',
  SelectLicence_NoLicences: 'لا يوجد رخصة مرتبطة بهذا الحساب.',
  CompanyDetails_Title: 'ادخل تفاصيل الشركة',
  CompanyDetails_Description: 'يُرجى إدخال تفاصيل الشركة المطلوبة.',
  CompanyDetails_Radio1: 'ادخل رقم توثيق',
  CompanyDetails_Radio2: 'ادخل تفاصيل الإيجار',
  CompanyDetails_TawtheeqInput: 'رقم توثيق <ادخل الرقم هنا>',
  CompanyDetails_CheckButton: 'تحقق',
  CompanyDetails_ValidTawtheeq: 'رقم توثيق غير صحيح',
  CompanyDetails_ContactInfoTitle: 'ادخل معلومات الاتصال',
  CompanyDetails_ContactInfoDesc:
    'يُرجى إضافة معلومات الاتصال أدناه. ستساعدنا هذه المعلومات في التواصل مع صاحب الطلب لإخطاره بأي تحديثات أو أمور متعلقة بالطلب.',
  CompanyDetails_ContactCheckbox:
    'أنا مسؤول الاتصال لهذا الطلب. اختر جميع معلومات الاتصال اللازمة من تفاصيل الحساب.',
  CompanyDetails_NameInput: 'الاسم <ادخل>',
  CompanyDetails_PhoneNumberInput: 'رقم الهاتف المحمول',
  CompanyDetails_EmailInput: 'عنوان البريد الإلكتروني <ادخل العنوان>',
  Global_AutosaveText: 'تم حفظ طلبك بشكل تلقائي',
  Global_BackButton: 'الرجوع',
  Global_LeaseAgreementNo: 'رقم عقد الإيجار',
  Global_LeaseAmount: 'قيمة الإيجار',
  Global_LeaseDateRange: 'مدة عقد الإيجار',
  Global_MapDesc: 'يُرجى تحديد عنوانك على الخريطة أدناه:',
  UploadDocuments_UploadDocuments: 'تحميل المستندات',
  UploadDocuments_UploadDocsDesc: 'يُرجى تحميل المستندات المطلوبة.',
  AwaitingApproval_ApprovalTitle: 'طلبك قيد الموافقة',
  AwaitingApproval_ApprovalWaitMessage:
    'سيتم تحديث بيانات الصفحة فور الموافقة على طلبك.',
  AwaitingApproval_SubmittedMessage:
    'تم تقديم طلبك بنجاح. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسَّجل. كما يمكنك مراجعة حالة الطلب بنفسك في أي وقت من خلال لوحة التحكم "أدِر شركتك".',
  ApplicationApproved_ApprovedTitle: 'تمت الموافقة على طلبك',
  ApplicationApproved_RefNo: 'الرقم المرجعي:',
  ApplicationApproved_SubmittedDate: 'تاريخ التقديم:',
  ApplicationApproved_ApprovedDesc:
    'تهانينا. تجد أدناه الرقم المرجعي لطلبك ويمكنك استخدامه لاحقاً لتتبع الطلب عبر لوحة التحكم. كما ستصلك جميع التحديثات لهذا الطلب عبر البريد الإلكتروني أو رقم الهاتف المحمول المُسجلين.',
  ApplicationApproved_PaymentSummaryTableTitle: 'ملخص المدفوعات',
  ApplicationApproved_TableClo1: 'الوصف',
  ApplicationApproved_TableCol2: 'الرسوم',
  ApplicationApproved_TableTotal: 'الإجمالي',
  ApplicationApproved_PayButton: 'دفع',
  Global_GetLicenceHideSteps: 'إخفاء الخطوات',
  Global_GetLicenceGetDedApproval: 'احصل على موافقة دائرة التنمية الاقتصادية',
  Global_GetLicenceMakePayment: 'دفع',
  Global_GetLicenceDownloadLicence: 'إصدار الرخصة',
  AwaitingPayment_Title: 'بانتظار تأكيد الدفع',
  AwaitingPayment_RefNo: 'الرقم المرجعي:',
  AwaitingPayment_SubmittedOn: 'تاريخ التقديم:',
  AwaitingPayment_Desc:
    'سيتم تحديث بيانات الصفحة فور تمام عملية الدفع. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجَّل. كما يمكنك مراجعة حالة الطلب بنفسك في أي وقت من خلال لوحة التحكم "أدِر شركتك".',
  LicenceIssued_LicenceRenewedTitle: 'تم تجديد رخصتك الاقتصادية',
  LicenceIssued_LicenceRenewedDesc:
    'تهانينا، تم تجديد رخصتك الاقتصادية. يمكنك إصدار نسخة من الرخصة الجديدة هنا وسيتم إرسال نسخة لك عبر البريد الإلكتروني. تستطيع الآن بدء تأسيس شركتك عبر لوحة التحكم. كما ستصلك جميع التحديثات على حالة الطلب عبر البريد الإلكتروني أو رقم الهاتف المحمول المُسجلين.',
  LicenceIssued_DownloadButton: 'تنزيل',
  LicenceIssued_VisitDashboardButton: 'زُر لوحة التحكم',
  LicenceIssued_Happiness: 'كيف تقيم تجربتك لهذه الخدمة؟',
  LicenceIssued_NextSteps: 'خطوتك التالية لتأسيس شركتك',
  LicenceIssued_NextStepsDesc:
    'بعد أن صدرت رخصتك، يمكنك اختيار الخدمات التالية لإنشاء وتأسيس شركتك.',
  LicenceIssued_NextStepsLink1: 'تمويل الشركة',
  LicenceIssued_NextStepsLink2: 'مُتعقّب التوظيف',
  LicenceIssued_NextStepsLink3: 'افتح حساب بنكي جديد',
  LicenceIssued_NextStepsLink4: 'وثائق التوظيف',
  LicenceIssued_NextStepsLink5: 'اعرف المزيد عن تصاريح الصيانة',
  LicenceIssued_NextStepsLink6: 'خيارات تمويل الشركة',
  LicenceIssued_NextStepsLink7: 'تعرف على إجراءات التوظيف',
  LicenceIssued_NextStepsLink8: 'تسجيل العلامة التجارية',
  ServicePage_ApplicationTableTitle: 'حالة الطلب',
  ServicePage_ApplicationTableFillApplication: 'الطلبات مُعبأ',
  ServicePage_ApplicationTableActionButton: 'الإجراء',
  ServicePage_ApplicationTableApplicationInProgress: 'الطلب قيد الإجراء',
  ServicePage_ApplicationTableSubmitted: 'تاريخ التقديم:',
  ServicePage_ApplicationTableRefNo: 'الرقم المرجعي:',
  ServicePage_ApplicationTableLicenceIssued: 'الرخصة الصادرة',
  ServicePage_ApplicationTableApplicationRejected: 'الطلب مرفوض',
  ServicePage_ApplicationTableActionRequired: 'مطلوب اتخاذ إجراء',
  ServicePage_ApplicationTableFilterShow: 'عرض',
  ServicePage_ApplicationTableFilterRefNo: 'ترتيب حسب الرقم المرجعي',
  ServicePage_ApplicationTableContinue: 'استمرار',
  ServicePage_ApplicationTableCancel: 'إلغاء',
  ApplicationReturned_ApplicationReturnedTitle: 'تمت إعادة طلبك لتجديد الرخصة',
  ApplicationReturned_FileSize: 'السعة القصوى: 200 ميجابايت للملف الواحد',
  ApplicationReturned_FileType: 'نوع الملفات: JPG أو PDF أو PNG',
  ApplicationReturned_ActionRedDesc:
    'يُرجى تحميل المستندات المطلوبة بناءً على التعليقات المذكورة أعلاه.',
  ApplicationReturned_SubmitButton: 'تقديم',
  CompanyDetails_Write: 'اكتب',
  CompanyDetails_SelectDates: 'Select Dates',
  UploadDocuments_NewLeaseContract: 'new lease contract',
  UploadDocuments_CivilDefenceCertificate: 'civil defence certificate',
  UploadDocuments_ADEnvironmentPermit: 'AD environment permit',
  AwaitingPayment_RetryButton: 'RETRY',
  ApplicationReturned_Desc:
    'أعادت دائرة التنمية الاقتصادية طلبك. يرجى الانتباه للملاحظات المذكورة أدناه وإجراء التعديلات اللازمة وتقديم المستندات المفقودة. للمزيد من المعلومات، يمكنك الاتصال بمركز خدمة تــــم أو التواصل مع دائرة التنمية الاقتصادية على الرقم 0097128158888.',
  ApplicationReturned_Feedback: 'تعليقات دائرة التنمية الاقتصادية',
  ApplicationReturned_FeedbackDesc: 'خطاب التفويض غير واضح.',
  ApplicationReturned_ActionReq: 'الإجراءات المطلوبة',
  somethingWentWrong: 'حدث خطأ',
  somethingWentWrongContent:
    'حدث خطأ ما أثناء عملية اكتمال الطلب. الرجاء المحاولة مجدداً.',
  bcrumbsHome: 'الرئيسية',
  bcrumbsBusinessInAbuDhabi: 'Business in Abu Dhabi',
  bcrumbsRegisterYourBusiness: 'Register your Business',
  bcrumbsIndustrialLicences: 'Industrial Licences',
  CompanyDetails_InvalidTawtheeq: 'Tawtheeq number is Invalid',
  Companydetails_requiredField: 'value is required',
  CompanyDetails_ValidateTawtheeq: 'please validate the tawtheeq number',
  SelectLicence_RenewalCheckEligibilityDesc:
    'Please check the eligibility of your licence',
  SelectLicence_RenewalNotEligibilityDesc:
    ' Licence number is not eligible for renewal.',
  UploadDocument_fileUploadFailed: 'File upload failed.',
  CompanyDetails_InvalidPhNo: 'Invalid mobile number',
  CompanyDetails_InvalidEmail: 'عنوان بريد إلكتروني غير صحيح',
  CompanyDetails_InvalidCoordinates: 'Invalid Coordinates.',
  CompanyDetails_SelectLocation: 'Please select your location.',
  SelectLicence_NoteDescriptionPart3:
    ' and try again or contact the Department of Economic Development on +971 2 815 8888.',
  SelectLicence_NoteDescriptionPart2: 'link your licence',
  SelectLicence_NoteDescriptionPart1:
    'If your licence number is not listed above, please ',
  continueProcessDescription: 'يرجى الانتظار قليلاً لحين التحقق من طلبك.',
  continueProcessTitle: 'سيتم الانتقال للصفحة المطلوبة سريعًا',
  Relevant_entity: 'الجهة المسؤولة',
  address: 'أبراج بني ياس، شارع الفلاح - شارع 6 فاطمة بنت مبارك، أبوظبي',
};
