export default {
  Global_ServiceName:
    'Request for Renewal of Economic Licence - Industrial Licence',
  ServicePage_StartButton: 'START',
  ServicePage_ServiceTime: 'Under 6 minutes',
  ServicePage_Fees: 'Approximate Fees: AED 10,000',
  ServicePage_DescriptionTitle: 'Description',
  ServicePage_Description:
    'Through this service, you can renew your existing licences expiring within 60 days. After entering your licence number, if you are eligible for a renewal, you will be asked to submit the relevant documents and make the payment. Once your licence has been renewed, you will be able to download the renewed licence.',
  ServicePage_Process: 'Process',
  ServicePage_Step1: 'Fill Up Application',
  ServicePage_Step1Desc: 'Enter the required information about the company.',
  ServicePage_Step2: 'Get the Licence',
  ServicePage_Step2Desc:
    'Submit your application for approval to the Department of Economic Development.',
  ServicePage_FeesTableTitle: 'Applicable Fees',
  ServicePage_Column1Title: 'Document',
  ServicePage_Column2Title: 'Fees',
  ServicePage_PaymentMethods: 'Payment methods: Credit / Debit Card, e-Dirham',
  SelectLicence_Title: 'Select the Licence',
  SelectLicence_Description:
    'Please select a licence number to check for eligibility. Please note that only the licences expiring in the next 60 days are eligible for renewal. Once the licence has been selected, please proceed to the next steps.',
  SelectLicence_MyLicencesTableTitle: 'My Licences',
  SelectLicence_TableSearch: 'Search',
  SelectLicence_TableColumn1: 'Licence Number',
  SelectLicence_TableColumn2: 'Company Name',
  SelectLicence_PaginationShowing: 'Showing',
  SelectLicence_NoteTitle: 'Note:',
  SelectLicence_NoteDescription:
    "If your licence number is not listed above, please <u><a href='{{Base_path}}/link-licence'>link your licence</a></u> and try again or contact the Department of Economic Development on +971 2 815 8888.",
  SelectLicence_CheckEligibilityButton: 'CHECK IF ELIGIBLE',
  SelectLicence_RenewalEligibilityTitle: 'Status on Renewal',
  SelectLicence_RenewalEligibilityDesc:
    'This licence is expiring in {{days}} days. It is eligible, you may proceed with its renewal.',
  Global_NextButton: 'NEXT',
  Global_CancelButton: 'Cancel',
  Global_Process: 'Process',
  Global_FillApplicationStep: 'Fill Up Application',
  Global_HideSteps: 'Hide steps',
  Global_SelectLicenceStep: 'Select the Licence',
  Global_EnterCompanyDetailsStep: 'Enter Company Details',
  Global_UploadDocumentsStep: 'Upload Documents',
  Global_GetLicenceStep: 'Get the Licence',
  Global_ShowSteps: 'Show steps',
  SelectLicence_NoLicences:
    'You do not have any licence linked to your account. ',
  CompanyDetails_Title: 'Enter Company Details',
  CompanyDetails_Description: 'Please enter the required company details. ',
  CompanyDetails_Radio1: 'Enter tawtheeq number',
  CompanyDetails_Radio2: 'Enter lease details',
  CompanyDetails_TawtheeqInput: 'TAWTHEEQ NUMBER',
  CompanyDetails_CheckButton: 'CHECK',
  CompanyDetails_ValidTawtheeq: 'Tawtheeq number is valid',
  CompanyDetails_ContactInfoTitle: 'Enter Contact Information',
  CompanyDetails_ContactInfoDesc:
    'Please enter the contact details below. This information will be used for all future correspondence related to this application.  ',
  CompanyDetails_ContactCheckbox:
    'I am the contact person for this application. Pick all contact information necessary from the account details.',
  CompanyDetails_NameInput: 'NAME',
  CompanyDetails_PhoneNumberInput: 'MOBILE NUMBER',
  CompanyDetails_EmailInput: 'EMAIL ADDRESS',
  Global_AutosaveText: 'Your application is being autosaved.',
  Global_BackButton: 'BACK',
  Global_LeaseAgreementNo: 'LEASE AGREEMENT NUMBER',
  Global_LeaseAmount: 'LEASE AMOUNT',
  Global_LeaseDateRange: 'LEASE AGREEMENT DATE RANGE',
  Global_MapDesc: 'Please pin your exact address on the map below:',
  UploadDocuments_UploadDocuments: 'Upload Documents',
  UploadDocuments_UploadDocsDesc: 'Please upload the requested documents.',
  AwaitingApproval_ApprovalTitle: 'Your Application Approval Is in Progress',
  AwaitingApproval_ApprovalWaitMessage:
    'This page will refresh and update once your application has been approved.',
  AwaitingApproval_SubmittedMessage:
    'Your application has been successfully submitted. You will be notified about changes to your application’s status on the registered email address and mobile number. You may also check the status of your application at any time by visiting the Manage Your Business dashboard.',
  ApplicationApproved_ApprovedTitle: 'Your Application Has Been Approved',
  ApplicationApproved_RefNo: 'Reference Number: ',
  ApplicationApproved_SubmittedDate: 'Submitted On:',
  ApplicationApproved_ApprovedDesc:
    'Congratulations! Please take note of the reference number. You will be able to use this reference number to track this application from your dashboard in the future. You will be notified about changes to your application’s status on the registered email address and mobile number.',
  ApplicationApproved_PaymentSummaryTableTitle: 'Payment Summary',
  ApplicationApproved_TableClo1: 'Description',
  ApplicationApproved_TableCol2: 'Fees',
  ApplicationApproved_TableTotal: 'TOTAL',
  ApplicationApproved_PayButton: 'PAY',
  Global_GetLicenceHideSteps: 'Hide steps',
  Global_GetLicenceGetDedApproval: 'Get DED Approval',
  Global_GetLicenceMakePayment: 'Make the Payment',
  Global_GetLicenceDownloadLicence: 'Download the Licence',
  AwaitingPayment_Title: 'Awaiting Payment Confirmation',
  AwaitingPayment_RefNo: 'Reference Number: ',
  AwaitingPayment_SubmittedOn: 'Submitted On:',
  AwaitingPayment_Desc:
    'This page will refresh once your payment is processed. You will be notified about changes to your application’s status on the registered email address and mobile number. You may also check the status of your application at any time by visiting the Manage Your Business dashboard.',
  LicenceIssued_LicenceRenewedTitle: 'Your Industrial Licence Has Been Renewed',
  LicenceIssued_LicenceRenewedDesc:
    'Congratulations! Your economic licence has been renewed. You can download the licence document here, a copy has been emailed to you. You can now start setting up your business from your dashboard. You will be notified about changes to your application’s status on the registered email address and mobile number.',
  LicenceIssued_DownloadButton: 'DOWNLOAD',
  LicenceIssued_VisitDashboardButton: 'VISIT DASHBOARD',
  LicenceIssued_Happiness: 'How was your experience using this service?',
  LicenceIssued_NextSteps: 'Your Next Steps to Set up Your Business',
  LicenceIssued_NextStepsDesc:
    'Now that your licence has been issued, you may consider the following services to continue with your business setup.',
  LicenceIssued_NextStepsLink1: 'Fund Your Business ',
  LicenceIssued_NextStepsLink2: 'Recruitment Tracker',
  LicenceIssued_NextStepsLink3: 'Open a Bank Account ',
  LicenceIssued_NextStepsLink4: 'Employment Documents ',
  LicenceIssued_NextStepsLink5: 'Learn About Maintenance Permits',
  LicenceIssued_NextStepsLink6: 'Financing and Funding Options',
  LicenceIssued_NextStepsLink7: 'Learn More About Hiring ',
  LicenceIssued_NextStepsLink8: 'Trademark Registration ',
  ServicePage_ApplicationTableTitle: 'Application Status',
  ServicePage_ApplicationTableFillApplication: 'Filled application',
  ServicePage_ApplicationTableActionButton: 'ACTION',
  ServicePage_ApplicationTableApplicationInProgress: 'Application in progress',
  ServicePage_ApplicationTableSubmitted: 'Date of Submission:',
  ServicePage_ApplicationTableRefNo: 'Reference Number:',
  ServicePage_ApplicationTableLicenceIssued: 'Licence issued',
  ServicePage_ApplicationTableApplicationRejected: 'Application rejected',
  ServicePage_ApplicationTableActionRequired: 'Action required',
  ServicePage_ApplicationTableFilterShow: 'Show',
  ServicePage_ApplicationTableFilterRefNo: 'Filter by Reference Number',
  ServicePage_ApplicationTableContinue: 'CONTINUE',
  ServicePage_ApplicationTableCancel: 'Cancel',
  ApplicationReturned_ApplicationReturnedTitle:
    'Your Application for Licence Renewal Has Been Returned',
  ApplicationReturned_FileSize: 'Maximum limit: 20MB per file',
  ApplicationReturned_FileType: 'File types: JPG, PDF, PNG',
  ApplicationReturned_ActionRedDesc:
    'Please upload the required documents based on the feedback above.',
  ApplicationReturned_SubmitButton: 'SUBMIT',
  CompanyDetails_Write: 'Write',
  CompanyDetails_SelectDates: 'Select Dates',
  UploadDocuments_NewLeaseContract: 'new lease contract',
  UploadDocuments_CivilDefenceCertificate: 'civil defence certificate',
  UploadDocuments_ADEnvironmentPermit: 'AD environment permit',
  AwaitingPayment_RetryButton: 'RETRY',
  ApplicationReturned_Desc:
    'Your application has been returned by the DED. Please check the feedback below, and make the required amendments and/or submit the requested documents. For further assistance, please contact TAMM support or alternatively call the Department of Economic Development at +971 2 815 8888.',
  ApplicationReturned_Feedback: 'Feedback from DED',
  ApplicationReturned_FeedbackDesc:
    'The authorisation letter uploaded is not clear.',
  ApplicationReturned_ActionReq: 'Actions Required',
  somethingWentWrong: 'Something Went Wrong',
  somethingWentWrongContent:
    'An error occurred while completing your request. Please try again later.',
  bcrumbsHome: 'Home',
  bcrumbsBusinessInAbuDhabi: 'Business in Abu Dhabi',
  bcrumbsRegisterYourBusiness: 'Register your Business',
  bcrumbsIndustrialLicences: 'Industrial Licences',
  CompanyDetails_InvalidTawtheeq: 'Tawtheeq number is Invalid',
  Companydetails_requiredField: 'value is required',
  CompanyDetails_ValidateTawtheeq: 'please validate the tawtheeq number',
  SelectLicence_RenewalCheckEligibilityDesc:
    'Please check the eligibility of your licence',
  SelectLicence_RenewalNotEligibilityDesc:
    ' Licence number is not eligible for renewal.',
  UploadDocument_fileUploadFailed: 'File upload failed.',
  CompanyDetails_InvalidPhNo: 'Invalid mobile number',
  CompanyDetails_InvalidEmail: 'Invalid email address',
  CompanyDetails_InvalidCoordinates: 'Invalid Coordinates.',
  CompanyDetails_SelectLocation: 'Please select your location.',
  fieldset_title: 'hellwo',
  SelectLicence_NoteDescriptionPart3:
    ' and try again or contact the Department of Economic Development on +971 2 815 8888.',
  SelectLicence_NoteDescriptionPart2: 'link your licence',
  SelectLicence_NoteDescriptionPart1:
    'If your licence number is not listed above, please ',
  continueProcessDescription:
    'Please be patient while we identify your application',
  continueProcessTitle: 'You will be redirected shortly',
  Relevant_entity: 'Relevant Entity',
  address:
    'Baniyas Towers, Al Falah Street - Fatima bint Mubarak St 6, Abu Dhabi',
};
