const PERMIT_CATEGORY_SIGNBOARD_AD = 'signboardAd';
const PERMIT_CATEGORY_ADDITIONAL_AD = 'additionalAdPermit';
const PERMIT_CATEGORY_MACHINE_AD = 'machineAd';
const PERMIT_CATEGORY_MOBILE_AD = 'mobileAd';
const PERMIT_CATEGORY_PROMOTIONAL_AD = 'promotionalAd';
export {
  PERMIT_CATEGORY_SIGNBOARD_AD,
  PERMIT_CATEGORY_ADDITIONAL_AD,
  PERMIT_CATEGORY_MACHINE_AD,
  PERMIT_CATEGORY_MOBILE_AD,
  PERMIT_CATEGORY_PROMOTIONAL_AD,
};
