export default {
  'serviceCard-desc': 'دفع رسوم مراجعة أنظمة البيئة والصحة والسلامة',
  process: 'خطوات العملية',
  'selectLicence-title': 'اختر الرخصة ',
  application_contact: 'بيانات الاتصال لصاحب الطلب',
  'applicationApproved-downloadButton': 'تنزيل الإيصال',
  make_payment: 'إتمام عملية الدفع',
  relevant_entity: 'الجهة الحكومية ذات الصلة',
  'selectLicence-description':
    'الرجاء اختيار رخصة صناعية صالحة للحصول على نسخة صحيحة من الرخصة.',
  search_licence: 'البحث في الرُخص',
  'selectLicence-licenceColumn': 'رقم الرخصة ',
  error_msg: 'الرجاء اختيار رخصة',
  'global-next': 'التالي',
  link_cancel: 'إلغاء',
  business_in_abudhabi: 'الأعمال في أبوظبي',
  register_your_business: 'سجّل شركتك',
  home: 'الصفحة الرئيسية',
  contact_description:
    'يُرجى تقديم بيانات الاتصال أدناه، والتي ستُسخدم لغايات التواصل معك بشأن طلبك.',
  'applicantDetails-nameField': 'الاسم ',
  'applicantDetails-numberField': 'رقم الهاتف المتحرك ',
  'applicantDetails-emailField': 'عنوان البريد الإلكتروني ',
  contact_fill_details: 'Fill Details',
  fee_amount: 'ادفع الرسوم',
  write: 'اكتب',
  'global-back': 'الرجوع',
  'applicantDetails-checkboxContact': 'أنا الشخص المتوفر للاتصال لهذا الطلب.',
  'applicationApproved-dashboardButton': 'زر لوحة التحكم',
  'paymentFailed-tryAgainButton': 'حاول مرة أخرى ',
  'paymentFailed-supportButton': 'تواصل مع خدمة العملاء',
  error_contactName: 'هذه الخانة مطلوبة\t',
  error_phoneNumber: 'هذه الخانة مطلوبة ويجب أن تحتوي على رقم هاتف محمول',
  error_email: 'هذا الخانة مطلوبة ويجب أن تحتوي على عنوان بريد إلكتروني.',
  'paymentSummary-title': 'تمت الموافقة على طلبك',
  'paymentSummary-description':
    'أصدرت دائرة التنمية الاقتصادية رقماً مرجعياً لهذه المعاملة. ستصلك التحديثات عن طلبك على البريد الإلكتروني المسجل ورقم الهاتف المتحرك. يرجى الاستمرار وإتمام الدفع هنا. ',
  'paymentSummary-tabletitle': 'ملخص المدفوعات',
  'paymentWaiting-title': 'بانتظار تأكيد الدفع',
  'paymentWaiting-description':
    'سيتم تحديث بيانات الصفحة فور تمام عملية الدفع. سيتم إخطارك بالتحديثات على الطلب من خلال البريد الإلكتروني أو الرسائل النصية القصيرة لرقم الهاتف المحمول المسجل. كما يمكنك مراجعة حالة الطلب بنفسك  في أي وقت من خلال لوحة التحكم "أدِر شركتك".',
  payment_success_title: 'تم استلام المدفوعات',
  payment_success_des:
    'صدر إيصال دفع رسوم مراجعة أنظمة البيئة والصحة والسلامة عن رقم الرخصة  IN-1000001 . يمكنك تنزيل جميع الملفات المطلوبة أدناه. ',
  'paymentFailed-title': 'فشلت عملية الدفع',
  'paymentFailed-description':
    'نعتذر، لم تنجح عملية الدفع. بإمكانك المحاولة مرة أخرى في وقت لاحق. إذا واجهتك أي مشكلة، الرجاء الإبلاغ عنها.',
  'somethingWentWrong-title': 'حصل خطأ ما ',
  'somethingWentWrong-description':
    'حصل خطأ ما أثناء محاولة إكمال الطلب. الرجاء المحاولة مرة أخرى.',
  no_info_title: 'لم يتم العثور على أية معلومات',
  no_info_des: 'لا يمكن تعديل هذه الرخصة',
  'global-reference': 'الرقم المرجعي:',
  'global-submitted': 'تاريخ التقديم:',
  step_selectLicence: 'اختر الرخصة',
  'applicantDetails-title': 'بيانات الاتصال لصاحب الطلب',
  step_makePayment: 'السداد',
  'waitingApproval-title': 'تأكيد الطلب',
  subStep_payAmount: 'ادفع الرسوم',
  step_downloadCertificate: 'تنزيل الإيصال',
  waitingPage_title: 'تأكيد الطلب',
  timeoutMessage: 'انتهت الجلسة. يرجى إعادة التحميل لتحديثها مرة أخرى',
  somethingWentWrong: 'حدث خطأ ما ',
  bc_home: 'الصفحة الرئيسية',
  bc_digitalServices: 'الخدمات الرقمية',
  bc_DED: 'دائرة التنمية الاقتصادية',
  accountUpgradeRequired: 'مطلوب تحديث الحساب',
  accountUpgradeDes:
    'يجب ترقية حسابك، لتتمكن من الحصول على الخدمة، لترقية الحساب، اضغط على الرابط.',
  upgradeYourAccount: 'يرجى تحديث حسابك',
  'selectLicence-tableTitle': 'جميع رُخصي',
  'paymentSummary-paybutton': 'ادفع',
  'paymentSummary-descriptionColumn': 'الوصف',
  'paymentSummary-priceColumn': 'السعر',
  'selectLicence-companyColumn': 'اسم الشركة ',
  'applicationApproved-title': 'تم استلام المدفوعات',
  'applicationApproved-description':
    'صدر إيصال دفع رسوم مراجعة أنظمة البيئة والصحة والسلامة عن رقم الرخصة  IN-1000001 . بإمكانك تنزيل جميع الملفات المطلوبة أدناه. ',
  'step_paymentSummary-tabletitle': 'السداد',
  'step_applicationApproved-downloadButton': 'تنزيل الإيصال',
  'paymentWaiting-waitingMessage':
    'ستظهر لك شاشة بوابة الدفع تلقائياً في نافذة جديدة.',
  'paymentWaiting-waitingMessageDescription':
    'إن لم تفتح الشاشة بشكل تلقائي، الرجاء الضغط هنا.',
  step_enterContactDetails: 'بيانات الاتصال لصاحب الطلب',
  subStep_requestConfirmation: 'تأكيد الطلب',
  button_cancel: 'إلغاء',
  noActiveLicenceDescription: 'لا تظهر أي رخصة مرتبطة بحسابك.',
  noActiveLicenceTitle: 'لا يوجد أي رخص سارية',
  waitingApprovalWaitingMessage: 'الرجاء الانتظار للحصول على معلومات إضافية.',
  paymentWaitingWaitingMessage:
    'ستظهر لك شاشة بوابة الدفع تلقائياً في نافذة جديدة.',
  continueProcessTitle: 'سيتم الانتقال للصفحة المطلوبة سريعًا',
  continueProcessDescription: 'يرجى الانتظار قليلاً لحين التحقق من طلبك.',
  start: 'ابدأ',
  pleaseLogIn: 'يُرجى تسجيل الدخول',
  address: 'أبراج بني ياس، شارع الفلاح - شارع 6 فاطمة بنت مبارك، أبوظبي',
  aed: 'درهم',
  nameValidation: 'هذا الحقل إجباري ويجب أن يحتوي على 5 أحرف على الأقل',
  'form.cancel': 'إلغاء',
};
