export default {
  'serviceCard-desc': 'EHSMS Reviewing Fee Payment',
  process: 'Process',
  'selectLicence-title': 'Select Licence',
  application_contact: 'Application Contact',
  'applicationApproved-downloadButton': 'DOWNLOAD RECEIPT',
  make_payment: 'Make Payment',
  relevant_entity: 'Relevant Entity',
  'selectLicence-description':
    'Please select the valid Industrial Licence for which you wish to make a payment through the EHSMS Reviewing Fee Payment service.',
  search_licence: 'SEARCH LICENCE',
  'selectLicence-licenceColumn': 'Licence Number',
  error_msg: 'Please select a licence',
  'global-next': 'NEXT',
  link_cancel: 'Cancel',
  business_in_abudhabi: 'Business in Abu Dhabi',
  register_your_business: 'Register Your Business',
  home: 'Home',
  contact_description:
    'Please provide the details below. These contact details will be used for any clarifications or questions related to this application.',
  'applicantDetails-nameField': 'NAME',
  'applicantDetails-numberField': 'MOBILE NUMBER',
  'applicantDetails-emailField': 'EMAIL ADDRESS',
  contact_fill_details: 'Fill Details',
  fee_amount: 'Pay Amount',
  write: 'Write',
  'global-back': 'BACK',
  'applicantDetails-checkboxContact':
    'I am the contact person for this application',
  'applicationApproved-dashboardButton': 'VISIT DASHBOARD',
  'paymentFailed-tryAgainButton': 'TRY AGAIN',
  'paymentFailed-supportButton': 'CONTACT SUPPORT',
  error_contactName: 'This field is required',
  error_phoneNumber: 'This field is required and must be a mobile number',
  error_email: 'This field is required and must be an email address',
  'paymentSummary-title': 'Your Application Has Been Approved',
  'paymentSummary-description':
    'The Department of Economic Development has generated a reference number for this transaction. You will be receiving all updates related to this application on the registered email and mobile number. Please proceed with your payment here.',
  'paymentSummary-tabletitle': 'Payment Summary',
  'paymentWaiting-title': 'Awaiting Payment Confirmation',
  'paymentWaiting-description':
    "This page will refresh once your payment is processed. You will be notified about changes to your application's status on the registered email address and mobile number. You may also check the status of your application at any time by visiting the Manage Your Business.",
  payment_success_title: 'Your payment has been received for EHMS reviewing',
  payment_success_des:
    'EHMS Reviewing Fees Payment Receipt has generated for licence number IN-1000001.You can download the relevant documents from the link below.',
  'paymentFailed-title': 'Your Payment Was Unsuccessful',
  'paymentFailed-description':
    'Unfortunately, the payment could not be processed. You can try again or come back later. If you encountered any error, please report this issue. ',
  'somethingWentWrong-title': 'Something Went Wrong',
  'somethingWentWrong-description':
    'An error occurred while trying to complete your request. Please try again.',
  no_info_title: 'No information found',
  no_info_des:
    'We are unable to find any details with the details provided. Please try again.',
  'global-reference': 'Reference number:',
  'global-submitted': 'Submitted on:',
  step_selectLicence: 'Select Licence',
  'applicantDetails-title': 'Application Contact',
  step_makePayment: 'Make Payment',
  'waitingApproval-title': 'Confirming Your Request',
  subStep_payAmount: 'Pay amount',
  step_downloadCertificate: 'Download Receipt',
  waitingPage_title: 'Confirming Request',
  timeoutMessage: 'Session timed out. Kindly reload the page',
  somethingWentWrong: 'Something went wrong\t',
  bc_home: 'Home',
  bc_digitalServices: 'Digital Services',
  bc_DED: 'Department of Economic Development',
  accountUpgradeRequired: 'Account upgrade required',
  accountUpgradeDes:
    'Your log in credentials need to be upgraded before you can proceed with this service. Please follow the link to complete the process.',
  upgradeYourAccount: 'Upgrade Your Account',
  'selectLicence-tableTitle': 'My Licences',
  'paymentSummary-paybutton': 'PAY',
  'paymentSummary-descriptionColumn': 'Description',
  'paymentSummary-priceColumn': 'Fees',
  'selectLicence-companyColumn': 'Company Name',
  'applicationApproved-title': 'Your Payment Has Been Received',
  'applicationApproved-description':
    'EHSMS Reviewing Fees Payment Receipt has been generated for licence number IN-1000001. You can download all the relevant documents below.',
  'step_paymentSummary-tabletitle': 'Make Payment',
  'step_applicationApproved-downloadButton': 'Download Receipt',
  'paymentWaiting-waitingMessage':
    'Your payment gateway will now open on a new tab.',
  'paymentWaiting-waitingMessageDescription':
    'If this does not open automatically, please click here.',
  step_enterContactDetails: 'Application Contact',
  subStep_requestConfirmation: 'Confirming request',
  button_cancel: 'Cancel',
  noActiveLicenceDescription:
    'You seem to have no active licences linked to this account',
  noActiveLicenceTitle: 'No active licences',
  waitingApprovalWaitingMessage: 'Please wait for more information.',
  paymentWaitingWaitingMessage:
    'Your payment gateway will now open on a new tab.',
  continueProcessTitle: 'You will be redirected shortly',
  continueProcessDescription:
    'Please be patient while we identify your application',
  start: 'Start',
  pleaseLogIn: 'Please Login',
  address:
    'Baniyas Towers, Al Falah Street - Fatima bint Mubarak St 6, Abu Dhabi',
  aed: 'AED',
  nameValidation: 'Name field should contain at least 5 characters.',
  'form.cancel': 'Cancel',
};
