export default {
  public: [
    // test case
    '/pub-test',
    // feedback
    '/feedback',
    // lookup
    '/getYamliSuggestions',
    '/getCountriesList',
    // ded
    '/tradeNameCheck',
    '/businessCertificate',
    '/getActivities',
    '/businessNameSuggestion',
    '/checkInvestorEligibility',
    '/getRequirements',
    '/businessLicenseFees',
    '/autoFillBusinessName',
    '/locationActivity',
    '/authorizedOperations',
    '/sectorByActivity',
    '/getLicenceDetailsV3',
    '/getTradeLicenseDetails',
    '/getTradeNames',
    '/getLocations',
    '/getLegalTypes',
    '/getBusinessActivities',
    '/getBusinessCategories',
    '/getBusinessFees',
    '/getBusinessRequirements',
    '/checkApplicationStatus',
    '/newActivityService',
    '/linkLicense',
    '/sendResponseEmail',
    '/sendResponseSms',
    // adu bpm
    '/bpm/tradeName/start',
    '/bpm/tradeName/message',
    '/bpm/tradeName/:instanceId/variables',
    '/bpm/tradeName/:instanceId/state',
    // tawtheeq
    '/getTawtheeqInfo',
    // adu
    '/uploadDocument',
    '/upload/uploadDocuments',
    '/relatedRecords',
    '/listTradeLicenses',
    '/RelatedRecords',
    '/listRelatedRecords',
    // moa
    '/moa/getMoaHtml',
    '/moa/sendInviteEmails',
    // scad
    '/goodsInquiry/getStoreItemByCategory',
    '/goodsInquiry/getItem',
    '/goodsInquiry/getCategories',
    '/goodsInquiry/searchStoreItems',
    '/getCommercialPromotions',
    '/relatedRecords',
    // adu bpm
    '/bpm/business-licence-fine/start',
    '/bpm/business-licence-fine/message',
    '/bpm/business-licence-fine/:instanceId/state',
    '/bpm/business-licence-fine/:instanceId/variables',
    '/bpm/pay-application-fees/start',
    '/bpm/pay-application-fees/message',
    '/bpm/pay-application-fees/:instanceId/variables',
    '/bpm/pay-application-fees/:instanceId/state',
    '/bpm/addNewActivity/start',
    '/bpm/addNewActivity/message',
    '/bpm/addNewActivity/:instanceId/variables',
    '/bpm/addNewActivity/:instanceId/state',
    // io
    '/io/getApplications',
    // tawtheeq
    '/getTawtheeqDetailsV4',
    // scad
    '/getCommercialPromotions',
    '/goodsInquiry/getStoreItemByCategory',
    '/goodsInquiry/getItem',
    '/goodsInquiry/getCategories',
    '/goodsInquiry/searchStoreItems',
    '/issueLetter',
    // public bpmn
    '/listTradeLicensesV3',
    '/issueLetter',
    '/listTradeLicenses',
    '/consumerAndBusinessProtection',
    '/bpm/goldenServices/start',
    '/bpm/goldenServices/message',
    '/bpm/goldenServices/:instanceId/state',
    '/bpm/goldenServices/:instanceId/variables',

    '/io/amendmentByEmiratesId',
    '/io/amendmentUpdate',
    '/io/amendmentById',
    '/esri/getToken',
    '/esri/mapQuery/**',

    '/ms-call/gateway/TammJourneyCms/1.0/newsListing',
    '/ms-call/gateway/TammJourneyCms/1.0/pressReleaseListing',
    '/ms-call/gateway/TammJourneyCms/1.0/newsInfo',
    '/ms-call/gateway/TammJourneyCms/1.0/pageInfo',
    '/ms-call/gateway/TammJourneyCms/1.0/cmsDictionary',
  ],
  loggedIn: [
    '/loggedin-test',
    '/uploadDocument',
    '/permitRequirementsInquiry',
    '/bpm/verified-route',
    '/bpm/:licenseName/start',
    '/bpm/:licenseName/diagram',
    '/bpm/:licenseName/diagram/:instanceType',
    '/bpm/:licenseName/start/:processDefinitionId',
    '/bpm/:licenseName/message',
    '/bpm/:licenseName/redirect',
    '/bpm/:licenseName/:instanceId/state',
    '/bpm/:processName/:instanceId/variables',
    '/bpm/:processName/:instanceId/redirect',
    '/ms-call/gateway/*',
  ],
  verified: [
    // adu bpm
    '/bpm/verified-route',
    '/bpm/:licenseName/start',
    '/bpm/:licenseName/diagram',
    '/bpm/:licenseName/diagram/:instanceType',
    '/bpm/:licenseName/start/:processDefinitionId',
    '/bpm/:licenseName/message',
    '/bpm/:licenseName/redirect',
    '/bpm/:licenseName/:instanceId/state',
    '/bpm/:processName/:instanceId/variables',
    '/bpm/:processName/:instanceId/redirect',
    '/moa/getMoaHtml',
    '/moa/sendInviteEmails',
    '/io/getApplications',
    '/io/getPermits',
    // add specific rules
    // '/ms-call/gateway/TammJourneyDed/1.0/dedBusiness/authenticateUser',
    // or add wildcard rules
    '/ms-call/gateway/*',
  ],
};
